### ISSUE TITLE
Image not found, when running plaidml-setup (on macOs)

### ISSUE THREAD

**Issue by SamVanhoutte** [plaidml/plaidml#1024]
Hello all

I have the exact same issue as described at #277 . 
I tried all suggestions: 

- uninstall/reinstall the plaidml packages.  
- install inside or outside a virtuel env.  

Nothing works and helps.  I keep getting the image not found exception.  Did this ever got fixed?  The issue seems closed, but without a solution.

This is the output of `plaidml-setup`:

```
Traceback (most recent call last):
  File "/Users/samvanhoutte/plaidml/bin/plaidml-setup", line 8, in <module>
    sys.exit(main())
  File "/Users/samvanhoutte/plaidml/lib/python3.7/site-packages/plaidml/plaidml_setup.py", line 16, in main
    ctx = plaidml.Context()
  File "/Users/samvanhoutte/plaidml/lib/python3.7/site-packages/plaidml/__init__.py", line 892, in Context
    return plaidml.context.Context(_lib())
  File "/Users/samvanhoutte/plaidml/lib/python3.7/site-packages/plaidml/__init__.py", line 789, in _lib
    _impl_lib = _Library()
  File "/Users/samvanhoutte/plaidml/lib/python3.7/site-packages/plaidml/__init__.py", line 174, in __init__
    lib = ctypes.cdll.LoadLibrary(os.environ['PLAIDML_NATIVE_PATH'])
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libplaidml.dylib:/Users/samvanhoutte/opt/miniconda3/bin:/Users/samvanhoutte/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.local/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands, 6): image not found
(plaidml) (base) macbook-sam:~ samvanhoutte$ 
```

**Comment by zap-wizard** [comment]
It looks like your path to _libplaidml.dylib_ is really messed up...
Try running this
```
export PLAIDML_NATIVE_PATH=/Users/samvanhoutte/plaidml/lib/libplaidml.dylib
```
Or replace the path with whatever it is, if I didn't guess it right.

**Comment by SamVanhoutte** [comment]
Well, it seems that indeed my environment variables were "messed up" quite a bit.  I reset everything and after that, things got back to normal.
Thanks for the heads up.  Will close the issue

**Comment by jtlz2** [comment]
Worked for me - but not on High Sierra 10.13
