### ISSUE TITLE
Error while input_rpn_match = KL.Input(shape=[None, 1], name="input_rpn_match", dtype=tf.int32)

### ISSUE THREAD

**Issue by nitinkumartech** [plaidml/plaidml#1026]
Was trying to port Matterport Mask-RCNN to use plaidml, but it errors out after switching the backend

Full stack trace below:

Traceback (most recent call last):
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\plaidml\tile.py", line 105, in convert_np_dtype_to_pml
    return NUMPY_DTYPE_TO_PLAIDML[dtype]
KeyError: tf.int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "balloon.py", line 331, in <module>
    model_dir=args.logs)
  File "E:\dev\Mask_RCNN\mrcnn\model.py", line 1839, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "E:\dev\Mask_RCNN\mrcnn\model.py", line 1864, in build
    shape=[None, 1], name="input_rpn_match", dtype=tf.int32)
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\keras\engine\input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\keras\engine\input_layer.py", line 87, in __init__
    name=self.name)
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\plaidml\keras\backend.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\plaidml\keras\backend.py", line 1187, in placeholder
    dtype = ptile.convert_np_dtype_to_pml(dtype or floatx())
  File "C:\Users\Cypher\Miniconda3\envs\sudoku\lib\site-packages\plaidml\tile.py", line 107, in convert_np_dtype_to_pml
    raise ValueError("Unrecognized Numpy dtype {}".format(dtype))
ValueError: Unrecognized Numpy dtype <dtype: 'int32'>

**Comment by liweikeai2002** [comment]
I had the same problem. Is there a solution?
