### ISSUE TITLE
Plaidml-setup fails in conda environment on MacOS

### ISSUE THREAD

**Issue by zap-wizard** [plaidml/plaidml#1027]
**Running plaidml-setup fails on macOS in a conda environment.**

I have installed tensorflow with
`conda install -c conda-forge tensorflow`
and then plaidml with keras
`pip install plaidml-keras plaidbench`

**After that, running** `plaidml-setup` **returns this error:**

```
Traceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/python/bin/plaidml-setup", line 8, in <module>
    sys.exit(main())
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/site-packages/plaidml/plaidml_setup.py", line 16, in main
    ctx = plaidml.Context()
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/site-packages/plaidml/__init__.py", line 892, in Context
    return plaidml.context.Context(_lib())
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/site-packages/plaidml/__init__.py", line 789, in _lib
    _impl_lib = _Library()
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/site-packages/plaidml/__init__.py", line 174, in __init__
    lib = ctypes.cdll.LoadLibrary(os.environ['PLAIDML_NATIVE_PATH'])
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/Users/username/opt/anaconda3/envs/python/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/username/opt/anaconda3/envs/python/lib/libplaidml.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/username/opt/anaconda3/envs/python/lib/libplaidml.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/username/opt/anaconda3/envs/python/lib/libplaidml.dylib
```

Before this I had also a different issue, similar to #277, but it went away after running following commands in terminal: _(I think first one solved the problem)_
```
export PLAIDML_NATIVE_PATH=/Users/username/opt/anaconda3/envs/python/lib/libplaidml.dylib
export RUNFILES_DIR=/Users/username/opt/anaconda3/envs/python/share/plaidml
```

_I'm running MacOS 13.6 
Python version in the environment is 3.7.7_

**Comment by zap-wizard** [comment]
Thanks for help!

**Comment by brianretford** [comment]
Ah, we pretty much only support the latest version of macos, sadly. If you build it from source it will probably work.

**Comment by zap-wizard** [comment]
Ok, thanks for help. Will try.

**Comment by zap-wizard** [comment]
Building it from source failed. But I managed to run `plaidml-setup` on an older version. (0.6.4)
`pip install plaidml=0.6.4`

**Comment by zap-wizard** [comment]
I got the version 0.7.0 working by replacing the `libplaidml.dylib` with the one in the previous version (0.6.4)
