### ISSUE TITLE
plaidml-setup on Windows 10 - "Could not find module plaidml.dll"

### ISSUE THREAD

**Issue by kushpet** [plaidml/plaidml#1033]
Hi!
I tried to install plaidml and plaidml-keras in virtual environment 'plaidml' on Windows 10.
I got the following configuration:

(plaidml) C:\Users\user>pip list
Package             Version
------------------- -------
cffi                1.14.0
enum34              1.1.10
h5py                2.10.0
Keras               2.2.4
Keras-Applications  1.0.8
Keras-Preprocessing 1.1.0
numpy               1.18.3
pip                 20.0.2
plaidml             0.7.0
plaidml-keras       0.7.0
pycparser           2.20
PyYAML              5.3.1
scipy               1.4.1
setuptools          46.1.3
six                 1.14.0
wheel               0.34.2

But when I tried to run plaidml-setup, I got the following error:

(plaidml) C:\Users\user>plaidml-setup
Traceback (most recent call last):
  File "c:\users\user\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 154, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "c:\users\user\appdata\local\programs\python\python38\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "c:\users\user\appdata\local\programs\python\python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'c:\users\user\envs\plaidml\lib\site-packages\plaidml\plaidml.dll'. Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Envs\plaidml\Scripts\plaidml-setup.exe\__main__.py", line 7, in <module>
  File "c:\users\user\envs\plaidml\lib\site-packages\plaidml\plaidml_setup.py", line 16, in main
    ctx = plaidml.Context()
  File "c:\users\user\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 892, in Context
    return plaidml.context.Context(_lib())
  File "c:\users\user\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 789, in _lib
    _impl_lib = _Library()
  File "c:\users\user\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 176, in __init__
    lib = load_library('plaidml.dll', ['Library', 'bin'])
  File "c:\users\user\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 166, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "c:\users\user\appdata\local\programs\python\python38\lib\ctypes\__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "c:\users\user\appdata\local\programs\python\python38\lib\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'c:\users\user\envs\plaidml\Library\bin\plaidml.dll'. Try using the full path with constructor syntax.

The file plaidml.dll actually exists in the file system:

(plaidml) C:\Users\user>dir c:\users\user\envs\plaidml\Library\bin\plaidml.dll
 Том в устройстве C имеет метку OS
 Серийный номер тома: 4275-1396

 Содержимое папки c:\users\user\envs\plaidml\Library\bin

27.04.2020  23:14        30 768 128 plaidml.dll
               1 файлов     30 768 128 байт
               0 папок  15 522 115 584 байт свободно

The Python version is 3.8.0

Could you please advise?

**Comment by kushpet** [comment]
The solution was to install [Visual Studio 2015 runtime redistributable](https://www.microsoft.com/en-ca/download/details.aspx?id=48145)
I tried to install plaidml on the other PC with Windows 7. When I tried to run plaidml-setup, it gave the same error but either error window with "vcruntime140_1.dll not found". Solution for this dll problem I found on [Stackoverflow](https://stackoverflow.com/questions/58828982/vcruntime140-1-dll-missing-after-building-solution-with-c)
