### ISSUE TITLE
TimeDistributed layer fails on nested models

### ISSUE THREAD

**Issue by kpot** [plaidml/plaidml#108]
Hi,

Trying to adapt my project to PlaidML (latest version available) I found that `keras.layers.TimeDistributed` doesn't work with nested models [as it supposed to do](https://keras.io/getting-started/functional-api-guide/#all-models-are-callable-just-like-layers). Although it works with a simple layer, like Dense.

Here is a minimalistic example which works with TF but fails with PlaidML:
```
try:
    import plaidml.keras
    plaidml.keras.install_backend()
except ImportError:
    pass

from keras.layers import Dense, TimeDistributed, Input
from keras.models import Model

INPUT_WIDTH = 10


def make_sub_model():
    inp = Input(shape=(INPUT_WIDTH,))
    out = Dense(INPUT_WIDTH)(inp)
    model = Model(inp, out)
    return model


def make_main_model(sub_model, time_steps):
    inp = Input(shape=(time_steps, INPUT_WIDTH,))
    out = TimeDistributed(sub_model)(inp)
    model = Model(inp, out)
    return model

# test with a simple layer
main_model_with_layer = make_main_model(Dense(INPUT_WIDTH), time_steps=5)

# test with a nested model
sub_model = make_sub_model()
main_model_with_nested_model = make_main_model(sub_model, time_steps=5)
```

The error:
```
python plaid_test.py
INFO:plaidml:Opening device "tahiti.1"
Traceback (most recent call last):
  File "plaid_test.py", line 31, in <module>
    main_model_with_nested_model = make_main_model(sub_model, time_steps=5)
  File "plaid_test.py", line 22, in make_main_model
    out = TimeDistributed(sub_model)(inp)
  File "/home/kpot/pyves/plaidml-venv/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/kpot/pyves/plaidml-venv/lib/python3.6/site-packages/keras/layers/wrappers.py", line 211, in call
    y = self.layer.call(inputs, **kwargs)
  File "/home/kpot/pyves/plaidml-venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/kpot/pyves/plaidml-venv/lib/python3.6/site-packages/keras/engine/topology.py", line 2273, in run_internal_graph
    uses_learning_phase = computed_tensors[0]._uses_learning_phase
AttributeError: 'Value' object has no attribute '_uses_learning_phase'
```

My versions:
Python: 3.6.4
PlaidML: plaidml==0.3.1, plaidml-keras==0.3.1
Keras: I tested both recommended 2.0.8 and latest 2.1.5, it fails on any of them

**Comment by tzerrell** [comment]
Thanks for the report, we're looking into this!

**Comment by SAMJAYHK** [comment]
Hi there, I got the same issue when using TimeDistributed. Did you have any solution to fix this? Thanks.

**Comment by GuNovello** [comment]
Hello people! I have this problem too. I need to use an rnn after a cnn, and apparently the only way is using TimeDistributed. Does anyone know a workaround? thanks. 

PlaidML: plaidml==0.6.0, plaidml-keras==0.6.0

**Comment by barloccia** [comment]
Any updating?
