### ISSUE TITLE
AttributeError: module 'plaidml.keras.backend' has no attribute 'eager'

### ISSUE THREAD

**Issue by chiboreache** [plaidml/plaidml#1083]
ArchLinux 5.6.13-arch1-1

tensorflow 2.2.0-1
python-plaidml 0.7.0-1
python-plaidml-keras 0.7.0-1

```python
import plaidml.keras

import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

plaidml.keras.install_backend()
```

____

```sh
Traceback (most recent call last):
  File "/home/chibo/ML/tst.py", line 8, in <module>
    plaidml.keras.install_backend()
  File "/usr/lib/python3.8/site-packages/plaidml/keras/__init__.py", line 68, in install_backend
    from keras.utils import conv_utils
  File "/usr/lib/python3.8/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/lib/python3.8/site-packages/keras/utils/__init__.py", line 26, in <module>
    from .vis_utils import model_to_dot
  File "/usr/lib/python3.8/site-packages/keras/utils/vis_utils.py", line 7, in <module>
    from ..models import Model
  File "/usr/lib/python3.8/site-packages/keras/models.py", line 10, in <module>
    from .engine.input_layer import Input
  File "/usr/lib/python3.8/site-packages/keras/engine/__init__.py", line 3, in <module>
    from .input_layer import Input
  File "/usr/lib/python3.8/site-packages/keras/engine/input_layer.py", line 7, in <module>
    from .base_layer import Layer
  File "/usr/lib/python3.8/site-packages/keras/engine/base_layer.py", line 12, in <module>
    from .. import initializers
  File "/usr/lib/python3.8/site-packages/keras/initializers.py", line 281, in <module>
    class Identity(Initializer):
  File "/usr/lib/python3.8/site-packages/keras/initializers.py", line 295, in Identity
    @K.eager
AttributeError: module 'plaidml.keras.backend' has no attribute 'eager'
```

**Comment by ssghost** [comment]
I have the same problem. Mac OS X

**Comment by literalgoblin** [comment]
Same issue, Mac OS Big Sur.... Any luck since the original issue was submitted?
