### ISSUE TITLE
Keras : model.fit_generator giving plaidml.exceptions.Unknown: Datatype for index input to gather must be INT32

### ISSUE THREAD

**Issue by Athul8raj** [plaidml/plaidml#1092]
OS : Windows 64bit
Python: 3.7
Plaidml-keras : 0.7.0
keras : 2.2.4

**Stack Trace**
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "llvm_cpu.0"
Epoch 1/100
Traceback (most recent call last):
  File "ssd_train.py", line 55, in <module>
    initial_epoch=initial_epoch)
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\plaidml\keras\backend.py", line 183, in __call__
    for name in self._output_names
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\plaidml\keras\backend.py", line 183, in <listcomp>
    for name in self._output_names
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\plaidml\__init__.py", line 1462, in get_output_shape
    return _Shape(self._ctx, _lib().plaidml_alloc_invoker_output_shape(self, name.encode()))
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\plaidml\__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "D:\Practice\Practice\Upwork\Keras Mobilenet\MobileNetV3\ssd\plaidml-venv\lib\site-packages\plaidml\library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Datatype for index input to gather must be INT32

**Code**
import os
import time
os.environ['KERAS_BACKEND'] = 'plaidml.keras.backend'
#os.environ['KERAS_BACKEND'] = 'theano'
import keras
from ssd_model import SSD300
from ssd_utils import PriorUtil
from ssd_data import InputGenerator
from ssd_training import SSDLoss
from utils.training import  Logger
from data_wf import GTUtility
import keras.backend as K
import numpy as np

gt_util = GTUtility('./WIDER_train/WIDER_train/')
gt_util_train, gt_util_val = gt_util.split(0.8)
experiment = 'ssd300_wf'

model = SSD300(num_classes=gt_util.num_classes)

prior_util = PriorUtil(model)

initial_epoch = 0
epochs = 100
batch_size = 2

gen_train = InputGenerator(gt_util_train, prior_util, batch_size, model.image_size, augmentation=True)
gen_val = InputGenerator(gt_util_val, prior_util, batch_size, model.image_size, augmentation=True)

checkdir = './checkpoints/' + time.strftime('%Y%m%d%H%M') + '_' + experiment
if not os.path.exists(checkdir):
    os.makedirs(checkdir)

optim = keras.optimizers.Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

loss = SSDLoss(alpha=1.0, neg_pos_ratio=3.0)

model.compile(optimizer=optim, loss=loss.compute, metrics=loss.metrics)

#model.summary()       
history = model.fit_generator(
        gen_train.generate(), 
        steps_per_epoch=gen_train.num_batches,
        epochs=epochs, 
        callbacks=[
            keras.callbacks.ModelCheckpoint(checkdir+'/weights.{epoch:03d}.h5', verbose=1, save_weights_only=True),
            Logger(checkdir),
        ], 
        validation_data=gen_val.generate(), 
        validation_steps=gen_val.num_batches,
        verbose=1,
        workers=1, 
        #use_multiprocessing=False, 
        initial_epoch=initial_epoch)

**Comment by Athul8raj** [comment]
@dgkutnic Can you guys look into this issue

**Comment by bgbutler** [comment]
I have a similar issue:  Mac OS X 10.15.4, plaidML 0.7.0, Keras 2.2.5, Keras-preprocessing 1.1.0, tensorflow 2.2.0.  It works for every other CNN with this system setup, but with an image generator, it throws an error.

Complete Code for Model

```
import plaidml.keras
plaidml.keras.install_backend()
from keras import backend as K

import pandas as pd
import numpy as np
import seaborn as sns

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

from matplotlib.image import imread
%matplotlib inline


# will need to crop or pad other images
image_shape = (140 ,140, 3)

image_gen = ImageDataGenerator(rotation_range=20,
                              width_shift_range=0.1,
                              height_shift_range=0.1,
                              shear_range=0.1,
                              zoom_range=0.1,
                              horizontal_flip=True,
                              fill_mode='nearest')

model = Sequential()

model.add(Conv2D(filters=32, kernel_size=(3,3),input_shape=image_shape, activation='relu',))
model.add(MaxPool2D(pool_size=(2, 2)))

model.add(Conv2D(filters=64, kernel_size=(3,3),input_shape=image_shape, activation='relu',))
model.add(MaxPool2D(pool_size=(2, 2)))

model.add(Conv2D(filters=64, kernel_size=(3,3),input_shape=image_shape, activation='relu',))
model.add(MaxPool2D(pool_size=(2, 2)))

model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

early_stopping = EarlyStopping(monitor='val_loss', patience=2)

batch_size=16

train_image_gen = image_gen.flow_from_directory(train_path,
                                               target_size = image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='binary')

# don't shuffle test data
test_image_gen = image_gen.flow_from_directory(test_path,
                                               target_size = image_shape[:2],
                                               color_mode='rgb',
                                               batch_size=batch_size,
                                               class_mode='binary',
                                               shuffle=False)

results = model.fit_generator(train_image_gen, epochs=20,
                             validation_data=test_image_gen,
                             callbacks=[early_stopping])


```


The notebook works well up until the model.fit_generator and throws an attribute error.



![Screen Shot 2020-07-21 at 20 37 09](https://user-images.githubusercontent.com/7228375/88238886-e6367500-cc50-11ea-845b-28fd2f30ad82.png)


![Screen Shot 2020-07-22 at 09 24 49](https://user-images.githubusercontent.com/7228375/88238913-f77f8180-cc50-11ea-951b-30dfab5c0933.png)
