### ISSUE TITLE
run sample  error 

### ISSUE THREAD

**Issue by vockalimo** [plaidml/plaidml#1095]
machine : macbook pro 2019

Version 
python=3.6.3
Keras==2.3.1
plaidml==0.7.0
plaidml-keras==0.7.0

Error : 
```

Using plaidml.keras.backend backend.
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    import keras
  File "/usr/local/var/pyenv/versions/env363/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/var/pyenv/versions/env363/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/usr/local/var/pyenv/versions/env363/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/usr/local/var/pyenv/versions/env363/lib/python3.6/site-packages/keras/backend/__init__.py", line 15, in <module>
    from .load_backend import is_variable
ImportError: cannot import name 'is_variable'
```

Can someone give me tips to fix this issue ?
thank

Code 
```
#!/usr/bin/env python

import numpy as np
import os
import time

os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

import keras
import keras.applications as kapp
from keras.datasets import cifar10

(x_train, y_train_cats), (x_test, y_test_cats) = cifar10.load_data()
batch_size = 8
x_train = x_train[:batch_size]
x_train = np.repeat(np.repeat(x_train, 7, axis=1), 7, axis=2)
model = kapp.VGG19()
model.compile(optimizer='sgd', loss='categorical_crossentropy',
              metrics=['accuracy'])

print("Running initial batch (compiling tile program)")
y = model.predict(x=x_train, batch_size=batch_size)

# Now start the clock and run 10 batches
print("Timing inference...")
start = time.time()
for i in range(10):
    y = model.predict(x=x_train, batch_size=batch_size)
print("Ran in {} seconds".format(time.time() - start))
```

**Comment by chiboreache** [comment]
same error during test from main page

`ImportError: cannot import name 'is_variable' from 'keras.backend.load_backend' (/usr/lib/python3.8/site-packages/keras/backend/load_backend.py)`

OS: Arch Linux
Kernel: x86_64 Linux 5.6.15-arch1-1
GPU: [AMD/ATI] Navi10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
Python 3.8.3
python-keras 2.3.1-1 
python-plaidml 0.7.0-1
python-plaidml-keras 0.7.0-1

**Comment by vockalimo** [comment]
hmm i rebuild env 
It's work for me 
change log 
use virtualenv replace pyenv 
follow the run book

**Comment by chiboreache** [comment]
> hmm i rebuild env
> It's work for me
> change log
> use virtualenv replace pyenv
> follow the run book

but i don't use any kind of virtual envirment..

**Comment by chiboreache** [comment]
# about 30 times faster in venv
meh...

still do not want to work in venv..
