### ISSUE TITLE
How to use tf.keras.losses.BinaryCrossentropy() in PlaidML?

### ISSUE THREAD

**Issue by cdaein** [plaidml/plaidml#1430]
I am following a code example from https://keras.io website, where they use
```python
from tensorflow import keras
tf.keras.losses.BinaryCrossentropy(from_logits=True)
```

With PlaidML, I was trying to change it to:
```python
import keras
keras.losses.BinaryCrossentropy(from_logits=True)
```

this give me an error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-47-ddb75c662319> in <module>
      1 import keras
----> 2 keras.losses.BinaryCrossentropy(from_logits=True)

AttributeError: module 'keras.losses' has no attribute 'BinaryCrossentropy'
```

Is there something I can do to use the function above?

**Comment by rescuehero** [comment]
You need to setup your plaidml backend, like:
´´´python
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
import keras
´´´
it should return
´´´
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "privacy"
´´´

**Comment by cdaein** [comment]
My apologies for not including the full code. I was just trying to keep it short.
I did setup the plaidml backend, and I am having the same problem, so it's not because of that.

The following code returns the same error message as my original post:
```python
import os
os.environ['KERAS_BACKEND'] = 'plaidml.keras.backend'

import keras
keras.losses.BinaryCrossentropy(from_logits=True)
```

**Comment by IIIBlueberry** [comment]
IIRC Keras 2.2.4 loss is not a class, it's a function instead

`import keras
loss = keras.losses.binary_crossentropy(y_true, y_pred)`
this should fix your issues

**Comment by FuhrerStein** [comment]
I had the same problem adapting a [tutorial from keras website about a toy ResNet Model](https://keras.io/guides/functional_api/#a-toy-resnet-model). There, you complile a model with a loss function that has arguments:

```
model.compile(
    optimizer=keras.optimizers.RMSprop(1e-3),
    loss=keras.losses.CategoricalCrossentropy(from_logits=True),
    metrics=["acc"],
)
```

Problem is in line `loss=keras.losses.CategoricalCrossentropy(from_logits=True)`.
I tried changing it to `loss=keras.backend.categorical_crossentropy(from_logits=True)`, but it does not work that way:

```
Traceback (most recent call last):
  File "D:/Projects/Python/NeuralNetLearn/ResNet.py", line 57, in <module>
    loss=keras.backend.categorical_crossentropy(from_logits=True),
  File "D:\Projects\Python\NeuralNetLearn\venv\lib\site-packages\plaidml\tile.py", line 257, in function
    operation = cls(*args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'target' and 'output'
```

It does compile if you omit `(from_logits=True)` part, but that way accuracy never goes over 10%, so model simply does not work.

What I ended up doing is writing my own wrapper function and passing it to the model:
```
def categorical_crossentropy_from_logits(y_true, y_pred):
    return keras.backend.categorical_crossentropy(y_true, y_pred, from_logits=True)


model.compile(
    optimizer=keras.optimizers.RMSprop(1e-3),
    loss=categorical_crossentropy_from_logits,
    metrics=["accuracy"],
)
```

That seems to work fine.
Of course, I omit the rest of the code for brevity.
