### ISSUE TITLE
NotImplementedError: The PlaidML backend for Keras does not support changing tensor shapes with set_value.

### ISSUE THREAD

**Issue by borderlineinteractive** [plaidml/plaidml#145]
Hi, I got the following error message using the Image Segmentation Keras repository:

https://github.com/divamgupta/image-segmentation-keras

The repository was originally written for the Theano backend, but I did not see any Theano specific code. Nevertheless I receive the following error regardless, which segmentation model I use (Unet, Segnet or FCN):

python  train.py --save_weights_path=weights/ex1 --train_images="data/dataset1/images_prepped_train/"  --train_annotations="data/dataset1/annotations_prepped_train/"  --val_images="data/dataset1/images_prepped_test/"  --val_annotations="data/dataset1/annotations_prepped_test/"  --n_classes=10 --input_height=320 --input_width=640 --model_name="vgg_segnet" 
INFO:plaidml:Opening device "metal_amd_radeon_pro_580.0"
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    m = modelFN( n_classes , input_height=input_height, input_width=input_width   )
  File "/Users/user/plaidml/imageseg/Models/VGGSegnet.py", line 56, in VGGSegnet
    vgg.load_weights(VGG_Weights_path)
  File "/Users/user/plaidml-venv/lib/python2.7/site-packages/keras/engine/topology.py", line 2619, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/Users/user/plaidml-venv/lib/python2.7/site-packages/keras/engine/topology.py", line 3095, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/Users/user/plaidml-venv/lib/python2.7/site-packages/plaidml/keras/backend.py", line 275, in batch_set_value
    set_value(pair[0], pair[1])
  File "/Users/user/plaidml-venv/lib/python2.7/site-packages/plaidml/keras/backend.py", line 1516, in set_value
    + 'existing.shape = ' + str(x.shape) + ', value.shape = ' + str(value.shape))
NotImplementedError: The PlaidML backend for Keras does not support changing tensor shapes with set_value.
existing.shape = Shape(dtype=<DType.FLOAT32: 50>, dims=(102400L, 4096L)), value.shape = (25088, 4096)

It appears that the required functionality is not implemented. Does anybody have further insight into this?

Thanks a lot!

**Comment by torokati44** [comment]
I just got a similar error on my laptop, while running the same code that worked fine on my desktop before.
So out of gut feeling (and because I installed Keras on my laptop much earlier than on my desktop), I upgraded the `keras` package to its latest available version using `pip3`.
That solved it for me. Maybe it will help you too.
The command I used was `pip3 install --user --upgrade keras`, but this might be a bit different for you, especially if you use `virtualenv`, or similar.
