### ISSUE TITLE
ValueError: could not broadcast input array 

### ISSUE THREAD

**Issue by reynierhdez** [plaidml/plaidml#146]
Hi! I'm using a R7 M260 card.

I got the following error when running the Hello VGG:

INFO:plaidml:Opening device "opencl_amd_iceland.0"
Traceback (most recent call last):
  File ".\hellovgg.py", line 17, in <module>
    model = kapp.VGG19()
  File "C:\Python37\lib\site-packages\keras\applications\vgg19.py", line 112, in VGG19
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv1')(img_input)
  File "C:\Python37\lib\site-packages\keras\engine\topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "C:\Python37\lib\site-packages\keras\layers\convolutional.py", line 134, in build
    constraint=self.kernel_constraint)
  File "C:\Python37\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\keras\engine\topology.py", line 396, in add_weight
    weight = K.variable(initializer(shape),
  File "C:\Python37\lib\site-packages\keras\initializers.py", line 212, in __call__
    dtype=dtype, seed=self.seed)
  File "C:\Python37\lib\site-packages\plaidml\keras\backend.py", line 1238, in random_uniform
    rng_state = _make_rng_state(seed)
  File "C:\Python37\lib\site-packages\plaidml\keras\backend.py", line 170, in _make_rng_state
    rng_state = variable(rng_init, dtype='uint32')
  File "C:\Python37\lib\site-packages\plaidml\keras\backend.py", line 1762, in variable
    view.copy_from_ndarray(value)
  File "C:\Python37\lib\site-packages\plaidml\__init__.py", line 1194, in copy_from_ndarray
    np.copyto(dst, src)
ValueError: could not broadcast input array from shape (3,2048) into shape (6144)

Thanks!!!

**Comment by reynierhdez** [comment]
I reinstalled the framework with `pip install -I plaidml-keras plaidbench` and worked OK!
