### ISSUE TITLE
Unsupport layer or Function in Keras 2.2.4 & PlaidML-0.7.0

### ISSUE THREAD

**Issue by shivSD** [plaidml/plaidml#1478]
**System info**
plaidml-keras-0.7.0
plaidml-0.7.0
MacOS 10.15.7

During the inference, getting following error
  _File "/Users/plaidml-venv/lib/python3.8/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/Users/plaidml-venv/lib/python3.8/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/plaidml-venv/lib/python3.8/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/plaidml-venv/lib/python3.8/site-packages/keras/layers/__init__.py", line 52, in deserialize
    return deserialize_keras_object(config,
  File "/Users/plaidml-venv/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 137, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name +
ValueError: Unknown layer: Functional_ 

I get this error with 2.2.4 version of Keras and Plaidml - 0.7.0. If I install 2.4.0 Keras and tensorflow this weight/model file gets loaded without any issue. 

Looks like 2.2.4 doesn't support some layers.

Is there any workaround to change the Keras version to 2.4.0 in PlaidML ?

**Comment by cdgriffith** [comment]
I am also curious if there will be an update to latest Keras in the near future  (now that it's a year later after this report.) 

Two other near duplicate issues: 
https://github.com/plaidml/plaidml/issues/1489
https://github.com/plaidml/plaidml/issues/1725

Posting all here as this is oldest one I found.  Current version of Keras is 2.7.0 and a lot of tutorials have functions and features 2.2.4 does not support. Sadly cannot just update to latest either as the `install_backend` monkey-patch then breaks: 

```
Traceback (most recent call last):
  File "image_classifier/ml_classification.py", line 10, in <module>
    plaidml.keras.install_backend()
  File "image_classifier/venv/lib/python3.8/site-packages/plaidml/keras/__init__.py", line 68, in install_backend
    from keras.utils import conv_utils
  File "image_classifier/venv/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "image_classifier/venv/lib/python3.8/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "image_classifier/venv/lib/python3.8/site-packages/plaidml/keras/__init__.py", line 95, in load_module
    self._add_imports(mod, self._backend_modname)
  File "image_classifier/venv/lib/python3.8/site-packages/plaidml/keras/__init__.py", line 105, in _add_imports
    impl = importlib.import_module(import_modname, __name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "image_classifier/venv/lib/python3.8/site-packages/plaidml/keras/backend.py", line 44, in <module>
    from keras.backend.common import cast_to_floatx
ModuleNotFoundError: No module named 'keras.backend.common'
```
