### ISSUE TITLE
AttributeError: 'module' object has no attribute 'convert_np_dtype_to_pml'

### ISSUE THREAD

**Issue by jack-willturner** [plaidml/plaidml#148]
After installation, when running:

` $ plaidbench --print-stacktraces keras mobilenet `

```
Running 1024 examples with mobilenet, batch size 1
'module' object has no attribute 'convert_np_dtype_to_pml'
Set --print-stacktraces to see the entire traceback
Traceback (most recent call last):
  File "/home/odroid/jack/plaidml/bin/plaidbench", line 11, in <module>
    sys.exit(plaidbench())
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/plaidbench/frontend_keras.py", line 228, in cli
    return runner.run(frontend, networks)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/plaidbench/core.py", line 248, in run
    model.setup()
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/plaidbench/frontend_keras.py", line 93, in setup
    self.model = mod['build_model'](**build_model_kwargs)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/plaidbench/networks/keras/mobilenet.py", line 30, in build_model
    model = kapp.mobilenet.MobileNet()
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/keras/applications/mobilenet.py", line 442, in MobileNet
    img_input = Input(shape=input_shape)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1436, in Input
    input_tensor=tensor)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1347, in __init__
    name=self.name)
  File "/home/odroid/jack/plaidml/local/lib/python2.7/site-packages/plaidml/keras/backend.py", line 1037, in placeholder
    dtype = ptile.convert_np_dtype_to_pml(dtype or floatx())
AttributeError: 'module' object has no attribute 'convert_np_dtype_to_pml'
```

`pip` version is `10.0.1`
`keras` version is `2.0.8`

**Comment by tzerrell** [comment]
This looks like an error I'd expect if you had mismatched versions of `plaidml` and `plaidml-keras`. Can you check if these have different version numbers?

**Comment by tzerrell** [comment]
Closing this as stale, but if you have both `plaidml` and `plaidml-keras` at our latest release (0.3.5) and the problem persists, please reopen.
