### ISSUE TITLE
plaidml-setup fails with '[Errno 9: Bad file descriptor]' on CPython 3.6.6

### ISSUE THREAD

**Issue by paulie-g** [plaidml/plaidml#152]
Followed install instructions in README.md, tried terminator/konsole/actual console, same issue. Can *not* reproduce it in the REPL.

GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
Arch x64 up-to-date

`PlaidML Setup (0.3.4)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the GNU AGPLv3
 
Default Config Devices:
   opencl_amd_ellesmere.1 : Advanced Micro Devices, Inc. Ellesmere (OpenCL)
   opencl_amd_ellesmere.0 : Advanced Micro Devices, Inc. Ellesmere (OpenCL)

Experimental Config Devices:
   llvm_cpu.0 : CPU (LLVM)
   opencl_amd_pitcairn.0 : Advanced Micro Devices, Inc. Pitcairn (OpenCL)
   opencl_amd_ellesmere.1 : Advanced Micro Devices, Inc. Ellesmere (OpenCL)
   opencl_amd_ellesmere.0 : Advanced Micro Devices, Inc. Ellesmere (OpenCL)
   opencl_cpu.0 : Intel(R) Corporation CPU (OpenCL)

Using experimental devices can cause poor performance, crashes, and other nastiness.

Enable experimental device support? (y,n)[n]:Traceback (most recent call last):
  File "/home/paul/dev/tmp/plaidml/bin/plaidml-setup", line 11, in <module>
    sys.exit(main())
  File "/home/paul/dev/tmp/plaidml/lib/python3.6/site-packages/plaidml/plaidml_setup.py", line 75, in main
    exp = choice_prompt("Enable experimental device support", ["y", "n"], "n")
  File "/home/paul/dev/tmp/plaidml/lib/python3.6/site-packages/plaidml/plaidml_setup.py", line 21, in choice_prompt
    inp = input("{0}? ({1})[{2}]:".format(question, ",".join(choices), default))
OSError: [Errno 9] Bad file descriptor
`

**Comment by paulie-g** [comment]
Something somewhere must be closing stdin (or, less likely, stdout), but it beats me how that happens. Readline is from the virtualenv, so presumably that isn't the problem.

**Comment by tzerrell** [comment]
Does this problem persist and manifest in the same way in PlaidML 0.3.5?
