### ISSUE TITLE
Mainly a docs question: Want to know what to expect if some test fail, but some pass

### ISSUE THREAD

**Issue by StuAtGit** [plaidml/plaidml#1557]
Hello!
I got plaidml setup with some help from `PLAIDML_VERBOSE`:
https://github.com/plaidml/plaidml/issues/1302#issuecomment-726497962

However, I noticed one plaidbench run reported failure, but others worked:

So far:

Failed:
  - mobilenet

Passed:
  - mobilenet_v2
  - inception_v3

Just wondering what to make of this - can I expect it to work, in general?

**Comment by StuAtGit** [comment]
Follow up: interestingly enough, logging through the log messages, the vgg19 test, which reliably causes the computer to shut down fairly quickly, seems to be causing the GPU to reliably overheat. :thinking: 

Given the range of other GPU intensive tasks I've run, that did not cause a shutdown, it's interesting this particular test pretty much immediately causes it to overheat.

**Comment by StuAtGit** [comment]
Another update: I re-ran the tests with: `export PLAIDML_USE_STRIPE=1` enabled

The following tests:
- densenet121
- densenet169
- densenet201
All failed with a similar error, along the lines of:

```
plaidbench --print-stacktraces keras densenet201
Running 1024 examples with densenet201, batch size 1, on backend plaid
INFO:plaidml:Opening device "opencl_amd_gfx1010.0"
Model loaded, folding in batch_norm
Can only fold BN to Conv2d right now, got: MaxPooling2D 7
Set --print-stacktraces to see the entire traceback
Traceback (most recent call last):
  File "/home/stu/.local/bin/plaidbench", line 8, in <module>
    sys.exit(plaidbench())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/stu/.local/lib/python3.8/site-packages/plaidbench/frontend_keras.py", line 412, in cli
    return runner.run(frontend, backend, networks)
  File "/home/stu/.local/lib/python3.8/site-packages/plaidbench/core.py", line 410, in run
    _inner_run(
  File "/home/stu/.local/lib/python3.8/site-packages/plaidbench/core.py", line 256, in _inner_run
    model.setup()
  File "/home/stu/.local/lib/python3.8/site-packages/plaidbench/frontend_keras.py", line 203, in setup
    self.model = self.fold_batch_norm(self.model)
  File "/home/stu/.local/lib/python3.8/site-packages/plaidbench/frontend_keras.py", line 141, in fold_batch_norm
    raise Exception("Can only fold BN to Conv2d right now, got: " +
Exception: Can only fold BN to Conv2d right now, got: MaxPooling2D 7
```

Still failed:
```
-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS          
-----------------------------------------------------------------------------------------
mobilenet            94.96 ms                  92.26 ms / 10.84 fps
Correctness: FAIL, max_error: 8.913599967956543, max_abs_error: 0.2467142641544342, fail_ratio: 0.854
```

Switched from failed to pass!

```
-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS          
-----------------------------------------------------------------------------------------
resnet50             8.12 ms                   5.85 ms / 171.00 fps
Correctness: PASS, max_error: 9.301000318373553e-06, max_abs_error: 7.748603820800781e-07, fail_ratio: 0.0
```
