### ISSUE TITLE
facing noise_shape error while using spatial_dropout

### ISSUE THREAD

**Issue by upasana-mittal** [plaidml/plaidml#165]
I am facing error on `SpatialDropout1D`. The error I am facing is given below.

 ```
raise PlaidMLKerasException('Unimplemented noise shape in dropout')
 plaidml.keras.backend.PlaidMLKerasException: Unimplemented noise shape in dropout
```

**Comment by Payback80** [comment]
i'm facing the same problem too, any workaround?

**Comment by SleepProgger** [comment]
Same error here with SpatialDropout2D

```
from keras.layers.core import SpatialDropout2D
from keras.layers.convolutional import Conv2D
from keras.engine.input_layer import Input
x = Input((5,5,3))
x = Conv2D(5, 3)(x)
x = SpatialDropout2D(0.25)(x)
```

->

```
Traceback (most recent call last):
  File "/run/media/nope/data/home/nope/workspace/test/keras_spatial_dropout.py", line 12, in <module>
    x = SpatialDropout2D(0.25)(x)
  File "/home/nope/.local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/nope/.local/lib/python3.7/site-packages/keras/layers/core.py", line 126, in call
    training=training)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 753, in in_train_phase
    cx = x()
  File "/home/nope/.local/lib/python3.7/site-packages/keras/layers/core.py", line 124, in dropped_inputs
    seed=self.seed)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 588, in dropout
    raise PlaidMLKerasException('Unimplemented noise shape in dropout')
plaidml.keras.backend.PlaidMLKerasException: Unimplemented noise shape in dropout
```

Could that layer be supported pretty please ?

**Comment by dgkutnic** [comment]
Issues in the `needs info` state for 7+ days will be marked as obsolete and closed. If the issue is still occurring for you, please re-open the issue and provide us with the requested info.

**Comment by SleepProgger** [comment]
Should be fixed in https://github.com/plaidml/plaidml/pull/305 anyway
