### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by Allen83219** [plaidml/plaidml#1652]
I installed plaidml-keras, punched in plaidml-setup, then I got the following:
'''
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\plaidml-setup.exe\__main__.py", line 7, in <module>
  File "C:\Users\10340\AppData\Roaming\Python\Python38\site-packages\plaidml\plaidml_setup.py", line 72, in main
    devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
  File "C:\Users\10340\AppData\Roaming\Python\Python38\site-packages\plaidml\__init__.py", line 1076, in devices
    enumerator = _Enumerator(ctx)
  File "C:\Users\10340\AppData\Roaming\Python\Python38\site-packages\plaidml\__init__.py", line 1033, in __init__
    self._as_parameter_ = _lib().plaidml_alloc_device_enumerator(
OSError: exception: access violation reading 0x0000000000000000
'''
And no, I didn't modify it (though I was tempted to do so.)

**Comment by Allen83219** [comment]
System: Windows 10
CPU: Ryzen 9 4900H
GPU: 1660Ti

**Comment by Allen83219** [comment]
installation commands as below:
[req.txt](https://github.com/plaidml/plaidml/files/5756161/req.txt)
`pip install --upgrade --force-reinstall tf-nightly
pip install --upgrade --force-reinstall -r req.txt
pip install --upgrade --force-reinstall numpy==1.19.2
plaidml-setup
`

**Comment by antonpolishko** [comment]
I've got the same issue.

System: Windows 10 Insider preview build 21292
CPU: i5-9600k
GPU: 2080ti, driver v265.21


vcredist2015 was installed using `scoop`, not  `choco`

python 3.8 from conda, dedicated conda environment and installation according to the guide. Output of `pip freeze`

```
certifi==2020.12.5
cffi==1.14.4
click==7.1.2
colorama==0.4.4
enum34==1.1.10
h5py==3.1.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
numpy==1.19.5
plaidbench==0.7.0
plaidml==0.7.0
plaidml-keras==0.7.0
pycparser==2.20
PyYAML==5.4.1
scipy==1.6.0
six==1.15.0
wincertstore==0.2
```

Error for `plaidml-setup`
```
Traceback (most recent call last):
  File "c:\users\anton\anaconda3\envs\plaidml\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\anton\anaconda3\envs\plaidml\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anton\anaconda3\envs\plaidml\Scripts\plaidml-setup.exe\__main__.py", line 7, in <module>
  File "c:\users\anton\anaconda3\envs\plaidml\lib\site-packages\plaidml\plaidml_setup.py", line 72, in main
    devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
  File "c:\users\anton\anaconda3\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 1076, in devices
    enumerator = _Enumerator(ctx)
  File "c:\users\anton\anaconda3\envs\plaidml\lib\site-packages\plaidml\__init__.py", line 1033, in __init__
    self._as_parameter_ = _lib().plaidml_alloc_device_enumerator(
OSError: exception: access violation reading 0x0000000000000000
```

**Comment by abilashcgit** [comment]
I am facing a similar access violation issue when trying to profile PlaidML benchmark using Nsight VSE with OpenCL trace settings.
Any known solution to the same?

<<output from pip freeze>>
 pip freeze
cached-property==1.5.2
cffi==1.14.6
click==8.0.1
colorama==0.4.4
enum34==1.1.10
h5py==2.10.0
importlib-metadata==4.8.1
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
numpy==1.19.5
plaidbench==0.7.0
plaidml==0.7.0
plaidml-keras==0.7.0
pycparser==2.20
PyYAML==5.4.1
scipy==1.5.4
six==1.16.0
typing-extensions==3.10.0.2
zipp==3.5.0
