### ISSUE TITLE
PowerShell returning 'The term 'plaidml-setup' is not recognized'

### ISSUE THREAD

**Issue by R470R** [plaidml/plaidml#1731]
Hello, first of all thanks a lot for this incredible package.
It seems my only option for my sweet 6900XT.

After installing latest version of openCL in my windows 10 normal environment I installed python , chocolatey etc (without anaconda)

Then installing plaidml I get the following response from powershell :

```
pip install -U plaidml-keras
Requirement already up-to-date: plaidml-keras in c:\python38\lib\site-packages (0.7.0)
Requirement already satisfied, skipping upgrade: plaidml in c:\python38\lib\site-packages (from plaidml-keras) (0.7.0) Requirement already satisfied, skipping upgrade: keras==2.2.4 in c:\python38\lib\site-packages (from plaidml-keras) (2.2.4) Requirement already satisfied, skipping upgrade: six in c:\python38\lib\site-packages (from plaidml-keras) (1.15.0) Requirement already satisfied, skipping upgrade: enum34>=1.1.6 in c:\python38\lib\site-packages (from plaidml->plaidml-keras) (1.1.10) Requirement already satisfied, skipping upgrade: numpy in c:\python38\lib\site-packages (from plaidml->plaidml-keras) (1.20.1) Requirement already satisfied, skipping upgrade: cffi in c:\python38\lib\site-packages (from plaidml->plaidml-keras) (1.14.5) Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in c:\python38\lib\site-packages (from keras==2.2.4->plaidml-keras) (1.0.8) Requirement already satisfied, skipping upgrade: scipy>=0.14 in c:\python38\lib\site-packages (from keras==2.2.4->plaidml-keras) (1.6.1) Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in c:\python38\lib\site-packages (from keras==2.2.4->plaidml-keras) (1.1.2) Requirement already satisfied, skipping upgrade: pyyaml in c:\python38\lib\site-packages (from keras==2.2.4->plaidml-keras) (5.4.1) Requirement already satisfied, skipping upgrade: h5py in c:\python38\lib\site-packages (from keras==2.2.4->plaidml-keras) (3.2.1) Requirement already satisfied, skipping upgrade: pycparser in c:\python38\lib\site-packages (from cffi->plaidml->plaidml-keras) (2.20) WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available. You should consider upgrading via the 'c:\python38\python.exe -m pip install --upgrade pip' command.

```
Then with

`plaidml-setup`
i get

```
plaidml-setup : The term 'plaidml-setup' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ plaidml-setup
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (plaidml-setup:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
and with

plaidbench keras mobilenet
i get the same

    plaidbench : The term 'plaidbench' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ plaidbench keras mobilenet
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (plaidbench:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
already tried uninstall and reinstall , same thing happens
```

Does someone has a good hint ? I'm trying this on amd 6900xt

Best regards

**Comment by vgrimault-fr** [comment]
Hello,
I had got the same problem as you. To solve this problem, you need to find the plaidml_setup.py, and run it manually.

`PS C:\Python38\Lib\site-packages\plaidml> ./plaidml_setup.py`

I hope it will solve your problems.

**Comment by R470R** [comment]
It solved, thanks a lot Mr vgrimault-fr !!!

**Comment by aquilaadrian** [comment]
Hey vgrimault-fr, 
 i tried to run it as you suggest python plaidml_setup.py
> Hello,
> I had got the same problem as you. To solve this problem, you need to find the plaidml_setup.py, and run it manually.
> 
> `PS C:\Python38\Lib\site-packages\plaidml> ./plaidml_setup.py`
> 
> I hope it will solve your problems.


however i got an error 
`Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\plaidml\plaidml_setup.py", line 10, in <module>
    import plaidml
  File "C:\Python39\lib\site-packages\plaidml\__init__.py", line 50, in <module>
    import plaidml.settings
  File "C:\Python39\lib\site-packages\plaidml\settings.py", line 33, in <module>
    _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
  File "C:\Python39\lib\site-packages\plaidml\settings.py", line 29, in _setup_config
    raise plaidml.exceptions.PlaidMLError(
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".`

i am not sure where can i find this experimental.json ? i take a look at [https://github.com/plaidml/plaidml/issues/370](url) however i am still don't understand how he can solve it
any idea how to solve this?

**Comment by vgrimault-fr** [comment]
Hey aquilaadrian,

I think that you are using Python 3.9. For me, Python 3.9 doesn't work with PlaidML.
When I was trying to use PlaidML, I've got error, and I can't use my GPU if I wasn't using Python 3.8, PlaidML 0.6.0, and hp5y 2.10.0.
I hope that it can solve your problems.

**Comment by aquilaadrian** [comment]
thanks @vgrimault-fr
