### ISSUE TITLE
plaidml-setup plaidml.dll location?

### ISSUE THREAD

**Issue by aquilaadrian** [plaidml/plaidml#1751]
Hey i tried to run plaidml-setup but the command is not detected on anaconda prompt or cmd prompt,

 i tried to run it manually by finding the plaidml_setup.py

however i am stuck at this:
`(plaidML) C:\Python39\Lib\site-packages\plaidml>python plaidml_setup.py
Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\plaidml\plaidml_setup.py", line 10, in <module>
    import plaidml
  File "C:\Python39\lib\site-packages\plaidml\__init__.py", line 50, in <module>
    import plaidml.settings
  File "C:\Python39\lib\site-packages\plaidml\settings.py", line 33, in <module>
    _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
  File "C:\Python39\lib\site-packages\plaidml\settings.py", line 29, in _setup_config
    raise plaidml.exceptions.PlaidMLError(
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".
`
i tried to windows search my whole C disk of eperimental.json file but got no result, how should i proceed?

[https://github.com/plaidml/plaidml/issues/370](url) i tried to look at this as well but no clear solution for me like explicitly mentioning where the experimental.json

**Comment by aquilaadrian** [comment]
I managed to add config.json and experimental.json from this github page, now the error is changed to 
`Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\plaidml\plaidml_setup.py", line 156, in <module>
    main()
  File "C:\Python39\Lib\site-packages\plaidml\plaidml_setup.py", line 16, in main
    ctx = plaidml.Context()
  File "C:\Python39\lib\site-packages\plaidml\__init__.py", line 892, in Context
    return plaidml.context.Context(_lib())
  File "C:\Python39\lib\site-packages\plaidml\__init__.py", line 789, in _lib
    _impl_lib = _Library()
  File "C:\Python39\lib\site-packages\plaidml\__init__.py", line 176, in __init__
    lib = load_library('plaidml.dll', ['Library', 'bin'])
  File "C:\Python39\lib\site-packages\plaidml\__init__.py", line 167, in load_library
    raise exceptions.PlaidMLError(
plaidml.exceptions.PlaidMLError: Could not find PlaidML library file: "plaidml.dll".`

where is plaidml.dll?

**Comment by aquilaadrian** [comment]
Solved, by re-installing anaconda, uninstall python, and delete Pythonfolder on roaming AppData
run normal plaidml-setup and voila it is installed

**Comment by hemangjoshi37a** [comment]
can anyone please send the missing experimental.json file any other needed files.
