### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'unique_object_name'

### ISSUE THREAD

**Issue by jkind9** [plaidml/plaidml#1798]
Trying to use the plaidml Keras backend has resulted in the following error:
 ```
PyCharmCE2020.3/scratches/scratch.py
2021-06-10 08:46:56.951912: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-10 08:46:56.952281: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Using plaidml.keras.backend backend.
Traceback (most recent call last):
  File "C:/Users/James.Alexander/AppData/Roaming/JetBrains/PyCharmCE2020.3/scratches/scratch.py", line 21, in <module>
    model = keras.models.Sequential()
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 109, in __init__
    super(functional.Functional, self).__init__(  # pylint: disable=bad-super-call
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\keras\engine\training.py", line 245, in __init__
    super(Model, self).__init__(**kwargs)
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 522, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 350, in __init__
    self._init_set_name(name)
  File "C:\Users\James.Alexander\Anaconda3\lib\site-packages\keras\engine\functional.py", line 501, in _init_set_name
    self._name = backend.unique_object_name(
AttributeError: module 'keras.backend' has no attribute 'unique_object_name'

Process finished with exit code 1
```
Im using the following version of tensorflow and Keras:
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
tensorflow==2.5.0
tensorflow-estimator==2.5.0

**Comment by fkiller** [comment]
PlaidML runs on tensorflow==1.14.0
Check [requirements.txt](https://github.com/plaidml/plaidml/blob/master/demos/TransferLearning/requirements.txt) in demo/TransferLearning
