### ISSUE TITLE
Facing PlaidML build issues on Windows 10

### ISSUE THREAD

**Issue by abilashcgit** [plaidml/plaidml#1895]
Facing the below Build issue when trying to Build PlaidML using Bazel. Unable to resolve the same. Could not get any pointers from https://plaidml.github.io/plaidml/docs/troubleshooting.html as well. Any pointers on this would help. Thanks

PS C:\plaidml> bazel build --config windows_x86_64 //plaidml:wheel
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=171
INFO: Options provided by the client:
  'build' options: --python_path=C:/ProgramData/Anaconda3/python.exe
INFO: Reading rc options for 'build' from c:\plaidml\bzl\bazel.rc:
  'build' options: -c opt --spawn_strategy=standalone --genrule_strategy=standalone --announce_rc --nolegacy_external_runfiles --distinct_host_configuration=false --enable_platform_specific_config --action_env=LC_ALL --action_env=LANG --action_env=NO_PROXY --action_env=HTTP_PROXY --action_env=HTTPS_PROXY --action_env=no_proxy --action_env=http_proxy --action_env=https_proxy --define=version=0.0.0.dev0
INFO: Found applicable config definition build:windows_x86_64 in file c:\plaidml\bzl\bazel.rc: --build_tag_filters=-darwin,-docs,-latex,-linux,-metal,-pytorch --action_env=CONDA_EXE --action_env=NUMBER_OF_PROCESSORS --action_env=PLAIDML_SETTINGS --cxxopt=/std:c++17 --cxxopt=/Zc:__cplusplus
INFO: Found applicable config definition build:windows in file c:\plaidml\bzl\bazel.rc: --build_tag_filters=-darwin,-docs,-latex,-linux,-metal,-pytorch --action_env=CONDA_EXE --action_env=NUMBER_OF_PROCESSORS --action_env=PLAIDML_SETTINGS --cxxopt=/std:c++17 --cxxopt=/Zc:__cplusplus
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
jsonschema-4.1.2     | 54 KB     | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['C:\\users\\sample\\_bazel_sample\\zmmwpgyj\\external\\com_intel_plaidml_conda_windows\\env\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\plaidml\\conda\\condaenv.cl1jgdxs.requirements.txt']
Pip subprocess output:
Collecting bokeh
  Using cached https://files.pythonhosted.org/packages/26/96/3e56636664e497728b14738fea5e54297de1bc0f451b7206325a6453e73d/bokeh-2.4.1-py3-none-any.whl
Collecting click
  Using cached https://files.pythonhosted.org/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl
Processing c:\users\sample\appdata\local\pip\cache\wheels\28\da\a5\bebf76a2c642f94ed4e1410fb99f7a04916216b13554e694c0\defaultlist-1.0.0-py2.py3-none-any.whl
Collecting graphviz
  Using cached https://files.pythonhosted.org/packages/97/14/b5eeeb6d24dbca0ada857ce4a453985df34d9512464bb20cc1a8aca44c54/graphviz-0.17-py3-none-any.whl
Collecting humanize
  Using cached https://files.pythonhosted.org/packages/fd/5e/9840102591431f86c2e99c5a8e4f18bb399f9f2e982b0dbba87c98ae800f/humanize-3.12.0-py3-none-any.whl
Collecting keras==2.2.4
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting keras-applications==1.0.8
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting networkx
  Using cached https://files.pythonhosted.org/packages/e9/93/aa6613aa70d6eb4868e667068b5a11feca9645498fd31b954b6c4bb82fa5/networkx-2.6.3-py3-none-any.whl
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/b8/42/977a30bfb4ce937b188e148fcfbae913a9aa6d22ea3d32fef603444eb588/pandas-1.3.4-cp37-cp37m-win_amd64.whl
Collecting pcpp==1.20.1
  Using cached https://files.pythonhosted.org/packages/33/7b/e8ca3707a86a21685214cbe8d7d77a71a2964dfef01c1fe9bbfad9ff6b39/pcpp-1.20.1-py2.py3-none-any.whl
Collecting tensorflow==1.15
  Using cached https://files.pythonhosted.org/packages/94/a9/7a9ff9b51a6acf5cf113e79e4cfd68a88045321cfc65802c16169dfcd041/tensorflow-1.15.0-cp37-cp37m-win_amd64.whl
Processing c:\users\sample\appdata\local\pip\cache\wheels\89\40\74\3a0b7d937890c66c4373120117ebf4ba99f4889b4a0a6a810c\theano-1.0.5-cp37-none-any.whl
Collecting h5py==2.10.0
  Using cached https://files.pythonhosted.org/packages/a1/6b/7f62017e3f0b32438dd90bdc1ff0b7b1448b6cb04a1ed84f37b6de95cd7b/h5py-2.10.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied, skipping upgrade: typing-extensions>=3.10.0 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (3.10.0.2)
Requirement already satisfied, skipping upgrade: Jinja2>=2.9 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (3.0.2)
Requirement already satisfied, skipping upgrade: PyYAML>=3.10 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (6.0)
Requirement already satisfied, skipping upgrade: tornado>=5.1 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (6.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11.3 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (1.21.2)
Requirement already satisfied, skipping upgrade: pillow>=7.1.0 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (8.3.2)
Requirement already satisfied, skipping upgrade: packaging>=16.8 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (21.0)
Requirement already satisfied, skipping upgrade: colorama; platform_system == "Windows" in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from click->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 2)) (0.4.4)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from click->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 2)) (4.8.1)
Requirement already satisfied, skipping upgrade: setuptools in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from humanize->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 5)) (58.2.0)
Collecting keras-preprocessing>=1.0.5
  Using cached https://files.pythonhosted.org/packages/79/4c/7c3275a01e12ef9368a892926ab932b33bb13d55794881e3573482b378a7/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: scipy>=0.14 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from keras==2.2.4->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 6)) (1.7.1)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from keras==2.2.4->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 6)) (1.16.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from pandas->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 9)) (2.8.2)
Collecting pytz>=2017.3
  Using cached https://files.pythonhosted.org/packages/d3/e3/d9f046b5d1c94a3aeab15f1f867aa414f8ee9d196fae6865f1d6a0ee1a0b/pytz-2021.3-py2.py3-none-any.whl
Collecting google-pasta>=0.1.6
  Using cached https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: wheel>=0.26 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from tensorflow==1.15->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 11)) (0.37.0)
Collecting astor>=0.6.0
  Using cached https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Collecting wrapt>=1.11.1
  Using cached https://files.pythonhosted.org/packages/61/1f/ea8fa253f36782acdc1dd6a2ebfe6ae84e8d53c7eb6dafe68bc682a357af/wrapt-1.13.2-cp37-cp37m-win_amd64.whl
Processing c:\users\sample\appdata\local\pip\cache\wheels\5c\2e\7e\a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd\gast-0.2.2-cp37-none-any.whl
Collecting absl-py>=0.7.0
  Using cached https://files.pythonhosted.org/packages/97/75/f5e61fb67ecbe45c31035b17562464e11b91a2b8a351bae5ca0db2969e3b/absl_py-0.15.0-py3-none-any.whl
Processing c:\users\sample\appdata\local\pip\cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6\termcolor-1.1.0-cp37-none-any.whl
Collecting protobuf>=3.6.1
  Using cached https://files.pythonhosted.org/packages/d2/0a/b3e777b74356cfcf8812e239869009a52e62345ec2fbba382b7a6cb929a0/protobuf-3.18.1-cp37-cp37m-win_amd64.whl
Collecting tensorboard<1.16.0,>=1.15.0
  Using cached https://files.pythonhosted.org/packages/1e/e9/d3d747a97f7188f48aa5eda486907f3b345cd409f0a0850468ba867db246/tensorboard-1.15.0-py3-none-any.whl
Collecting grpcio>=1.8.6
  Using cached https://files.pythonhosted.org/packages/7a/bd/e4443285fd5ae68ddef66188d3ea13974d7e45b88a1944a220c977991860/grpcio-1.41.0-cp37-cp37m-win_amd64.whl
Collecting opt-einsum>=2.3.2
  Using cached https://files.pythonhosted.org/packages/bc/19/404708a7e54ad2798907210462fd950c3442ea51acc8790f3da48d2bee8b/opt_einsum-3.3.0-py3-none-any.whl
Collecting tensorflow-estimator==1.15.1
  Using cached https://files.pythonhosted.org/packages/de/62/2ee9cd74c9fa2fa450877847ba560b260f5d0fb70ee0595203082dafcc9d/tensorflow_estimator-1.15.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: MarkupSafe>=2.0 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from Jinja2>=2.9->bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (2.0.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from packaging>=16.8->bokeh->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 1)) (2.4.7)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env\lib\site-packages (from importlib-metadata; python_version < "3.8"->click->-r C:\plaidml\conda\condaenv.cl1jgdxs.requirements.txt (line 2)) (3.6.0)
Collecting werkzeug>=0.11.15
  Using cached https://files.pythonhosted.org/packages/1e/73/51137805d1b8d97367a8a77cae4a792af14bb7ce58fbd071af294c740cf0/Werkzeug-2.0.2-py3-none-any.whl
Collecting markdown>=2.6.8
  Using cached https://files.pythonhosted.org/packages/6e/33/1ae0f71395e618d6140fbbc9587cc3156591f748226075e0f7d6f9176522/Markdown-3.3.4-py3-none-any.whl
Installing collected packages: bokeh, click, defaultlist, graphviz, humanize, keras-preprocessing, h5py, keras-applications, keras, networkx, pytz, pandas, pcpp, google-pasta, astor, wrapt, gast, absl-py, termcolor, protobuf, grpcio, werkzeug, markdown, tensorboard, opt-einsum, tensorflow-estimator, tensorflow, theano
  Found existing installation: networkx 2.5
    Uninstalling networkx-2.5:
      Successfully uninstalled networkx-2.5
Successfully installed absl-py-0.15.0 astor-0.8.1 bokeh-2.4.1 click-8.0.3 defaultlist-1.0.0 gast-0.2.2 google-pasta-0.2.0 graphviz-0.17 grpcio-1.41.0 h5py-2.10.0 humanize-3.12.0 keras-2.2.4 keras-applications-1.0.8 keras-preprocessing-1.1.2 markdown-3.3.4 networkx-2.6.3 opt-einsum-3.3.0 pandas-1.3.4 pcpp-1.20.1 protobuf-3.18.1 pytz-2021.3 tensorboard-1.15.0 tensorflow-1.15.0 tensorflow-estimator-1.15.1 termcolor-1.1.0 theano-1.0.5 werkzeug-2.0.2 wrapt-1.13.2

done
#
# To activate this environment, use
#
#     $ conda activate C:\users\sample\_bazel_sample\zmmwpgyj\external\com_intel_plaidml_conda_windows\env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

INFO: Repository llvm-project instantiated at:
  C:/plaidml/WORKSPACE:22:18: in <toplevel>
  C:/plaidml/bzl/workspace.bzl:186:17: in plaidml_workspace
Repository rule http_archive defined at:
  C:/plaidml/vendor/bazel/repo.bzl:51:31: in <toplevel>
INFO: Repository gflags instantiated at:
  C:/plaidml/WORKSPACE:22:18: in <toplevel>
  C:/plaidml/bzl/workspace.bzl:45:17: in plaidml_workspace
Repository rule http_archive defined at:
  C:/plaidml/vendor/bazel/repo.bzl:51:31: in <toplevel>
ERROR: Analysis of target '//plaidml:wheel' failed; build aborted: no such package '@toolchain//': The repository '@toolchain' could not be resolved
INFO: Elapsed time: 219.251s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (56 packages loaded, 232 targets configured)

**Comment by abilashcgit** [comment]
Gentle reminder for an update on this issue. 
Waiting for a solution for the same.

Thanks.

**Comment by ronghongbo** [comment]
Hello, due to resource constraint, we are not actively maintaining the main branch for now, but only plaidml-v1 branch. Sorry for the inconvenience.

**Comment by abilashcgit** [comment]
Ok. In that case, are there any procedure links for PlaidML-v1 branch build using Bezel?

**Comment by ronghongbo** [comment]
We are using ninja. Here are the steps to build:
Install Miniconda3
________________________________
Install the latest Miniconda3 from https://docs.conda.io/en/latest/miniconda.html

Example:

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
conda init

Make sure to re-login so that the 'base' miniconda environment is activated. When you login, you should see (base) at the beginning of your prompt. Instead of re-login also this is possible:
eval "$([PATH_TO_ANACONDA]/bin/conda shell.bash hook)"
Initial configuration and build
________________________________

conda activate
git clone ***@***.******@***.***:plaidml/plaidml.git> --recursive -b plaidml-v1
# if failed in the above clone with an error like
# "could not read from remote repository", try this:
# git clone https://github.com/plaidml/plaidml.git --recursive -b plaidml-v1

cd plaidml

#Prepare for building PlaidML
./configure --no_openvino
# Note:
#   1. the configure command has created an environment named .cenv
#      You can manually create that environment too:
#          rm -rf ./.cenv
#          conda env create -f environment.yml -p .cenv/
#   2. To build the plaidml compiler in debug mode:
#          ./configure --no_openvino --type=Debug

Now add the following to your $HOME/.bashrc (Change YourPathToPlaidML to your installation of plaidml, and Release to Debug if the debug build is to be used):
export PATH=YourPathToPlaidML/build-x86_64/Release/bin:YourPathToPlaidML/build-x86_64/Release/_deps/llvm-project-build/bin:$PATH
Running tests
________________________________
Whenever you start a new shell, set up the environment first:
# Activate the environment
cd plaidml
conda activate ./.cenv

# Optional: this is just one way
cd build-x86_64/Release
ninja && PYTHONPATH=$PWD python plaidml/plaidml_setup.py
# Now you can run any test, for example
#   ninja check-core   #select the llvm cpu device
# An alternative way: Replace the above 3 commands with
#   ninja -C build-x86_64/Release setup check-core
Using ninja check-core  or ninja check-smoke  will run all unit tests.

If want to run all of just the lit tests, use:
ninja pmlc_lit

To run a specific lit test (this is just an example, each lit test might have different arguments, check the first RUN line of the lit test file and use the same arguments):
ninja pmlc-opt && bin/pmlc-opt ../../pmlc/target/x86/tests/reorder_layouts.mlir --split-input-file

To run the EDSL tests:
ninja plaidml_edsl_tests_cc_test && bin/plaidml_edsl_tests_cc_test

To run plaidbench:
ninja plaidbench_py && PYTHONPATH=$PWD KMP_AFFINITY=compact,granularity=fine,1 OMP_NUM_THREADS=56 python plaidbench/plaidbench.py -n1 keras resnet50
Diagnostics and Profiling
________________________________
PlaidML uses easylogging for printing logs, see: https://github.com/amrayn/easyloggingpp#overview

To configure the level of logging, use the PLAIDML_VERBOSEenvironment variable.
For example, to run the EDSL test with verbose logging level 3 and below, use:
ninja plaidml_edsl_tests_cc_test && PLAIDML_VERBOSE=3  bin/plaidml_edsl_tests_cc_test
Use the PLAIDML_PROFILE=1 environment variable to enable profiling. When a network runs, PlaidML will inject timing instrumentation on a per-kernel basis. For example, this will print a comma-delimited report after each run.
ninja plaidbench_py && PLAIDML_PROFILE=1 PYTHONPATH=$PWD KMP_AFFINITY=compact,granularity=fine,1 OMP_NUM_THREADS=56 python plaidbench/plaidbench.py -n1 keras resnet50

To dump the IR after each pass, use PLAIDML_DUMP=/path/to/dir/, and then use PLAIDML_DEBUG=1 to have the locations within the dump files have human friendly names. Note that PLAIDML_DEBUG=1, breaks the ability to parse an IR file (it breaks roundtrip-ability).

**Comment by ronghongbo** [comment]
We are using ninja. Here are the steps to build:

1. Install the latest Miniconda3 from https://docs.conda.io/en/latest/miniconda.html
Example:

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
conda init
```

Make sure to re-login so that the 'base' miniconda environment is activated. When you login, you should see (base) at the beginning of your prompt. Instead of re-login also this is possible:

```
eval "$([PATH_TO_ANACONDA]/bin/conda shell.bash hook)"
```

2. Initial configuration and build

```
conda activate
git clone git@github.com:plaidml/plaidml.git --recursive -b plaidml-v1
# if failed in the above clone with an error like
# "could not read from remote repository", try this:
# git clone https://github.com/plaidml/plaidml.git --recursive -b plaidml-v1

cd plaidml

#Prepare for building PlaidML
./configure --no_openvino
# Note:
#   1. the configure command has created an environment named .cenv
#      You can manually create that environment too:
#          rm -rf ./.cenv
#          conda env create -f environment.yml -p .cenv/
#   2. To build the plaidml compiler in debug mode:
#          ./configure --no_openvino --type=Debug
```

Now add the following to your `$HOME/.bashrc` (Change YourPathToPlaidML to your installation of plaidml, and Release to Debug if the debug build is to be used):

```
export PATH=YourPathToPlaidML/build-x86_64/Release/bin:YourPathToPlaidML/build-x86_64/Release/_deps/llvm-project-build/bin:$PATH
```

3. Running tests
Whenever you start a new shell, set up the environment first:

```
# Activate the environment
cd plaidml
conda activate ./.cenv

# Optional: this is just one way
cd build-x86_64/Release
ninja && PYTHONPATH=$PWD python plaidml/plaidml_setup.py
# Now you can run any test, for example
#   ninja check-core   #select the llvm cpu device
# An alternative way: Replace the above 3 commands with
#   ninja -C build-x86_64/Release setup check-core
```
Using ninja check-core  or ninja check-smoke  will run all unit tests.

If want to run all of just the lit tests, use:

```
ninja pmlc_lit
```
To run a specific lit test (this is just an example, each lit test might have different arguments, check the first RUN line of the lit test file and use the same arguments):

```
ninja pmlc-opt && bin/pmlc-opt ../../pmlc/target/x86/tests/reorder_layouts.mlir --split-input-file
```

To run the EDSL tests:
```
ninja plaidml_edsl_tests_cc_test && bin/plaidml_edsl_tests_cc_test
```

To run plaidbench, for example:
```
ninja plaidbench_py && PYTHONPATH=$PWD KMP_AFFINITY=compact,granularity=fine,1 OMP_NUM_THREADS=56 python plaidbench/plaidbench.py -n1 keras resnet50
```

4. Diagnostics and Profiling
PlaidML uses easylogging for printing logs, see: https://github.com/amrayn/easyloggingpp#overview

To configure the level of logging, use the `PLAIDML_VERBOSE` environment variable.
For example, to run the EDSL test with verbose logging level 3 and below, use:

```
ninja plaidml_edsl_tests_cc_test && PLAIDML_VERBOSE=3  bin/plaidml_edsl_tests_cc_test
```

Use the `PLAIDML_PROFILE=1` environment variable to enable profiling. When a network runs, PlaidML will inject timing instrumentation on a per-kernel basis. For example, this will print a comma-delimited report after each run.

```
ninja plaidbench_py && PLAIDML_PROFILE=1 PYTHONPATH=$PWD KMP_AFFINITY=compact,granularity=fine,1 OMP_NUM_THREADS=56 python plaidbench/plaidbench.py -n1 keras resnet50
```
To dump the IR after each pass, use `PLAIDML_DUMP=/path/to/dir/`, and then use `PLAIDML_DEBUG=1` to have the locations within the dump files have human friendly names. Note that `PLAIDML_DEBUG=1`, breaks the ability to parse an IR file (it breaks roundtrip-ability).

**Comment by abilashcgit** [comment]
@ronghongbo :
I actually wanted to tru plaidm-v1 build using ninja in Windows.
I had followed the steps that you have given, using windows commands (windows 10) in Powershell.

Stuck up with the below error (filenotfound) during configure. 
Are there predefined steps that you had tried before for Plaidml-v1 branch build using Ninja in WINDOWS?


<snip>
(base) PS C:\plaidml> python configure --no_openvino


Configuring PlaidML build environment
Namespace(ci=False, skip_conda_env=False, skip_precommit=False, local_llvm=None, type='Release', target='x86_64', temp=None, no_openvino=True)
conda found at: C:\ProgramData\Miniconda3\Library\bin\conda.BAT
Updating conda environment from: C:\plaidml\environment-windows.yml
['C:\\ProgramData\\Miniconda3\\Library\\bin\\conda.BAT', 'env', 'update', '-f', 'C:\\plaidml\\environment-windows.yml', '-p', 'C:\\plaidml\\.cenv', '--prune'] {'check': True, 'stdout': -3}
Activating conda environment
[WindowsPath('C:/ProgramData/Miniconda3/Library/bin/conda.BAT'), 'run', '--no-capture-output', '-p', WindowsPath('C:/plaidml/.cenv'), 'python', 'configure', '--no_openvino'] {'check': True}
Configuring PlaidML build environment
Namespace(ci=False, local_llvm=None, no_openvino=True, skip_conda_env=False, skip_precommit=False, target='x86_64', temp=None, type='Release')
conda found at: C:\plaidml\.cenv\Library\bin\conda.BAT

Searching for pre-commit in: C:\plaidml\.cenv\Scripts
['C:\\plaidml\\.cenv\\Scripts\\pre-commit.EXE', 'install'] {'check': True}
pre-commit installed at .git\hooks\pre-commit
['cmake', '-S.', '-Bbuild-x86_64\\Release', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache', '-DFETCHCONTENT_QUIET=OFF', '-DPML_OPENVINO_BRIDGE=OFF', '-ULOCAL_LLVM_DIR'] {'check': True}
Traceback (most recent call last):
  File "configure", line 231, in <module>
    main()
  File "configure", line 219, in main
    cfg.configure_cmake(args)
  File "configure", line 177, in configure_cmake
    run(cmd, check=True)
  File "configure", line 35, in run
    subprocess.run(cmd, **kwargs)
  File "C:\plaidml\.cenv\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\plaidml\.cenv\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\plaidml\.cenv\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
ERROR conda.cli.main_run:execute(41): `conda run python configure --no_openvino` failed. (See above for error)
Traceback (most recent call last):
  File "C:\plaidml\configure", line 231, in <module>
    main()
  File "C:\plaidml\configure", line 215, in main
    cfg.activate_conda(args)
  File "C:\plaidml\configure", line 68, in activate_conda
    run(cmd, check=True, env=env)
  File "C:\plaidml\configure", line 35, in run
    subprocess.run(cmd, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[WindowsPath('C:/ProgramData/Miniconda3/Library/bin/conda.BAT'), 'run', '--no-capture-output', '-p', WindowsPath('C:/plaidml/.cenv'), 'python', 'configure', '--no_openvino']' returned non-zero exit status 1.

</snip>

**Comment by ronghongbo** [comment]
The `main` branch of the PlaidML repo is the pre-MLIR "v0" of PlaidML. We are currently focusing on branch plaidml-v1, and unlikely to ever update PlaidML v0 again. Sorry for the inconvenience, but I would suggest you to move to plaidml-v1.

**Comment by abilashcgit** [comment]
@ronghongbo The above errors are from plaidml-v1 itself. Please check and revert back to my queries below on windows build,

Repo was created using "git clone git@github.com:plaidml/plaidml.git --recursive -b plaidml-v1"

plaidml-v1 build using ninja in Windows.
I had followed the steps that you have given, using windows commands (windows 10) in Powershell.
Stuck up with the below error (filenotfound) during configure.


Are there predefined steps that you had tried before for Plaidml-v1 branch build using Ninja in WINDOWS?

**Comment by ronghongbo** [comment]
The instructions I gave are for Linux. I have never tried Windows. You might have to follow the README for [Windows](https://plaidml.github.io/plaidml/docs/install#windows) (Not sure if it works, though). For the lack of resources, our team focuses only on Linux right now.

**Comment by abilashcgit** [comment]
@ronghongbo The Windows build procedure in README https://plaidml.github.io/plaidml/docs/building.html, doesn't work. The original issue faced as in the description above is after trying to Build PlaiML using Bezel in windows.
