### ISSUE TITLE
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json"

### ISSUE THREAD

**Issue by hykilpikonna** [plaidml/plaidml#1910]
```log
Wed 12-22 02:21 HyDEV 🐱 ~
> pip3 install plaidml-keras==0.6.4
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: plaidml-keras==0.6.4 in /usr/local/lib/python3.9/site-packages (0.6.4)
Requirement already satisfied: keras==2.2.4 in /usr/local/lib/python3.9/site-packages (from plaidml-keras==0.6.4) (2.2.4)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from plaidml-keras==0.6.4) (1.12.0)
Requirement already satisfied: plaidml in /usr/local/lib/python3.9/site-packages (from plaidml-keras==0.6.4) (0.7.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (from keras==2.2.4->plaidml-keras==0.6.4) (6.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.9/site-packages (from keras==2.2.4->plaidml-keras==0.6.4) (1.1.2)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.9/site-packages (from keras==2.2.4->plaidml-keras==0.6.4) (1.7.3)
Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.9/site-packages (from keras==2.2.4->plaidml-keras==0.6.4) (1.21.4)
Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.9/site-packages (from keras==2.2.4->plaidml-keras==0.6.4) (1.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.9/site-packages (from keras==2.2.4->plaidml-keras==0.6.4) (3.6.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.9/site-packages (from plaidml->plaidml-keras==0.6.4) (1.14.3)
Requirement already satisfied: enum34>=1.1.6 in /usr/local/lib/python3.9/site-packages (from plaidml->plaidml-keras==0.6.4) (1.1.10)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/site-packages (from cffi->plaidml->plaidml-keras==0.6.4) (2.20)

Wed 12-22 02:21 HyDEV 🐱 ~
> plaidml-setup
Traceback (most recent call last):
  File "/usr/local/bin/plaidml-setup", line 5, in <module>
    from plaidml.plaidml_setup import main
  File "/usr/local/lib/python3.9/site-packages/plaidml/__init__.py", line 50, in <module>
    import plaidml.settings
  File "/usr/local/lib/python3.9/site-packages/plaidml/settings.py", line 33, in <module>
    _setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
  File "/usr/local/lib/python3.9/site-packages/plaidml/settings.py", line 29, in _setup_config
    raise plaidml.exceptions.PlaidMLError(
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".

Wed 12-22 02:21 HyDEV 🐱 ~
> ll /usr/local/lib/python3.9/site-packages/plaidml
total 624
-rw-r--r--   1 hykilpikonna  staff    58K Dec 22 02:16 __init__.py
drwxr-xr-x  10 hykilpikonna  staff   320B Dec 22 02:16 __pycache__
-rwxr-xr-x   1 hykilpikonna  staff   1.3K Dec 22 02:16 boost-LICENSE
-rw-r--r--   1 hykilpikonna  staff   887B Dec 22 02:16 context.py
-rwxr-xr-x   1 hykilpikonna  staff   1.1K Dec 22 02:16 easylogging-LICENSE
-rw-r--r--   1 hykilpikonna  staff   1.8K Dec 22 02:16 exceptions.py
-rwxr-xr-x   1 hykilpikonna  staff   1.4K Dec 22 02:16 gmock-LICENSE
-rwxr-xr-x   1 hykilpikonna  staff   1.1K Dec 22 02:16 half-LICENSE
-rwxr-xr-x   1 hykilpikonna  staff   2.6K Dec 22 02:16 jsoncpp-LICENSE
drwxr-xr-x   5 hykilpikonna  staff   160B Dec 22 02:19 keras
-rw-r--r--   1 hykilpikonna  staff   5.1K Dec 22 02:16 library.py
-rwxr-xr-x   1 hykilpikonna  staff    15K Dec 22 02:16 llvm-LICENSE
-rwxr-xr-x   1 hykilpikonna  staff   876B Dec 22 02:16 minizip-LICENSE
-rw-r--r--   1 hykilpikonna  staff   114K Dec 22 02:16 op.py
-rw-r--r--   1 hykilpikonna  staff   5.6K Dec 22 02:16 plaidml_setup.py
-rwxr-xr-x   1 hykilpikonna  staff   1.7K Dec 22 02:16 protobuf-LICENSE
-rw-r--r--   1 hykilpikonna  staff   6.0K Dec 22 02:16 settings.py
-rwxr-xr-x   1 hykilpikonna  staff   1.0K Dec 22 02:16 six-LICENSE
-rw-r--r--   1 hykilpikonna  staff    52K Dec 22 02:16 tile.py
```

**Comment by hemangjoshi37a** [comment]
Have you found any solutions yet?
can anyone please send the missing experimental.json file any other needed files.
