### ISSUE TITLE
ModuleNotFoundError: No module named 'plaidml.bridge'

### ISSUE THREAD

**Issue by xjdeng** [plaidml/plaidml#1935]
I'm having trouble running plaidml recently, no matter what I try.  It works neither on my work computer (a mac) nor my personal (a Windows 10).  Steps to reproduce (if you're running conda)

1. ```conda create -n plaidml python=3.8``` (Note: I've also tried python 3.7 to no avail.)
2. ```conda activate plaidml```
3. ```pip install plaidml-keras plaidbench```
4. ```plaidml-setup``` (then follow the setup instructions)
5. ```python```
6. Then run the following code:
```
import numpy as np
import os
import time

os.environ["KERAS_BACKEND"] = "plaidml.bridge.keras"

import keras
import keras.applications as kapp
from keras.datasets import cifar10
```

Result:

```
(plaidml) C:\Users\xjd00>python
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import os
>>> import time
>>>
>>> os.environ["KERAS_BACKEND"] = "plaidml.bridge.keras"
>>>
>>> import keras
Traceback (most recent call last):
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\backend\__init__.py", line 93, in <module>
    backend_module = importlib.import_module(_BACKEND)
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plaidml.bridge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\backend\__init__.py", line 108, in <module>
    raise ValueError('Unable to import backend : ' + str(_BACKEND))
ValueError: Unable to import backend : plaidml.bridge.keras
>>> import keras.applications as kapp
Traceback (most recent call last):
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\backend\__init__.py", line 93, in <module>
    backend_module = importlib.import_module(_BACKEND)
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plaidml.bridge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\xjd00\miniconda3\envs\plaidml\lib\site-packages\keras\backend\__init__.py", line 108, in <module>
    raise ValueError('Unable to import backend : ' + str(_BACKEND))
ValueError: Unable to import backend : plaidml.bridge.keras
```

**Comment by mdberryh** [comment]
I used to use plaidML and I'm keeping an eye on it. I think I've ran into issues like this. Which keras version are you using? As far as I can tell the newer keras versions have dramatically changed and I don't know if one can use backends anymore. It seems that keras now depends on tensorflow, which is CUDA only... maybe someone else can offer their input, but that is what I have found so far. You should be able to install the older version of keras back from 2019 and use backends. That's how I was getting my AMD card to work.
