### ISSUE TITLE
plaidml.exceptions.Unknown: Illegal typecast: float to <16 x float>

### ISSUE THREAD

**Issue by shirishr** [plaidml/plaidml#206]
Run

`plaidbench --batch-size 16 --print-stacktraces keras --train mobilenet`

results into the above error
```
Full trace as below:
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/py36/bin/plaidbench", line 11, in <module>
    sys.exit(plaidbench())
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidbench/frontend_keras.py", line 240, in cli
    return runner.run(frontend, networks)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidbench/core.py", line 255, in run
    model_output = model.run(once=True)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidbench/frontend_keras.py", line 167, in run
    initial_epoch=0)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1037, in fit
    validation_steps=validation_steps)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidml/keras/backend.py", line 165, in __call__
    self._invoker.invoke()
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidml/__init__.py", line 1432, in invoke
    return Invocation(self._ctx, self)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidml/__init__.py", line 1438, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidml/__init__.py", line 716, in _check_err
    self.raise_last_status()
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Illegal typecast: float to <16 x float>
```

**Comment by brianretford** [comment]
Hey yeah, see the issue on plaidvision - what os/device/version of plaidml are you using?

**Comment by shirishr** [comment]
plaidml: 0.3.5
ubuntu 18.04
ocl-icd-opencl-dev 2.2.11-1ubuntu1
cpu only
originally a windows machine. Dell Inspiron 15R with intel i7

**Comment by brianretford** [comment]
New stripe based backends do not have this problem, though we have only released iGPU support in preview so far. More soon
