### ISSUE TITLE
Error when using gradient clipping

### ISSUE THREAD

**Issue by cjones903** [plaidml/plaidml#228]
Awesome work with plaidml!

I am experiencing an issue when trying to use gradient clipping with any optimizer. Using clipvalue=1.0 will work while using clipnorm=1.0 will fail complaining about dimensionality of tensors. Here is the specific error:

`Unknown: Applying function, tensor with mismatching dimensionality: I, expected=1, got=2`

**Comment by kilroythethird** [comment]
Can confirm in Plaidml 0.5.0.
Clipnorm values > 0 lead to the above mentioned error.

**stacktrace:**
```
Traceback (most recent call last):
  File "foo.py", line 22, in <module>
    _test(1.)
  File "foo.py", line 11, in _test
    model.train_on_batch(np.ones((5,5)), np.zeros((5,5)))
  File "/home/nope/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "/home/nope/.local/lib/python3.7/site-packages/keras/engine/training.py", line 519, in _make_train_function
    **self._function_kwargs)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 686, in function
    return _Function(inputs, outputs, updates, name)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 148, in __init__
    name=name)
  File "/usr/lib/python3.7/site-packages/plaidml/tile.py", line 1053, in compose
    bindings.insert(op, op.bind(bindings))
  File "/usr/lib/python3.7/site-packages/plaidml/tile.py", line 281, in bind
    applier.add_input(input_name, input_value.bind(bindings))
  File "/usr/lib/python3.7/site-packages/plaidml/__init__.py", line 1362, in add_input
    _lib().plaidml_apply_add_input(self, name.encode(), _as_plaidml_var(value))
  File "/usr/lib/python3.7/site-packages/plaidml/__init__.py", line 746, in _check_err
    self.raise_last_status()
  File "/usr/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Applying function, tensor with mismatching dimensionality: I, expected=1, got=2

```

**Snippet to reproduce:**
```
import keras
from keras.optimizers import Adam
import numpy as np

def _test(clipnorm):
	optimizer = Adam(clipnorm=clipnorm)
	in_ = keras.Input((5,))
	x = keras.layers.Dense(5)(in_)
	model = keras.Model(in_, x)
	model.compile(optimizer=optimizer, loss='mean_absolute_error')
	model.train_on_batch(np.ones((5,5)), np.zeros((5,5)))

for i in range(-10, 11):
	clipnorm = i / 10.
	try:
		_test(clipnorm)
		print("[+] %.2f success" % clipnorm)
	except Exception as e:
		print("[-] %.2f %s" % (clipnorm, e))

# Generate stacktrace
_test(1.)
```

**Comment by brianretford** [comment]
Thanks for the snippet and the details! Mars or Tim, any ideas?

**Comment by YOUSIKI** [comment]
I have met this error and I'm wondering how to solve this.
Can anyone give some advice?
Many thanks!
``` 
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "metal_amd_radeon_pro_560.0"
INFO:plaidml:Analyzing Ops: 52 of 67 operations complete
INFO:plaidml:Analyzing Ops: 50 of 98 operations complete
training model built successfully!
Epoch: 1
Found 82783 images belonging to 1 classes.
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    train(options)
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/helper_functions.py", line 124, in train
    epochs=1, verbose=0, batch_size=options["batch_size"])
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/plaidml/keras/backend.py", line 170, in __call__
    for name in self._output_names
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/plaidml/keras/backend.py", line 170, in <listcomp>
    for name in self._output_names
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/plaidml/__init__.py", line 1430, in get_output_shape
    return _Shape(self._ctx, _lib().plaidml_alloc_invoker_output_shape(self, name.encode()))
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/plaidml/__init__.py", line 764, in _check_err
    self.raise_last_status()
  File "/Users/yousiki/Documents/GitHub/fast-neural-style-keras/venv/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Applying function, tensor with mismatching dimensionality: I10, expected=0, got=2
```

**Comment by tzerrell** [comment]
Probably the same underlying problem as https://github.com/plaidml/plaidml/issues/301

**Comment by SleepProgger** [comment]
Just a heads up: NOT fixed in plaidml 0.6.1

**Comment by jaltmayerpizzorno** [comment]
I just ran into this issue using PlaidML from master (VERSION says 0.7.0).
