### ISSUE TITLE
Issue working with tensor slice

### ISSUE THREAD

**Issue by JKRuebush** [plaidml/plaidml#235]
I only have half an idea of what I am doing, so this may not turn out to actually be an issue.

I want to use spatial pyramid pooling, so I grabbed the implementation from [keras-spp](https://github.com/yhenon/keras-spp/blob/master/spp/SpatialPyramidPooling.py). After stripping out code having to do with the dimension ordering, here is the relevant part:

```Python
def call(self, x, mask=None):
    input_shape = K.shape(x)

    num_rows = input_shape[1]
    num_cols = input_shape[2]

    row_length = [K.cast(num_rows, 'float32') / i for i in self.pool_list]
    col_length = [K.cast(num_cols, 'float32') / i for i in self.pool_list]

    outputs = []

    for pool_num, num_pool_regions in enumerate(self.pool_list):
        for jy in range(num_pool_regions):
            for ix in range(num_pool_regions):
                x1 = ix * col_length[pool_num]
                x2 = ix * col_length[pool_num] + col_length[pool_num]
                y1 = jy * row_length[pool_num]
                y2 = jy * row_length[pool_num] + row_length[pool_num]

                x1 = K.cast(K.round(x1), 'int32')
                x2 = K.cast(K.round(x2), 'int32')
                y1 = K.cast(K.round(y1), 'int32')
                y2 = K.cast(K.round(y2), 'int32')

                new_shape = [input_shape[0], y2 - y1,
                                x2 - x1, input_shape[3]]

                x_crop = x[:, y1:y2, x1:x2, :]
                xm = K.reshape(x_crop, new_shape)
                pooled_val = K.max(x_crop, axis=(1, 2))
                outputs.append(pooled_val)

    outputs = K.concatenate(outputs)
    return outputs
```

With the problem line being:

```Python
x_crop = x[:, y1:y2, x1:x2, :]
```

This works fine with Tensorflow, but it looks like PlaidML doesn't support slicing this way. Spotting `slice_tensor` in `op`, I made this change:

```Python
# x_crop = x[:, y1:y2, x1:x2, :]
x_crop = slice_tensor(x,
                      axes=(1,2),
                      starts=(y1,x1),
                      ends=(y2,x2))
```

However, this leads to

```
ERROR:plaidml:syntax error, unexpected ID, expecting "," or ) :
        function (I[D0, D1, D2, D3]) -> (O) {
            O[d0, d1, d2, d3 : D0, min(Cast INT32(), D1)-min(Cast INT32(), D1), min(Cast INT32(), D2)-min(Cast INT32(), D2), D3] = =(I[d0, d1+min(Cast INT32(), D1), d2+min(Cast INT32(), D2), d3]);
        }
Traceback (most recent call last):
  File ".\main.py", line 175, in <module>
    dcgan.train(epochs=4001, batch_size=32, save_interval=50)
  File ".\main.py", line 136, in train
    d_loss_real = self.discriminator.train_on_batch(imgs, valid)
  File "...\Python36\lib\site-packages\keras\engine\training.py",
line 1216, in train_on_batch
    self._make_train_function()
  File "...\Python36\lib\site-packages\keras\engine\training.py",
line 519, in _make_train_function
    **self._function_kwargs)
  File "...\Python36\lib\site-packages\plaidml\keras\backend.py",
line 686, in function
    return _Function(inputs, outputs, updates, name)
  File "...\Python36\lib\site-packages\plaidml\keras\backend.py",
line 148, in __init__
    name=name)
  File "...\Python36\lib\site-packages\plaidml\tile.py", line 1053, in compose
    bindings.insert(op, op.bind(bindings))
  File "...\Python36\lib\site-packages\plaidml\tile.py", line 278, in bind
    func = plaidml.Function(self.code, backtrace=self.backtrace, fid=safe_name)
  File "...\Python36\lib\site-packages\plaidml\__init__.py", line
891, in __init__
    code.encode(), fid.encode()))
  File "...\Python36\lib\site-packages\plaidml\__init__.py", line
746, in _check_err
    self.raise_last_status()
  File "...\Python36\lib\site-packages\plaidml\library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.ResourceExhausted: Out of memory
```

I probably am misusing the function, but don't think that's the error I should be getting.

In case something else is actually breaking things, the rest of my code is taken from the [Keras-GAN DCGAN](https://github.com/eriklindernoren/Keras-GAN/blob/master/dcgan/dcgan.py). The only modifications I made were importing the layer and the following at around line 96:
```Python
# model.add(Flatten())
model.add(SpatialPyramidPooling([1, 2, 4]))
```

**Comment by earhart** [comment]
That looks like invalid Tile code.
IIRC, `slice_tensor` requires a list of ints or `tile.Value` for the starts and ends; I'm not sure what `K.cast()` is producing, but it doesn't appear to be either of these.

**Comment by JKRuebush** [comment]
It looks like `K.cast()` is ultimately returning a `tile.Shape`. Based on that, I don't see any easy/obvious way to get SPP to work the way I want it to here. It could work with a known input size. All that would need is swapping out `K.shape()` for `K.int_shape()` along with swapping the logic to using ints. However, the reason I wanted to use it was to play around with arbitrarily sized images.

**Comment by brianretford** [comment]
Tim or Rob, any thoughts? There should be a mechanism to get this to work like you want to

**Comment by SleepProgger** [comment]
I ran into the same error porting a masked loss function.

Error:
```
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "opencl_amd_ellesmere.0"
ERROR:plaidml:syntax error, unexpected ID, expecting "," or ] : function (I0[N0, N1, A0], I1[N0, N1, A1], I2[N0, N1, A2]) -> (O) {
  T0[n0, n1, a+0: N0, N1, Add UINT64()] = =(I0[n0, n1, a]);
  T1[n0, n1, a+Ceiling UINT64(): N0, N1, Add UINT64()] = =(I1[n0, n1, a]);
  T2[n0, n1, a+Add UINT64(): N0, N1, Add UINT64()] = =(I2[n0, n1, a]);
  O = T0 + T1 + T2;
}
Traceback (most recent call last):
  File "/run/media/nope/data/home/nope/workspace/test/plaidml_slice_test.py", line 34, in <module>
    model.train_on_batch(np.zeros((32, 64, 64, 3)), np.ones((32, 64, 64, 3)))
  File "/home/nope/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "/home/nope/.local/lib/python3.7/site-packages/keras/engine/training.py", line 519, in _make_train_function
    **self._function_kwargs)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 686, in function
    return _Function(inputs, outputs, updates, name)
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 148, in __init__
    name=name)
  File "/usr/lib/python3.7/site-packages/plaidml/tile.py", line 1053, in compose
    bindings.insert(op, op.bind(bindings))
  File "/usr/lib/python3.7/site-packages/plaidml/tile.py", line 278, in bind
    func = plaidml.Function(self.code, backtrace=self.backtrace, fid=safe_name)
  File "/usr/lib/python3.7/site-packages/plaidml/__init__.py", line 891, in __init__
    code.encode(), fid.encode()))
  File "/usr/lib/python3.7/site-packages/plaidml/__init__.py", line 746, in _check_err
    self.raise_last_status()
  File "/usr/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.ResourceExhausted: Out of memory
```

Code:
```
    import keras
    import numpy as np
    from keras import backend as K
    
    
    def dummy_loss(y_true, y_pred):
        mask = 1
        tr, tg, tb = (y_true[:, :, :, i] for i in range(3))
        pr, pg, pb = (y_pred[:, :, :, i] for i in range(3))
        tr *= mask
        tg *= mask
        tb *= mask
        pr *= mask
        pg *= mask
        pb *= mask
        y_pred = K.reshape(K.concatenate([pr,pg,pb], axis=-1), K.int_shape(y_pred))
        y_true = K.reshape(K.concatenate([tr,tg,tb], axis=-1), K.int_shape(y_pred))
        return keras.losses.mean_squared_error(y_true, y_pred)
    
    in_ = x = keras.Input((64, 64, 3))
    x = keras.layers.Conv2D(3, 3, strides=1, padding="same")(x)    
    model = keras.Model(in_, x)
    model.compile("Adam", dummy_loss)
    
    model.train_on_batch(np.zeros((32, 64, 64, 3)), np.ones((32, 64, 64, 3)))
```

It works well when not changing `y_true` in the loss function.
Might be related to the fact that the int_shape of `y_true` is `(None, None, None, None)` while the one of `y_pred` is `(None, 64, 64, 3)`


*I ended up using K.repeat_elements to change my mask (which in reality has a shape of (None,64,64,1) ) to (None, 64, 64, 3) and don't use slicing at all.*

**Comment by brianretford** [comment]
Both of these issues are related to using the results of computations based on runtime parameters as dimensions of tensors. We will support this in upcoming releases
