### ISSUE TITLE
TypeError: Cannot cast scalar from dtype('O') to dtype('<f4') according to the rule 'same_kind'

### ISSUE THREAD

**Issue by crowoy** [plaidml/plaidml#262]
I've been trying to get a LSTM based project up and running with PlainML.

I'm getting: `TypeError: Cannot cast scalar from dtype('O') to dtype('<f4') according to the rule 'same_kind'` error when running with PlaidML backend - this includes OpenCL / Metal / LLVM on all of: CPU / Intel Graphics 630 / AMD Radeon Pro 560X.

This error does not appear when simply running with Keras.

```
(env) $ python run_all.py
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "metal_amd_radeon_pro_560x.0 / opencl_amd_amd_radeon_pro_560x_compute_engine.0"
Compilation Time (s) : 0.00164794921875
Train on 2393 samples, validate on 423 samples
Traceback (most recent call last):
  File "run_all.py", line 121, in <module>
    results_config = run.run_configuration ([...])
  File "xxx/dev/run.py", line 107, in run_configuration
    model.fit(xs_norm[:,:,1:], ys_norm[:,1], batch_size=batch_size, epochs=epochs,
    validation_split=validation_split, callbacks=[esCallBack], shuffle=False)
  File "xxx/env/lib/python3.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "xxx/env/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "xxx/env/lib/python3.7/site-packages/plaidml/keras/backend.py", line 165, in __call__
    val = variable(val, dtype=self._input_types[name]).var
  File "xxx/env/lib/python3.7/site-packages/plaidml/keras/backend.py", line 1669, in variable
    view.copy_from_ndarray(value)
  File "xxx/env/lib/python3.7/site-packages/plaidml/__init__.py", line 1174, in copy_from_ndarray
    np.copyto(dst, src)
TypeError: Cannot cast scalar from dtype('O') to dtype('<f4') according to the rule 'same_kind'
```

Here are examples of the values given to `model.fit`:

```
xs_norm[:,:,1:]: ... // type: <class 'numpy.ndarray'>
ys_norm[:,1]: ... // type: <class 'numpy.ndarray'>
batch_size: 32 // type: <class 'int'>
epochs: 1000 // type: <class 'int'>
validation_split: 0.15 // type: <class 'float'>
[esCallBack]: [<keras.callbacks.EarlyStopping object at 0x135838898>] // type: <class 'list'>
```

**Comment by brianretford** [comment]
Can you provide a minimal code example that reproduces? In general LSTM support isn't great in PlaidML right now. We are planning on addressing that in the next month or two

**Comment by David4D** [comment]
It's work after a reboot (device "metal_nvidia_geforce_gt_750m.0")

**Comment by crowoy** [comment]
@brianretford - I'm struggling to put together a minimal code example...

I'm not sure if it's a factor, but I noticed that when I run it without PlaidML, I get the 2 warnings below - the program runs as expected.

I don't get these warnings when I run with PlaidML.

```
WARNING:tensorflow:From /env/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.

WARNING:tensorflow:From /env/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
```

**Comment by brianretford** [comment]
those warnings shouldn't matter. Mars is quite familiar with typing errors that pop up in plaid. If this blocking your work?

**Comment by crowoy** [comment]
This issue isn't stopping my work, but I imagine being able to train and infer on GPU would drastically speed it up. Often my training batches take 10-14 days on CPU.

**Comment by brianretford** [comment]
If you even provide a mockup of your code that doesn't run and doesn't reveal anything you want to reveal that would probably help us. Also, call plaidml._internal_set_vlog(True) you should get tons of logs that would really help us.

**Comment by brianretford** [comment]
We'd really love some more specific reproduction code if possible as we'd love to fix this.

**Comment by DimaDDM** [comment]
I have same issue on my iMac with `AMD RADEON PRO 555` and Mac Book Air with `Intel HD Graphics 6000`.
Test networks working without error, but not mine.

My NN model looks like
```
create_model(self, units, activ, opt, loss, metrics):
        model = models.Sequential()
        in_shape = (self.train_data.shape[1],)
        model.add(layers.Dense(units, activation=activ, input_shape=in_shape))
        model.add(layers.Dense(units, activation=activ))
        model.add(layers.Dense(1))
        model.compile(optimizer=opt, loss=loss, metrics=metrics)
        self.model = model
```

`create_model(units=64, activ="relu", opt="rmsprop", loss="mse", metrics=["mae"])`

without `os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"` all work fine.

**Comment by DimaDDM** [comment]
And  after setup with `plaidml-setup` folder `/Users/%USER%/.plaidml` not exists but command output `Success!`

**Comment by dgkutnic** [comment]
@DimaDDM I tried reproducing your error with the code snippet you provided, but it is working fine for me for both TensorFlow and PlaidML. Could you provide me with more information about the input shape you used in your model?

**Comment by DimaDDM** [comment]
Okay.

Normalization for data
 ```
minimum = self.train_data.min()
self.train_data -= minimum
ptp = self.train_data.ptp()
self.train_data /= ptp

self.test_data -= minimum
self.test_data /= ptp
```

Input shape
```
[[0.5087424850688349 0.42807573217731204 0.4291560905260425
  0.4291560904756656]
 [0.47884268284531145 0.4468573661612375 0.42915609052790155
  0.4291560904763648]
 [0.5321896718621563 0.49402908616319824 0.42915609053771947
  0.42915609047706404]
 ...
 [0.5746546743219217 0.5276613428930929 0.42915609054033693
  0.4291560904777632]
 [0.5155102732877647 0.44340007939254106 0.42915609053724846
  0.4291560904784624]
 [0.45447801545432526 0.44238736659030653 0.4291560905397955
  0.42915609047916164]]
```

Log
  ```
File "venv/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "venv/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "venv/lib/python3.6/site-packages/plaidml/keras/backend.py", line 164, in __call__
    val = variable(val, dtype=self._input_types[name]).var
  File "/venv/lib/python3.6/site-packages/plaidml/keras/backend.py", line 1736, in variable
    view.copy_from_ndarray(value)
  File "venv/lib/python3.6/site-packages/plaidml/__init__.py", line 1205, in copy_from_ndarray
    np.copyto(dst, src)
  File "<__array_function__ internals>", line 6, in copyto
TypeError: Cannot cast scalar from dtype('O') to dtype('<f4') according to the rule 'same_kind'
```

**Comment by oestej** [comment]
Also experiencing this bug.  Works fine on Keras w/o PlaidML.

Relevant code snips follow below:

`import plaidml.keras
plaidml.keras.install_backend()

from keras.models import Sequential
from keras.layers import Dense, Activation

[...]
def try_neural_classifier(X, y, X2, y2):
	model = Sequential()
	model.add(Dense(6,activation='relu',input_dim=X.shape[1]))
	model.add(Dense(1, activation='sigmoid'))
	model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
	model.fit(X, y, epochs=110, batch_size=32, verbose=0)
	yP = model.predict_classes(X2, verbose=0)
	print_metrics(y2,yP, "NN")`

Logs:

`INFO:plaidml:Opening device "metal_intel(r)_iris(tm)_plus_graphics_650.0"
Traceback (most recent call last):
  File "<redacted>", line 235, in <module>
    try_neural_classifier(X,y,X2,y2)
  File "<redacted>", line 182, in try_neural_classifier
    model.fit(X, y, epochs=110, batch_size=32, verbose=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plaidml/keras/backend.py", line 164, in __call__
    val = variable(val, dtype=self._input_types[name]).var
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plaidml/keras/backend.py", line 1736, in variable
    view.copy_from_ndarray(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plaidml/__init__.py", line 1205, in copy_from_ndarray
    np.copyto(dst, src)
  File "<__array_function__ internals>", line 6, in copyto
TypeError: Cannot cast scalar from dtype('O') to dtype('<f4') according to the rule 'same_kind'`

**Comment by bogdad** [comment]
hey, bumped into the same issue i think, also have a ltsm step in a classification problem

```
    model.fit(X_train, Y_train, validation_split=0.25, epochs=60, batch_size=128)
  File "../workspace/.../plaidml-venv/lib/python3.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "../workspace/.../plaidml-venv/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "../workspace/.../plaidml-venv/lib/python3.7/site-packages/plaidml/keras/backend.py", line 164, in __call__
    val = variable(val, dtype=self._input_types[name]).var
  File "../workspace/.../plaidml-venv/lib/python3.7/site-packages/plaidml/keras/backend.py", line 1736, in variable
    view.copy_from_ndarray(value)
  File "../workspace/.../plaidml-venv/lib/python3.7/site-packages/plaidml/__init__.py", line 1209, in copy_from_ndarray
    np.copyto(dst, src)
  File "<__array_function__ internals>", line 6, in copyto
TypeError: Cannot cast scalar from dtype('O') to dtype('<f4') according to the rule 'same_kind'
```

if I add prints to copy_from_ndarray(..) like this

``` 
    def copy_from_ndarray(self, src):
        print(self._dtype) # added 
        print(src.dtype) # added 
        if self._dtype == DType.FLOAT16:
            if src.dtype != 'float16':
                src = src.astype('float16')
            src = src.view(dtype='uint16')
        if src.dtype == object: # added 
            print(src) # added 
        dst = np.ctypeslib.as_array(self._base, shape=src.shape)
        np.copyto(dst, src)
```

I get, just before the traceback
``` 
DType.FLOAT32
int32
DType.FLOAT32
object
[[0]
 [1]
...
]
```

if i change copy_from_ndarray to 
```
    def copy_from_ndarray(self, src):
        if self._dtype == DType.FLOAT16:
            if src.dtype != 'float16':
                src = src.astype('float16')
            src = src.view(dtype='uint16')
        if self._dtype == DType.FLOAT32 and src.dtype == object:
            src = src.astype('float16') # probably not correct
            src = src.view(dtype='uint16')  # probably not correct
        dst = np.ctypeslib.as_array(self._base, shape=src.shape)
        np.copyto(dst, src)
```

it seems to work for me, thats a hack though, don't know enough to implement a proper fix,
hope that helps

**Comment by Alex-W-Haas** [comment]
I implemented the fix that @bogdad did, and it allowed me to train my model, however it greatly increased the time need per epoch to train (from ~40 sec. to >7 min)

**Comment by Metalkiler** [comment]
Hey Guys for this issue you could try the following:

 history=model.fit(train_X.to_numpy().astype('float'), Promos_train_Y.target,
                      epochs=100,
                      batch_size=2**10,callbacks = callbacks_list,validation_split=0.3)
it forces to be a matrix type float and does not give that error, at least for me
I hope it helps

**Comment by Metalkiler** [comment]
Also if you are using sparse dataframes it causes that error as well @crowoy

**Comment by elliptic1** [comment]
I have the same error with an LSTM layer, and when I added `astype('float')` to `X` it changes to this error:

`TypeError: Cannot cast scalar from dtype('<U7') to dtype('<f4') according to the rule 'same_kind'`

**Comment by Metalkiler** [comment]
Have you tried also the @bogdad solution, with the One I presented?

It worked for me though @elliptic1
