### ISSUE TITLE
plaidml.exceptions.Unknown: Error: Always false constraint given to MergeParallelConstraints.

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#272]
I am not sure if i messed something up, but i ran into another problem regarding slicing (probably).
After the first steps implementing a (non functional) version of `tf.extract_image_patches` like this:

```
def extract_image_patches(images, ksizes, strides, rates, padding):
    patches = []
    p_height, p_width = ksizes[1:3]
    i_shape = K.int_shape(images)
    for y in range(0, i_shape[1]-p_height+1, p_height):
        for x in range(0, i_shape[2]-p_width+1, p_width):
            d = images[:, y:y+p_height, x+p_width, :]
            patches.append(d)
    result = K.concatenate(patches, axis=-1)
    return result

BATCHES = 10
IMG_SHAPE = (6,6,3)
SIDE = 3
images = np.random.rand(BATCHES, *IMG_SHAPE)
k_images = K.variable(images, dtype=images.dtype)    
k_patches = extract_image_patches(k_images, ksizes, strides, rates, padding).eval()
```

i ran into this error:
```
Traceback (most recent call last):
  File "image_patches.py", line 76, in <module>
    k_patches = extract_image_patches(k_images, ksizes, strides, rates, padding).eval()
  File "/home/nope/.conda/envs/py3_6/lib/python3.6/site-packages/plaidml/keras/backend.py", line 710, in get_value
    invoker.invoke()
  File "/home/nope/.conda/envs/py3_6/lib/python3.6/site-packages/plaidml/__init__.py", line 1428, in invoke
    return Invocation(self._ctx, self)
  File "/home/nope/.conda/envs/py3_6/lib/python3.6/site-packages/plaidml/__init__.py", line 1437, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/home/nope/.conda/envs/py3_6/lib/python3.6/site-packages/plaidml/__init__.py", line 746, in _check_err
    self.raise_last_status()
  File "/home/nope/.conda/envs/py3_6/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Error: Always false constraint given to MergeParallelConstraints.
```

Possible related to https://github.com/plaidml/plaidml/issues/235

**Comment by brianretford** [comment]
can you print out the values of the parameters in extract_image_patches when this error happens? It seems like an case where some boundaries are causing nothing to be done, but I don't think it should fail like this. @tzerrell is the right person to look at this but @jbruestle might be able to get around to it

**Comment by SleepProgger** [comment]
Hmm, it doesn't matter which values for `ksizes` and which image shapes i used.
All led to the same error.

BUT, after i fixed a stupid error of mine it now works like expected.
Complete failing version
```
def extract_image_patches(images, ksizes):
    patches = []
    p_height, p_width = ksizes[1:3]
    i_shape = K.int_shape(images)
    for y in range(0, i_shape[1]-p_height+1, p_height):
        for x in range(0, i_shape[2]-p_width+1, p_width):
            d = images[:, y:y+p_height, x+p_width, :]
            patches.append(d)
    result = K.concatenate(patches, axis=-1)
    return result

IMG_SHAPE = (2, 4, 4, 1)
ksizes = [1, 2, 2, 1]
images = np.random.rand(*IMG_SHAPE)
k_images = K.variable(images, dtype=images.dtype)    
k_patches = extract_image_patches(k_images, ksizes).eval()
```

Working `extract_images_patches`
```
def extract_image_patches(images, ksizes):
    patches = []
    p_height, p_width = ksizes[1:3]
    i_shape = K.int_shape(images)
    for y in range(0, i_shape[1]-p_height+1, p_height):
        for x in range(0, i_shape[2]-p_width+1, p_width):
            d = images[:, y:y+p_height, x:x+p_width, :]
            patches.append(d)
    result = K.concatenate(patches, axis=-1)
    return result
```

So:
`d = images[:, y:y+p_height, x+p_width, :]`
vs 
`d = images[:, y:y+p_height, x:x+p_width, :]`

It seems like concat or slicing does not like when using a fixed index vs a range.

**Comment by SleepProgger** [comment]
My, bad. All that is is an index out of bounds error.
Same error:
`K.variable([1,2,3], dtype=images.dtype)[4].eval()`

Sorry for the noise.

**Comment by brianretford** [comment]
No worries, thanks for being engaged!

**Comment by brianretford** [comment]
How's performance? We'd love a PR

**Comment by SleepProgger** [comment]
Not sure about performance yet. Still struggling to get a plaidml version going that is fully compatible with TFs version (tf extract_image_patches version is really strange when it comes to rates).

A complete working (tho not fully tested) but ugly K version so far:
```
def extract_image_patches_k(images, ksizes, strides, rates, padding):
    r_strides_y = strides[1] - ksizes[1]
    r_strides_x = strides[2] - ksizes[2]
    ishape = images.shape.dims
    laxis = ksizes[1]*ksizes[2]*ishape[-1]
     
    if rates[1] != ksizes:
        ksizes[1] = ksizes[1] + (ksizes[1] -1) * (rates[1] - 1)
    if rates[2] != ksizes:
        ksizes[2] = ksizes[2] + (ksizes[2] -1) * (rates[2] - 1)
    print("New ksizes", ksizes)
    
    ishape = images.shape.dims
    patches_y = (ishape[1] + r_strides_y) // (ksizes[1] + r_strides_y)
    patches_x = (ishape[2] + r_strides_x) // (ksizes[2] + r_strides_x)
    
    patches = []
    fx, fy = (0, 0)
    for y in range(0, ishape[1], strides[1]):
        if y + ksizes[1] > ishape[1]:
            break
        fx = 0
        fy += 1
        for x in range(0, ishape[2], strides[2]):
            if x + ksizes[2] > ishape[2]:
                continue
            patch = images[:, y:y+ksizes[1]:rates[1], x:x+ksizes[2]:rates[2], :]
            patch = K.reshape(patch, (ishape[0], 1, 1, laxis))
            patches.append(patch)
            fx += 1
            
    patches = K.concatenate(patches, -1)
    nshape = (ishape[0], fy, fx, laxis)
    patches = K.reshape(patches, nshape)
    return patches
```

Will send an PR as soon as i have a working and tested TILE version for this madness ;)
