### ISSUE TITLE
OSError: dlopen(/usr/local/lib/python3.7/site-packages/plaidml/libplaidml.dylib, 6): image not found

### ISSUE THREAD

**Issue by JL1829** [plaidml/plaidml#277]
Dear Guys: 

I am new to PlaidML, currently using 2018 MacBook Pro with Mojave 10.14.3, and using Python 3.7.2,  just downloaded PlaidML-Keras with Brew, when I try to use plaidml-setup, it show the errors below: 

```
(plaidml-venv) ➜  plaidml_keras plaidml-setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 155, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/python3.7/site-packages/plaidml/libplaidml.dylib, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/plaidml-setup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/plaidml/plaidml_setup.py", line 15, in main
    ctx = plaidml.Context()
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 858, in Context
    return plaidml.context.Context(_lib())
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 758, in _lib
    _impl_lib = _Library()
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 175, in __init__
    lib = load_library('libplaidml.dylib', ['lib'])
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 165, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/libplaidml.dylib, 6): image not found
(plaidml-venv) ➜  plaidml_keras 
```

Have any ideas what's happening?

Thanks!!

**Comment by brianretford** [comment]
try uninstalling plaidml and plaidml-keras, and then just installing plaidml-keras. There seems to be a situation in which keras can overwrite part of plaidml

**Comment by JL1829** [comment]
> try uninstalling plaidml and plaidml-keras, and then just installing plaidml-keras. There seems to be a situation in which keras can overwrite part of plaidml

Dear Brian: 

Yes, I done this, and re-install plaidml-keras alone, and I also try to reproduce it in fresh installed Ubuntu 18.04, give me the same error. 

Wondering can I just clone the source and build it locally.

**Comment by brianretford** [comment]
I'm really not sure. We all use macbooks for development every day

**Comment by leedrake5** [comment]
Can you confirm you are installing plaidml to the right instance of python? My pip on my MacBook defaults to a system 2.6 instance, I had to export my paths to get it to install right.

**Comment by rogeriochaves** [comment]
because I installed python with brew, the lib was being copied to the wrong folder, this fixed for me:

```
ln -s /usr/local/lib/libplaidml.dylib /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/
```

**Comment by JL1829** [comment]
Dear Guys: 

Thanks for the help, after all, I choose the hard way, reinstall the macOS. 
now everything fine.

**Comment by zachmayer** [comment]
This happened to me when I tried to install outside of a virtual env.

Installing inside a virtual env worked fine
