### ISSUE TITLE
plaidml-setup throws SyntaxError: invalid syntax on line 1320 (MacOS)

### ISSUE THREAD

**Issue by sfsdfd** [plaidml/plaidml#321]
Following the install guide on MacOS (Mojave) currently throws this breaking exception on setup:

```
Code $ virtualenv plaidml-venv

New python executable in /Users/test/Documents/Files/Deep Learning/Code/plaidml-venv/bin/python
Installing setuptools, pip, wheel...
. pladone.

Code $ . plaidml-venv/bin/activate

(plaidml-venv) Code $ pip install -U plaidml-keras

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Collecting plaidml-keras (etc.)

Installing collected packages: six, numpy, h5py, keras-applications, scipy, keras-preprocessing, pyyaml, keras, enum34, plaidml, plaidml-keras

Successfully installed enum34-1.1.6 h5py-2.9.0 keras-2.2.4 keras-applications-1.0.7 keras-preprocessing-1.0.9 numpy-1.16.3 plaidml-0.6.0 plaidml-keras-0.6.0 pyyaml-5.1 scipy-1.2.1 six-1.12.0

(plaidml-venv) Code $ plaidml-setup

Traceback (most recent call last):

  File "/Users/test/Documents/Files/Deep Learning/Code/plaidml-venv/bin/plaidml-setup", line 8, in <module>
    from plaidml.plaidml_setup import main

  File "/Users/test/Documents/Files/Deep Learning/Code/plaidml-venv/lib/python2.7/site-packages/plaidml/__init__.py", line 1320
    def __init__(self, ctx, dtype, *args, layout=None):
                                               ^
SyntaxError: invalid syntax

(plaidml-venv) Code $ pip freeze

enum34==1.1.6
h5py==2.9.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
numpy==1.16.3
plaidml==0.6.0
plaidml-keras==0.6.0
PyYAML==5.1
scipy==1.2.1
six==1.12.0
(plaidml-venv) Code $ 
```

**Comment by chrisbarrera** [comment]
This is a known issue  they are fixing. Use python3 and it will work.

**Comment by sfsdfd** [comment]
No, Python 3 also doesn't work. That's actually what I tried first.

Code $ virtualenv plaidml-venv

New python executable in /Users/test/Documents/Files/Deep Learning/Code/plaidml-venv/bin/python

Installing setuptools, pip, wheel...
done.

Code $ . plaidml-venv/bin/activate

(plaidml-venv) Code $ pip3 install -U plaidml-keras

Requirement already up-to-date: plaidml-keras in /Users/test/Library/Python/3.7/lib/python/site-packages (0.6.0)
(etc.)

(plaidml-venv) Code $ plaidml-setup
-bash: plaidml-setup: command not found

**Comment by chrisbarrera** [comment]
Did you install the plaidml package in addition to plaidml-keras? You need to pip install 2 packages.

I originally reported the same issue you did and diagnosed it as a python3-ism that doesn't work under python2. I don't get the error you got when I use python3. But now you are showing plaidml-setup as not found, a different error, so now there is something else going on.

In any event I am not getting the line 1320 error with the 0.6.0 version under python3 but I can recreate it under python2. I don't get the plaidml-setup not found error and that could be due to a missing package.

**Comment by sfsdfd** [comment]
Yes. See above.

I uninstalled both plaidml and plaidml-keras and then reinstalled both of them via pip3. Now I'm getting this error when running plaidml-setup:

    (plaidml-venv) Code $ plaidml-setup

    Traceback (most recent call last):

    File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 154, in load_library
        return ctypes.cdll.LoadLibrary(libpath)
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)

    OSError: dlopen(/usr/local/lib/python3.7/site-packages/plaidml/libplaidml.dylib, 6): image not found

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):

    File "/usr/local/bin/plaidml-setup", line 10, in <module>
        sys.exit(main())
    File "/usr/local/lib/python3.7/site-packages/plaidml/plaidml_setup.py", line 15, in main
        ctx = plaidml.Context()
    File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 876, in Context
        return plaidml.context.Context(_lib())
    File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 776, in _lib
        _impl_lib = _Library()
    File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 174, in __init__
        lib = load_library('libplaidml.dylib', ['lib'])
    File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 164, in load_library
        return ctypes.cdll.LoadLibrary(libpath)
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
    File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)

    OSError: dlopen(/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/libplaidml.dylib, 6): image not found

**Comment by chrisbarrera** [comment]
It appears you have multiple python installs or at least multiple environments. It is looking for the dynamic lib under /usr/local/Cellar/python/3.7.3 when in earlier messages you have keras installed in /Users/test/Library/Python/3.7/lib/python/site-packages . So it makes sense it can't find it if using wrong python env.

**Comment by brianretford** [comment]
This is unrelated to the original issue, but if someone finds a resolution to this we'll happily include it in our FAQ. I'm not sure we can do much in software to address this.
