### ISSUE TITLE
Ngraph with plaidml backend leads to invalid opencl kernel

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#322]
When using a self compiled version of ngraph-tf to test ngraph with the plaidml backend i ran into some invalid generated opencl kernels because floor is called with integer parameter which leads to `'floor' is ambiguous` errors.

I used a slightly changed version of the keras example from ngraph-tf:
```
import tensorflow as tf
from keras.applications.resnet50 import ResNet50, preprocess_input, decode_predictions
import numpy as np
import sys

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("USAGE: %s NGRAPH_backend or NONE" % sys.argv[0])
        exit()
    if sys.argv[1] != "NONE":
        import ngraph_bridge
        print("Supported ngraph backend:\n  %s" % "\n  ".join(ngraph_bridge.list_backends()))
        ngraph_bridge.set_backend(sys.argv[1])
        print("Using ngraph backend %s" % ngraph_bridge.get_currently_set_backend_name())

    # A simple script to run inference and training on resnet 50
    model = ResNet50(weights='imagenet')
    
    batch_size = 8
    img = np.random.rand(batch_size, 224, 224, 3)
    preds = model.predict(preprocess_input(img))
    print('Predicted:', decode_predictions(preds, top=3)[0])
    model.compile("SGD", loss='categorical_crossentropy')
    preds = model.fit(
        preprocess_input(img), np.zeros((batch_size, 1000), dtype='float32'))
    print('Ran a train round')
```

When being executed like `python KERAS_BACKEND="tensorflow" python test_ngraph_bridge.py PLAIDML`
this leads to this output: https://gist.github.com/SleepProgger/c8c2ece66d6aed3010ff83c7c029b166
The error happens at the training phase, prediction works fine.

This is the same behaviour as this snippet produces with keras->plaidml:
`K.floor(K.constant(np.zeros(10, dtype=int), dtype=plaidml.DType.INT32)).eval()`
As there is no point ever to call `floor` on integer maybe the HAL or Tile should noop all floor calls with integer inputs (Same problem with `ceil` btw).

I am having some other problems with the ngraph-tf bridge, but that might be my fault because i used py3.7 instead of py3.5. This example ran ok via keras->tf->ngraph->cpu, keras->tf and keras->plaidml tho.

**Comment by SleepProgger** [comment]
I added a temporary fix for this by injecting `int const_func __attribute__((overloadable)) floor(int x){return x;}` into each generated kernel which "solved" this problem.
*I used LD_PRELOAD with https://gist.github.com/SleepProgger/205196b91190fd2ea9e87500d8f5cf7e because i was too lazy to recompile plaidml*

Now i run into the following error:
```
Traceback (most recent call last):
  File "test_ngrapg_tf.py", line 39, in <module>
    model.fit(x_train, y_train, epochs=5)
  File "/run/media/nope/data/home/nope/workspace/test/fs/ngraph-tf_master/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/run/media/nope/data/home/nope/workspace/test/fs/ngraph-tf_master/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 329, in model_iteration
    batch_outs = f(ins_batch)
  File "/run/media/nope/data/home/nope/workspace/test/fs/ngraph-tf_master/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/run/media/nope/data/home/nope/workspace/test/fs/ngraph-tf_master/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/run/media/nope/data/home/nope/workspace/test/fs/ngraph-tf_master/build_cmake/venv-tf-py3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Caught exception while compiling op_backend: get_shape() must be called on a node with exactly one output ()

	 [[{{node ngraph_cluster_44}}]]
```

which is the same error i get when using tensorflow.keras instead of keras with the keras backend set to tensorflow.
This seem to imply to me that tensorflow.keras -> ngraph does not lead to the invalid floor calls but keras with tensorflow backend -> ngraph seem to do.

I am going to test with an ubuntu based distro tomorrow. Lets hope that's all just some manjaro related weirdness.

**Comment by SleepProgger** [comment]
With the current ngraph i can't reproduce this specific error anymore.
Still having problems, but as much changed on ngraphs and ngraph-bridge side i am going to close this issue.
