### ISSUE TITLE
Error running StyleGAN-Keras

### ISSUE THREAD

**Issue by borderlineinteractive** [plaidml/plaidml#357]
Hi, I tried the StyleGAN-Keras repo on a Mac using Python3 and Plaidml as backend, but get the following error:

(plaidml_stylegan6) Users-iMac:StyleGAN-Keras user$ python stylegan.py
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "metal_amd_radeon_pro_580.0"
Traceback (most recent call last):
File "stylegan.py", line 509, in 
model = WGAN(lr = 0.0003, silent = False)
File "stylegan.py", line 343, in init
self.DisModel = self.GAN.DisModel()
File "stylegan.py", line 332, in DisModel
self.DM.compile(optimizer=Adam(self.LR, beta_1 = 0, beta_2 = 0.99, decay = 0.00001), loss=['mse', 'mse', partial_gp_loss])
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/keras/engine/training.py", line 342, in compile
sample_weight, mask)
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/keras/engine/training_utils.py", line 404, in weighted
score_array = fn(y_true, y_pred)
File "stylegan.py", line 109, in gradient_penalty_loss
axis=np.arange(1, len(gradients_sqr.shape)))
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/keras/backend.py", line 1638, in sum
floatx=ptile.convert_np_dtype_to_pml(floatx()))
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/op.py", line 2556, in summation
return Summation.function(value, axes=axes, keepdims=keepdims, floatx=floatx)
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/tile.py", line 255, in function
operation = cls(*args, **kwargs)
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/op.py", line 2539, in init
dims, _, subs = tile.compute_aggregation_axes(value.shape.dims, axes, keepdims)
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/tile.py", line 1353, in compute_aggregation_axes
reduce_indices = [dest_indices[i] for i in axes]
File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/tile.py", line 1353, in 
reduce_indices = [dest_indices[i] for i in axes]
TypeError: only integer scalar arrays can be converted to a scalar index

Any idea what might be going on?

This is the link to the StyleGAN-Keras repo:

https://github.com/manicman1999/StyleGAN-Keras

Thanks a lot!

**Comment by dgkutnic** [comment]
I've reproduced this error on my end and am working on a minimal reproduction. I'll let you know when I have more info!

**Comment by dgkutnic** [comment]
Hi @borderlineinteractive! I've identified our bug.

In the gradient penalty loss calculations, we have the following line:
```python3
gradient_penalty = K.sum(gradients_sqr, axis=np.arange(1, len(gradients_sqr.shape)))
```

It turns out that our backend for `K.sum` (or pretty much any Keras backend function that has the `axis` parameter) only accepts list inputs to `axis` at the moment. We'll modify the backend to also accept an `ndarray` for `axis` to fix this case. I'm targeting this fix for our next release (0.6.2, est. 7/12).

In the meantime, if you'd like a workaround, you can modify that line as follows:
```python3
gradient_penalty = K.sum(gradients_sqr, axis=list(range(1, len(gradients_sqr.shape))))
```

**Comment by dgkutnic** [comment]
FYI: I've made the changes and they are pending verification. The 0.6.2 release got pushed up to today, so these will be in the 0.6.3 release (still expected to be 7/12 as noted).

**Comment by borderlineinteractive** [comment]
Thank you very much for offering this fix. Unfortunately, this brings up another error:

(plaidml_stylegan6) Users-iMac:StyleGAN-Keras user$ python stylegan.py
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "metal_amd_radeon_pro_580.0"
stylegan.py:352: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  self.lastblip = time.clock()
/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/keras/engine/training.py:490: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
Traceback (most recent call last):
  File "stylegan.py", line 518, in <module>
    model.train()
  File "stylegan.py", line 374, in train
    a = self.train_dis()
  File "stylegan.py", line 401, in train_dis
    d_loss = self.DisModel.train_on_batch(train_data, [self.ones, self.nones, self.ones])
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/keras/engine/training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/keras/engine/training.py", line 519, in _make_train_function
    **self._function_kwargs)
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/keras/backend.py", line 745, in function
    return _Function(inputs, outputs, updates, name)
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/keras/backend.py", line 147, in __init__
    name=name)
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/tile.py", line 1053, in compose
    bindings.insert(op, op.bind(bindings))
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/op.py", line 1732, in bind
    output_vars = plaidml.gradients(loss_var, input_vars)
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/__init__.py", line 1475, in gradients
    return [Var(_lib().plaidml_compute_grad_wrt(g, var)) for var in variables]
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/__init__.py", line 1475, in <listcomp>
    return [Var(_lib().plaidml_compute_grad_wrt(g, var)) for var in variables]
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "/Users/user/plaidml_stylegan6/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Invalid derivative: unknown function simple_reduce

This looks similar to a the issue:

#223 

I will look for the next release, in which this might also be fixed.

Thank you very much

**Comment by brianretford** [comment]
Can you update to 0.6.3 and see if this issue has been resolved?

**Comment by borderlineinteractive** [comment]
I just updated to 0.6.3 but still get the same error (i.e.: "plaidml.exceptions.Unknown: Invalid derivative: unknown function simple_reduce")

Thank you very much

**Comment by IIIBlueberry** [comment]
Any update? still does not working for me i get this error : AttributeError: 'functools.partial' object has no attribute '__name__'
my loss function 
def r1_gp(y_true, y_pred, samples):
        gradients = K.gradients(y_pred, samples)[0]
        gradients = K.square(gradients)
        gradients = K.sum(gradients, axis=[1, 2, 3])
        return K.mean(gradients)

**Comment by dgkutnic** [comment]
Hi @IIIBlueberry and @borderlineinteractive,
Thanks for reporting the issue with `simple_reduce` and your overall patience here. I'll have someone on my team debug this today.

**Comment by FireFox1616** [comment]
@dgkutnic is there any news about that?

**Comment by blwhite7** [comment]
@dgkutnic I'm also eagerly awaiting a solution! Thank you for your work in getting the issue resolved.

**Comment by WLeeeee** [comment]
Hi 

Thanks for your patience. The bug occurs when calculating the gradients of inputs.
We are working on resolving the issue.

Thanks

**Comment by blwhite7** [comment]
Hi @WLeeeee, I see this was tagged as 0.6.3, but this release has passed. Is this issue still on your radar?

**Comment by xavierign** [comment]
Same issue here. Any updates on this? thanks for your help

**Comment by lucascamel** [comment]
@WenChuanLee 
Any update of this:
"Unknown: Invalid derivative: unknown function simple_reduce"
Thanks.

**Comment by minxdragon** [comment]
Hi all, is there an update to this? I have the same error as well.
