### ISSUE TITLE
'Attribute Error' when I calculate perceptual loss with VGG19 net

### ISSUE THREAD

**Issue by dfernr09** [plaidml/plaidml#379]
Hi, 
I am using a SRGAN net that use a VGG19 net to calculate the perceptual loss, this is the code:

def vgg_loss(self, y_true, y_pred):
       
       vgg19 = kapp.VGG19(include_top=False, weights='imagenet', input_shape=self.image_shape)
        vgg19.trainable = False
        #Make trainable as False
        for l in vgg19.layers:
            l.trainable = False
        model = Model(inputs=vgg19.input, outputs=vgg19.get_layer('block5_conv4').output)
        model.trainable = False
        return K.mean(K.square(model(y_true) - model(y_pred)))

The error is in the return statement, i try to divide it and i saw that it appears in this statement: 'model(y_true)' but not in the statement 'model(y_pred)'
The structure of these two 'tensors' is this:

- model(y_true): activation_1_target Placeholder FLOAT32(<tile.Value SymbolicDim UINT64()>, <tile.Value SymbolicDim UINT64()>, <tile.Value SymbolicDim UINT64()>, <tile.Value SymbolicDim UINT64()>) --> This show the error

- model(y_pred): Tanh FLOAT32(<tile.Value Operation UINT64()>, 32, 32, 3)

And the error:

Traceback (most recent call last):
  File "train.py", line 137, in <module>
    train(values.epochs, values.batch_size, values.input_dir, values.output_dir, values.model_save_dir, values.number_of_images, values.train_test_ratio)
  File "train.py", line 57, in train
    generator.compile(loss=loss.vgg_loss, optimizer=optimizer)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\keras\engine\training.py", line 342, in compile
    sample_weight, mask)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\keras\engine\training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "C:\Users\Usuario\Desktop\TFG\Utils_model.py", line 43, in vgg_loss
    return K.mean(K.square(model(y_true) - model(y_pred)))
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\keras\engine\network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\keras\engine\network.py", line 781, in run_internal_graph
    [x._uses_learning_phase for x in computed_tensors])
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\keras\engine\network.py", line 781, in <listcomp>
    [x._uses_learning_phase for x in computed_tensors])
AttributeError: 'Value' object has no attribute `_uses_learning_phase`

**Comment by dgkutnic** [comment]
Hi @dfernr09,
Thanks for providing us with this code sample! I've reproduced the error that you are hitting and have confirmed that this is a bug in our backend implementation.
The bug is occurring because we aren't setting the attribute `_uses_learning_phase` in some cases. We'll make sure that `_uses_learning_phase` is set in all cases and has a default value defined.
