### ISSUE TITLE
Neural Style Transfer from the Keras Examples

### ISSUE THREAD

**Issue by LukeB42** [plaidml/plaidml#52]
Not sure if this has already been fixed. Figured it'd be worth opening an issue in case no one's encountered this bug / error:
```
$ python2.7 neural_style_transfer.py ~/Downloads/cat.jpg ~/Downloads/starry_night.jpg ../output/style_transfer_
INFO:plaidml:Initializing device [...]"
INFO:plaidml:Opening device "[...]"
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg19_weights_tf_dim_ordering_tf_kernels_notop.h5
79781888/80134624 [============================>.] - ETA: 0sModel loaded.
Start of iteration 0
INFO:plaidml:Analyzing Ops: 40 of 487 operations complete
INFO:plaidml:Analyzing Ops: 74 of 487 operations complete
INFO:plaidml:Analyzing Ops: 108 of 487 operations complete
INFO:plaidml:Analyzing Ops: 147 of 487 operations complete
Traceback (most recent call last):
  File "neural_style_transfer.py", line 285, in <module>
    fprime=evaluator.grads, maxfun=20)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "neural_style_transfer.py", line 263, in loss
    loss_value, grad_values = eval_loss_and_grads(x)
  File "neural_style_transfer.py", line 239, in eval_loss_and_grads
    outs = f_outputs([x])
  File "/usr/local/lib/python2.7/dist-packages/plaidml/keras/backend.py", line 913, in __call__
    self._invoker.invoke()
  File "/usr/local/lib/python2.7/dist-packages/plaidml/__init__.py", line 1317, in invoke
    return Invocation(self._ctx, self)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/__init__.py", line 1323, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/usr/local/lib/python2.7/dist-packages/plaidml/__init__.py", line 667, in _check_err
    self.raise_last_status()
  File "/usr/local/lib/python2.7/dist-packages/plaidml/library.py", line 136, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Invalid reshape
```

**Comment by jbruestle** [comment]
I've tracked down the source of this issue, which appear to be related to our limited implementation for __setitem__ as well as a few other related problems.  I'll be working on this code this week, so hopefully I will have a fix for you soon.  Thanks for reporting!

**Comment by jbruestle** [comment]
I fixed the underlying operations for Neural Style Transfer and it compiles as of the latest update to master and the latest pips (0.1.2).  Please give them a try and let me know if it fixes your issue.

**Comment by jbruestle** [comment]
I'm closing this ticket since it's fixed in my repo and no response from reporter.
