### ISSUE TITLE
[bug] keras.backend.function([model.layers[0].input], [outputlist]) works weirdly

### ISSUE THREAD

**Issue by jongwooc** [plaidml/plaidml#550]
I used this code to get the outputs of all the layers in a single model.

However, when I use keras.backend.function after dropout layer like this:

keras.backend.function([model.layers[0].input], [model.any_layer_after_dropout.output]) 

plaid reports list of digraph Tiles and make plaidml.exceptions.Unknown: Binding missing placeholder error.

The next is the Traceback :

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plaidml/keras/backend.py", line 741, in function
    return _Function(inputs, outputs, updates, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plaidml/keras/backend.py", line 147, in __init__
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plaidml/tile.py", line 1064, in compose
    composer.add_output(output_name, binding)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plaidml/__init__.py", line 1409, in add_output
    _lib().plaidml_add_composer_output(self, name.encode(), val)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plaidml/__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Binding missing placeholder

Thank you for PlaidML!

**Comment by dgkutnic** [comment]
Hi @jongwooc,

`keras.backend.function` is a function that behaves in a wide variety of ways. To help us with the debug process, is there anything from the following list that you could provide us with?

* A minimal reproduction of your network/summary of the layers you're using before the Dropout layer(s)
* Does the code work with the TensorFlow backend? 
* Verbose logging before the error occurs (you can enable this by setting the environment variable `PLAIDML_VERBOSE` -- try setting it at level 3).

**Comment by jongwooc** [comment]
Hi, @dgkutnic,

Sorry for the late reply.

I was using PlaidML on zhixuhao/unet. (https://github.com/zhixuhao/unet)

However, as zhixuhao/unet does not have inference only function, I added test only code:

#test only code
def test_only():
    model = load_model('unet_membrane.hdf5')
    model.summary()
    img = io.imread("./data/membrane/test/0.png",as_gray = True)
    img = img / 255
    img = trans.resize(img,(256,256))
    img = np.reshape(img,(1,)+img.shape)
    img = np.expand_dims(img, -1)

    get_output_of_every_layers = keras.backend.function([model.layers[0].input], [model.layers[-1].output])
    temp_item_list = get_output_of_every_layers([img])
    results = temp_item_list[0]
    saveResult("./",results)


The two main difference between PlaidML and Tensorflow back end is these:

1. keras.backend.function([model.layers[0].input], [model.layers[-1].output])
temp_item_list = get_output_of_every_layers([img])
Tensorflow backend requires data format of img same with model.layers[0].input, which means when model.layers[0].input is single Item, img is OK with single img, but when model.layers[0].input is list, img should be list, too.
On the PlaidML backend, model.layers[0].input has to be list only. PlaidML does not accept a single item as input for the backend. function

2. When the two input items are matching, the code itself works fine with Tensorflow backend either way, but PlaidML backend returns error until the layer number of model.layers[-1].output is smaller than any dropout layer. (Which means, using the keras.backend fuction without dropout layer)

Although "set PLAIDML_VERBOSE=3"  does not change the log, I will add the full log here.

Total params: 31,031,685
Trainable params: 31,031,685
Non-trainable params: 0
__________________________________________________________________________________________________
digraph Tile {
  n1 [label="I0\ninput_1\ Placeholder\ FLOAT32\(<tile\.Value\ SymbolicDim\ UINT64\(\)>,\ 256,\ 256,\ 1\)" shape=circle];
  n2 [label="O0\nSigmoid\ FLOAT32\(<tile\.Value\ SymbolicDim\ UINT64\(\)>,\ 256,\ 256,\ 1\)" shape=doublecircle];
  n3 [label="dropout_1/tensor_variable_1\ Tensor\ UINT32\(3,\ 2048\)" shape=circle];
  n4 [label="PrngState\ UINT32\(3,\ 2048\)" shape=circle];
  n4 -> n3 [style=dotted];
  n5 [label="dropout_2/tensor_variable_1\ Tensor\ UINT32\(3,\ 2048\)" shape=circle];
  n6 [label="PrngState\ UINT32\(3,\ 2048\)" shape=circle];
  n6 -> n5 [style=dotted];
  n7 [label="PrngState" shape=oval];
  n8 [label="PrngStep" shape=box];
  n8 -> n7 [label="I"];
  n7 -> n6 [label="O"];
  n9 [label="PrngStep" shape=oval];
  n5 -> n9 [label="I"];
  n10 [label="Relu" shape=box];
  n10 -> n9 [label="X"];
  n9 -> n8 [label="O"];
  n11 [label="Relu" shape=oval];
  n12 [label="Add" shape=box];
  n12 -> n11 [label="X"];
  n13 [label="<unnamed>\ Real" shape=box];
  n13 -> n11 [label="Alpha"];
  n11 -> n10 [label="Y"];
  n14 [label="Add" shape=oval];
  n15 [label="conv2d_10" shape=box];
  n15 -> n14 [label="L"];
  n16 [label="conv2d_10/bias\ Tensor" shape=box];
  n16 -> n14 [label="R"];
  n14 -> n12 [label="O"];
  n17 [label="conv2d_10" shape=oval];
  n18 [label="Relu" shape=box];
  n18 -> n17 [label="I"];
  n19 [label="conv2d_10/kernel\ Tensor" shape=box];
  n19 -> n17 [label="K"];
  n17 -> n15 [label="O"];
  n20 [label="Relu" shape=oval];
  n21 [label="Add" shape=box];
  n21 -> n20 [label="X"];
  n22 [label="<unnamed>\ Real" shape=box];
  n22 -> n20 [label="Alpha"];
  n20 -> n18 [label="Y"];
  n23 [label="Add" shape=oval];
  n24 [label="conv2d_9" shape=box];
  n24 -> n23 [label="L"];
  n25 [label="conv2d_9/bias\ Tensor" shape=box];
  n25 -> n23 [label="R"];
  n23 -> n21 [label="O"];
  n26 [label="conv2d_9" shape=oval];
  n27 [label="max_pooling2d_4" shape=box];
  n27 -> n26 [label="I"];
  n28 [label="conv2d_9/kernel\ Tensor" shape=box];
  n28 -> n26 [label="K"];
  n26 -> n24 [label="O"];
  n29 [label="max_pooling2d_4" shape=oval];
  n30 [label="Switch" shape=box];
  n30 -> n29 [label="I"];
  n29 -> n27 [label="O"];
  n31 [label="Switch" shape=oval];
  n32 [label="dropout_1/placeholder_1\ Placeholder" shape=box];
  n32 -> n31 [label="C"];
  n33 [label="PrngValue" shape=box];
  n33 -> n31 [label="T"];
  n34 [label="Relu" shape=box];
  n34 -> n31 [label="E"];
  n31 -> n30 [label="O"];
  n35 [label="Relu" shape=oval];
  n36 [label="Add" shape=box];
  n36 -> n35 [label="X"];
  n37 [label="<unnamed>\ Real" shape=box];
  n37 -> n35 [label="Alpha"];
  n35 -> n34 [label="Y"];
  n38 [label="Add" shape=oval];
  n39 [label="conv2d_8" shape=box];
  n39 -> n38 [label="L"];
  n40 [label="conv2d_8/bias\ Tensor" shape=box];
  n40 -> n38 [label="R"];
  n38 -> n36 [label="O"];
  n41 [label="conv2d_8" shape=oval];
  n42 [label="Relu" shape=box];
  n42 -> n41 [label="I"];
  n43 [label="conv2d_8/kernel\ Tensor" shape=box];
  n43 -> n41 [label="K"];
  n41 -> n39 [label="O"];
  n44 [label="Relu" shape=oval];
  n45 [label="Add" shape=box];
  n45 -> n44 [label="X"];
  n46 [label="<unnamed>\ Real" shape=box];
  n46 -> n44 [label="Alpha"];
  n44 -> n42 [label="Y"];
  n47 [label="Add" shape=oval];
  n48 [label="conv2d_7" shape=box];
  n48 -> n47 [label="L"];
  n49 [label="conv2d_7/bias\ Tensor" shape=box];
  n49 -> n47 [label="R"];
  n47 -> n45 [label="O"];
  n50 [label="conv2d_7" shape=oval];
  n51 [label="max_pooling2d_3" shape=box];
  n51 -> n50 [label="I"];
  n52 [label="conv2d_7/kernel\ Tensor" shape=box];
  n52 -> n50 [label="K"];
  n50 -> n48 [label="O"];
  n53 [label="max_pooling2d_3" shape=oval];
  n54 [label="Relu" shape=box];
  n54 -> n53 [label="I"];
  n53 -> n51 [label="O"];
  n55 [label="Relu" shape=oval];
  n56 [label="Add" shape=box];
  n56 -> n55 [label="X"];
  n57 [label="<unnamed>\ Real" shape=box];
  n57 -> n55 [label="Alpha"];
  n55 -> n54 [label="Y"];
  n58 [label="Add" shape=oval];
  n59 [label="conv2d_6" shape=box];
  n59 -> n58 [label="L"];
  n60 [label="conv2d_6/bias\ Tensor" shape=box];
  n60 -> n58 [label="R"];
  n58 -> n56 [label="O"];
  n61 [label="conv2d_6" shape=oval];
  n62 [label="Relu" shape=box];
  n62 -> n61 [label="I"];
  n63 [label="conv2d_6/kernel\ Tensor" shape=box];
  n63 -> n61 [label="K"];
  n61 -> n59 [label="O"];
  n64 [label="Relu" shape=oval];
  n65 [label="Add" shape=box];
  n65 -> n64 [label="X"];
  n66 [label="<unnamed>\ Real" shape=box];
  n66 -> n64 [label="Alpha"];
  n64 -> n62 [label="Y"];
  n67 [label="Add" shape=oval];
  n68 [label="conv2d_5" shape=box];
  n68 -> n67 [label="L"];
  n69 [label="conv2d_5/bias\ Tensor" shape=box];
  n69 -> n67 [label="R"];
  n67 -> n65 [label="O"];
  n70 [label="conv2d_5" shape=oval];
  n71 [label="max_pooling2d_2" shape=box];
  n71 -> n70 [label="I"];
  n72 [label="conv2d_5/kernel\ Tensor" shape=box];
  n72 -> n70 [label="K"];
  n70 -> n68 [label="O"];
  n73 [label="max_pooling2d_2" shape=oval];
  n74 [label="Relu" shape=box];
  n74 -> n73 [label="I"];
  n73 -> n71 [label="O"];
  n75 [label="Relu" shape=oval];
  n76 [label="Add" shape=box];
  n76 -> n75 [label="X"];
  n77 [label="<unnamed>\ Real" shape=box];
  n77 -> n75 [label="Alpha"];
  n75 -> n74 [label="Y"];
  n78 [label="Add" shape=oval];
  n79 [label="conv2d_4" shape=box];
  n79 -> n78 [label="L"];
  n80 [label="conv2d_4/bias\ Tensor" shape=box];
  n80 -> n78 [label="R"];
  n78 -> n76 [label="O"];
  n81 [label="conv2d_4" shape=oval];
  n82 [label="Relu" shape=box];
  n82 -> n81 [label="I"];
  n83 [label="conv2d_4/kernel\ Tensor" shape=box];
  n83 -> n81 [label="K"];
  n81 -> n79 [label="O"];
  n84 [label="Relu" shape=oval];
  n85 [label="Add" shape=box];
  n85 -> n84 [label="X"];
  n86 [label="<unnamed>\ Real" shape=box];
  n86 -> n84 [label="Alpha"];
  n84 -> n82 [label="Y"];
  n87 [label="Add" shape=oval];
  n88 [label="conv2d_3" shape=box];
  n88 -> n87 [label="L"];
  n89 [label="conv2d_3/bias\ Tensor" shape=box];
  n89 -> n87 [label="R"];
  n87 -> n85 [label="O"];
  n90 [label="conv2d_3" shape=oval];
  n91 [label="max_pooling2d_1" shape=box];
  n91 -> n90 [label="I"];
  n92 [label="conv2d_3/kernel\ Tensor" shape=box];
  n92 -> n90 [label="K"];
  n90 -> n88 [label="O"];
  n93 [label="max_pooling2d_1" shape=oval];
  n94 [label="Relu" shape=box];
  n94 -> n93 [label="I"];
  n93 -> n91 [label="O"];
  n95 [label="Relu" shape=oval];
  n96 [label="Add" shape=box];
  n96 -> n95 [label="X"];
  n97 [label="<unnamed>\ Real" shape=box];
  n97 -> n95 [label="Alpha"];
  n95 -> n94 [label="Y"];
  n98 [label="Add" shape=oval];
  n99 [label="conv2d_2" shape=box];
  n99 -> n98 [label="L"];
  n100 [label="conv2d_2/bias\ Tensor" shape=box];
  n100 -> n98 [label="R"];
  n98 -> n96 [label="O"];
  n101 [label="conv2d_2" shape=oval];
  n102 [label="Relu" shape=box];
  n102 -> n101 [label="I"];
  n103 [label="conv2d_2/kernel\ Tensor" shape=box];
  n103 -> n101 [label="K"];
  n101 -> n99 [label="O"];
  n104 [label="Relu" shape=oval];
  n105 [label="Add" shape=box];
  n105 -> n104 [label="X"];
  n106 [label="<unnamed>\ Real" shape=box];
  n106 -> n104 [label="Alpha"];
  n104 -> n102 [label="Y"];
  n107 [label="Add" shape=oval];
  n108 [label="conv2d_1" shape=box];
  n108 -> n107 [label="L"];
  n109 [label="conv2d_1/bias\ Tensor" shape=box];
  n109 -> n107 [label="R"];
  n107 -> n105 [label="O"];
  n110 [label="conv2d_1" shape=oval];
  n1 -> n110 [label="I"];
  n111 [label="conv2d_1/kernel\ Tensor" shape=box];
  n111 -> n110 [label="K"];
  n110 -> n108 [label="O"];
  n112 [label="PrngValue" shape=oval];
  n113 [label="PrngStep" shape=box];
  n113 -> n112 [label="I"];
  n34 -> n112 [label="X"];
  n114 [label="<unnamed>\ Real" shape=box];
  n114 -> n112 [label="L"];
  n112 -> n33 [label="O"];
  n115 [label="PrngStep" shape=oval];
  n3 -> n115 [label="I"];
  n34 -> n115 [label="X"];
  n115 -> n113 [label="O"];
  n116 [label="PrngState" shape=oval];
  n113 -> n116 [label="I"];
  n116 -> n4 [label="O"];
  n117 [label="Sigmoid" shape=oval];
  n118 [label="Add" shape=box];
  n118 -> n117 [label="I"];
  n117 -> n2 [label="O"];
  n119 [label="Add" shape=oval];
  n120 [label="conv2d_24" shape=box];
  n120 -> n119 [label="L"];
  n121 [label="conv2d_24/bias\ Tensor" shape=box];
  n121 -> n119 [label="R"];
  n119 -> n118 [label="O"];
  n122 [label="conv2d_24" shape=oval];
  n123 [label="Relu" shape=box];
  n123 -> n122 [label="I"];
  n124 [label="conv2d_24/kernel\ Tensor" shape=box];
  n124 -> n122 [label="K"];
  n122 -> n120 [label="O"];
  n125 [label="Relu" shape=oval];
  n126 [label="Add" shape=box];
  n126 -> n125 [label="X"];
  n127 [label="<unnamed>\ Real" shape=box];
  n127 -> n125 [label="Alpha"];
  n125 -> n123 [label="Y"];
  n128 [label="Add" shape=oval];
  n129 [label="conv2d_23" shape=box];
  n129 -> n128 [label="L"];
  n130 [label="conv2d_23/bias\ Tensor" shape=box];
  n130 -> n128 [label="R"];
  n128 -> n126 [label="O"];
  n131 [label="conv2d_23" shape=oval];
  n132 [label="Relu" shape=box];
  n132 -> n131 [label="I"];
  n133 [label="conv2d_23/kernel\ Tensor" shape=box];
  n133 -> n131 [label="K"];
  n131 -> n129 [label="O"];
  n134 [label="Relu" shape=oval];
  n135 [label="Add" shape=box];
  n135 -> n134 [label="X"];
  n136 [label="<unnamed>\ Real" shape=box];
  n136 -> n134 [label="Alpha"];
  n134 -> n132 [label="Y"];
  n137 [label="Add" shape=oval];
  n138 [label="conv2d_22" shape=box];
  n138 -> n137 [label="L"];
  n139 [label="conv2d_22/bias\ Tensor" shape=box];
  n139 -> n137 [label="R"];
  n137 -> n135 [label="O"];
  n140 [label="conv2d_22" shape=oval];
  n141 [label="Relu" shape=box];
  n141 -> n140 [label="I"];
  n142 [label="conv2d_22/kernel\ Tensor" shape=box];
  n142 -> n140 [label="K"];
  n140 -> n138 [label="O"];
  n143 [label="Relu" shape=oval];
  n144 [label="Add" shape=box];
  n144 -> n143 [label="X"];
  n145 [label="<unnamed>\ Real" shape=box];
  n145 -> n143 [label="Alpha"];
  n143 -> n141 [label="Y"];
  n146 [label="Add" shape=oval];
  n147 [label="conv2d_21" shape=box];
  n147 -> n146 [label="L"];
  n148 [label="conv2d_21/bias\ Tensor" shape=box];
  n148 -> n146 [label="R"];
  n146 -> n144 [label="O"];
  n149 [label="conv2d_21" shape=oval];
  n150 [label="Concatenate" shape=box];
  n150 -> n149 [label="I"];
  n151 [label="conv2d_21/kernel\ Tensor" shape=box];
  n151 -> n149 [label="K"];
  n149 -> n147 [label="O"];
  n152 [label="Concatenate" shape=oval];
  n94 -> n152 [label="I0"];
  n153 [label="Relu" shape=box];
  n153 -> n152 [label="I1"];
  n152 -> n150 [label="O"];
  n154 [label="Relu" shape=oval];
  n155 [label="Add" shape=box];
  n155 -> n154 [label="X"];
  n156 [label="<unnamed>\ Real" shape=box];
  n156 -> n154 [label="Alpha"];
  n154 -> n153 [label="Y"];
  n157 [label="Add" shape=oval];
  n158 [label="conv2d_20" shape=box];
  n158 -> n157 [label="L"];
  n159 [label="conv2d_20/bias\ Tensor" shape=box];
  n159 -> n157 [label="R"];
  n157 -> n155 [label="O"];
  n160 [label="conv2d_20" shape=oval];
  n161 [label="RepeatElements" shape=box];
  n161 -> n160 [label="I"];
  n162 [label="conv2d_20/kernel\ Tensor" shape=box];
  n162 -> n160 [label="K"];
  n160 -> n158 [label="O"];
  n163 [label="RepeatElements" shape=oval];
  n164 [label="RepeatElements" shape=box];
  n164 -> n163 [label="I"];
  n163 -> n161 [label="O"];
  n165 [label="RepeatElements" shape=oval];
  n166 [label="Relu" shape=box];
  n166 -> n165 [label="I"];
  n165 -> n164 [label="O"];
  n167 [label="Relu" shape=oval];
  n168 [label="Add" shape=box];
  n168 -> n167 [label="X"];
  n169 [label="<unnamed>\ Real" shape=box];
  n169 -> n167 [label="Alpha"];
  n167 -> n166 [label="Y"];
  n170 [label="Add" shape=oval];
  n171 [label="conv2d_19" shape=box];
  n171 -> n170 [label="L"];
  n172 [label="conv2d_19/bias\ Tensor" shape=box];
  n172 -> n170 [label="R"];
  n170 -> n168 [label="O"];
  n173 [label="conv2d_19" shape=oval];
  n174 [label="Relu" shape=box];
  n174 -> n173 [label="I"];
  n175 [label="conv2d_19/kernel\ Tensor" shape=box];
  n175 -> n173 [label="K"];
  n173 -> n171 [label="O"];
  n176 [label="Relu" shape=oval];
  n177 [label="Add" shape=box];
  n177 -> n176 [label="X"];
  n178 [label="<unnamed>\ Real" shape=box];
  n178 -> n176 [label="Alpha"];
  n176 -> n174 [label="Y"];
  n179 [label="Add" shape=oval];
  n180 [label="conv2d_18" shape=box];
  n180 -> n179 [label="L"];
  n181 [label="conv2d_18/bias\ Tensor" shape=box];
  n181 -> n179 [label="R"];
  n179 -> n177 [label="O"];
  n182 [label="conv2d_18" shape=oval];
  n183 [label="Concatenate" shape=box];
  n183 -> n182 [label="I"];
  n184 [label="conv2d_18/kernel\ Tensor" shape=box];
  n184 -> n182 [label="K"];
  n182 -> n180 [label="O"];
  n185 [label="Concatenate" shape=oval];
  n74 -> n185 [label="I0"];
  n186 [label="Relu" shape=box];
  n186 -> n185 [label="I1"];
  n185 -> n183 [label="O"];
  n187 [label="Relu" shape=oval];
  n188 [label="Add" shape=box];
  n188 -> n187 [label="X"];
  n189 [label="<unnamed>\ Real" shape=box];
  n189 -> n187 [label="Alpha"];
  n187 -> n186 [label="Y"];
  n190 [label="Add" shape=oval];
  n191 [label="conv2d_17" shape=box];
  n191 -> n190 [label="L"];
  n192 [label="conv2d_17/bias\ Tensor" shape=box];
  n192 -> n190 [label="R"];
  n190 -> n188 [label="O"];
  n193 [label="conv2d_17" shape=oval];
  n194 [label="RepeatElements" shape=box];
  n194 -> n193 [label="I"];
  n195 [label="conv2d_17/kernel\ Tensor" shape=box];
  n195 -> n193 [label="K"];
  n193 -> n191 [label="O"];
  n196 [label="RepeatElements" shape=oval];
  n197 [label="RepeatElements" shape=box];
  n197 -> n196 [label="I"];
  n196 -> n194 [label="O"];
  n198 [label="RepeatElements" shape=oval];
  n199 [label="Relu" shape=box];
  n199 -> n198 [label="I"];
  n198 -> n197 [label="O"];
  n200 [label="Relu" shape=oval];
  n201 [label="Add" shape=box];
  n201 -> n200 [label="X"];
  n202 [label="<unnamed>\ Real" shape=box];
  n202 -> n200 [label="Alpha"];
  n200 -> n199 [label="Y"];
  n203 [label="Add" shape=oval];
  n204 [label="conv2d_16" shape=box];
  n204 -> n203 [label="L"];
  n205 [label="conv2d_16/bias\ Tensor" shape=box];
  n205 -> n203 [label="R"];
  n203 -> n201 [label="O"];
  n206 [label="conv2d_16" shape=oval];
  n207 [label="Relu" shape=box];
  n207 -> n206 [label="I"];
  n208 [label="conv2d_16/kernel\ Tensor" shape=box];
  n208 -> n206 [label="K"];
  n206 -> n204 [label="O"];
  n209 [label="Relu" shape=oval];
  n210 [label="Add" shape=box];
  n210 -> n209 [label="X"];
  n211 [label="<unnamed>\ Real" shape=box];
  n211 -> n209 [label="Alpha"];
  n209 -> n207 [label="Y"];
  n212 [label="Add" shape=oval];
  n213 [label="conv2d_15" shape=box];
  n213 -> n212 [label="L"];
  n214 [label="conv2d_15/bias\ Tensor" shape=box];
  n214 -> n212 [label="R"];
  n212 -> n210 [label="O"];
  n215 [label="conv2d_15" shape=oval];
  n216 [label="Concatenate" shape=box];
  n216 -> n215 [label="I"];
  n217 [label="conv2d_15/kernel\ Tensor" shape=box];
  n217 -> n215 [label="K"];
  n215 -> n213 [label="O"];
  n218 [label="Concatenate" shape=oval];
  n54 -> n218 [label="I0"];
  n219 [label="Relu" shape=box];
  n219 -> n218 [label="I1"];
  n218 -> n216 [label="O"];
  n220 [label="Relu" shape=oval];
  n221 [label="Add" shape=box];
  n221 -> n220 [label="X"];
  n222 [label="<unnamed>\ Real" shape=box];
  n222 -> n220 [label="Alpha"];
  n220 -> n219 [label="Y"];
  n223 [label="Add" shape=oval];
  n224 [label="conv2d_14" shape=box];
  n224 -> n223 [label="L"];
  n225 [label="conv2d_14/bias\ Tensor" shape=box];
  n225 -> n223 [label="R"];
  n223 -> n221 [label="O"];
  n226 [label="conv2d_14" shape=oval];
  n227 [label="RepeatElements" shape=box];
  n227 -> n226 [label="I"];
  n228 [label="conv2d_14/kernel\ Tensor" shape=box];
  n228 -> n226 [label="K"];
  n226 -> n224 [label="O"];
  n229 [label="RepeatElements" shape=oval];
  n230 [label="RepeatElements" shape=box];
  n230 -> n229 [label="I"];
  n229 -> n227 [label="O"];
  n231 [label="RepeatElements" shape=oval];
  n232 [label="Relu" shape=box];
  n232 -> n231 [label="I"];
  n231 -> n230 [label="O"];
  n233 [label="Relu" shape=oval];
  n234 [label="Add" shape=box];
  n234 -> n233 [label="X"];
  n235 [label="<unnamed>\ Real" shape=box];
  n235 -> n233 [label="Alpha"];
  n233 -> n232 [label="Y"];
  n236 [label="Add" shape=oval];
  n237 [label="conv2d_13" shape=box];
  n237 -> n236 [label="L"];
  n238 [label="conv2d_13/bias\ Tensor" shape=box];
  n238 -> n236 [label="R"];
  n236 -> n234 [label="O"];
  n239 [label="conv2d_13" shape=oval];
  n240 [label="Relu" shape=box];
  n240 -> n239 [label="I"];
  n241 [label="conv2d_13/kernel\ Tensor" shape=box];
  n241 -> n239 [label="K"];
  n239 -> n237 [label="O"];
  n242 [label="Relu" shape=oval];
  n243 [label="Add" shape=box];
  n243 -> n242 [label="X"];
  n244 [label="<unnamed>\ Real" shape=box];
  n244 -> n242 [label="Alpha"];
  n242 -> n240 [label="Y"];
  n245 [label="Add" shape=oval];
  n246 [label="conv2d_12" shape=box];
  n246 -> n245 [label="L"];
  n247 [label="conv2d_12/bias\ Tensor" shape=box];
  n247 -> n245 [label="R"];
  n245 -> n243 [label="O"];
  n248 [label="conv2d_12" shape=oval];
  n249 [label="Concatenate" shape=box];
  n249 -> n248 [label="I"];
  n250 [label="conv2d_12/kernel\ Tensor" shape=box];
  n250 -> n248 [label="K"];
  n248 -> n246 [label="O"];
  n251 [label="Concatenate" shape=oval];
  n30 -> n251 [label="I0"];
  n252 [label="Relu" shape=box];
  n252 -> n251 [label="I1"];
  n251 -> n249 [label="O"];
  n253 [label="Relu" shape=oval];
  n254 [label="Add" shape=box];
  n254 -> n253 [label="X"];
  n255 [label="<unnamed>\ Real" shape=box];
  n255 -> n253 [label="Alpha"];
  n253 -> n252 [label="Y"];
  n256 [label="Add" shape=oval];
  n257 [label="conv2d_11" shape=box];
  n257 -> n256 [label="L"];
  n258 [label="conv2d_11/bias\ Tensor" shape=box];
  n258 -> n256 [label="R"];
  n256 -> n254 [label="O"];
  n259 [label="conv2d_11" shape=oval];
  n260 [label="RepeatElements" shape=box];
  n260 -> n259 [label="I"];
  n261 [label="conv2d_11/kernel\ Tensor" shape=box];
  n261 -> n259 [label="K"];
  n259 -> n257 [label="O"];
  n262 [label="RepeatElements" shape=oval];
  n263 [label="RepeatElements" shape=box];
  n263 -> n262 [label="I"];
  n262 -> n260 [label="O"];
  n264 [label="RepeatElements" shape=oval];
  n265 [label="Switch" shape=box];
  n265 -> n264 [label="I"];
  n264 -> n263 [label="O"];
  n266 [label="Switch" shape=oval];
  n32 -> n266 [label="C"];
  n267 [label="PrngValue" shape=box];
  n267 -> n266 [label="T"];
  n10 -> n266 [label="E"];
  n266 -> n265 [label="O"];
  n268 [label="PrngValue" shape=oval];
  n8 -> n268 [label="I"];
  n10 -> n268 [label="X"];
  n269 [label="<unnamed>\ Real" shape=box];
  n269 -> n268 [label="L"];
  n268 -> n267 [label="O"];
}
Traceback (most recent call last):
  File "./main.py", line 46, in <module>
    test_only()
  File "./main.py", line 40, in test_only
    get_output_of_every_layers = keras.backend.function([model.layers[0].input], [model.layers[-1].output])
  File "/usr/local/lib/python3.7/site-packages/plaidml/keras/backend.py", line 69, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/plaidml/keras/backend.py", line 832, in function
    return _Function(inputs, outputs, updates, name)
  File "/usr/local/lib/python3.7/site-packages/plaidml/keras/backend.py", line 171, in __init__
    name=name)
  File "/usr/local/lib/python3.7/site-packages/plaidml/tile.py", line 1064, in compose
    composer.add_output(output_name, binding)
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 1410, in add_output
    _lib().plaidml_add_composer_output(self, name.encode(), val)
  File "/usr/local/lib/python3.7/site-packages/plaidml/__init__.py", line 778, in _check_err
    self.raise_last_status()
  File "/usr/local/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Binding missing placeholder

Thank you for the kind and fast reply. Hope PlaidML works well on this issue soon!

**Comment by dgkutnic** [comment]
Thanks for providing us with this info.

I'm out of the office this week but I'll reproduce this and debug it as soon as I'm back in.
