### ISSUE TITLE
plaidml-setup fails - OpenCL error: CL_INVALID_OPERATION (-59)

### ISSUE THREAD

**Issue by asteriske** [plaidml/plaidml#636]
```
$python --version
Python 3.6.8

$plaidml-setup
PlaidML Setup (0.6.4)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0
 
INFO:Verbose logging has been enabled - verbose level 4 


Default Config Devices:
   No devices.

Experimental Config File Location:
   /home/mccarthy/.pyenv/versions/3.6.8/envs/plaidenv/share/plaidml/

Experimental Config Devices:
   llvm_cpu.0 : CPU (LLVM)
   opencl_intel_hd_graphics_haswell_ultrabook_gt2_mobile.0 : Intel Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile (OpenCL)
[...]

DEBUG:plaidml:OpenCL error: CL_INVALID_OPERATION (-59)
WARNING:plaidml:Failed to build program kernel_c1_sdk_0: CL_INVALID_OPERATION

$uname -a
Linux X1 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$clinfo

Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.4 (git-419c0417)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_intel_required_subgroup_size cl_intel_media_block_io cl_intel_planar_yuv cl_khr_gl_sharing
  Platform Extensions function suffix             Intel

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
  Device Name                                     Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile
  Device Vendor                                   Intel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 beignet 1.4 (git-419c0417)
  Driver Version                                  1.4
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.4 (git-419c0417)
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               20
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
  Preferred work group size multiple              16
  Sub-group sizes (Intel)                         8, 16
  Preferred / native vector sizes                 
    char                                                16 / 8       
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 8        (n/a)
    float                                                4 / 4       
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1610612736 (1.5GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8192 (8KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4096 bytes
    Pitch alignment for 2D image buffers          1 pixels
    Max 2D image size                             8192x8192 pixels
    Max planar YUV image size                     8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max number of constant args                     8
  Max constant buffer size                        134217728 (128MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      80ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                __cl_copy_region_align4;__cl_copy_region_align16;__cl_copy_region_unalign_same_offset;__cl_copy_region_unalign_dst_offset;__cl_copy_region_unalign_src_offset;__cl_copy_buffer_rect;__cl_copy_buffer_rect_align4;__cl_copy_image_1d_to_1d;__cl_copy_image_2d_to_2d;__cl_copy_image_3d_to_2d;__cl_copy_image_2d_to_3d;__cl_copy_image_3d_to_3d;__cl_copy_image_2d_to_buffer;__cl_copy_image_2d_to_buffer_align4;__cl_copy_image_2d_to_buffer_align16;__cl_copy_image_3d_to_buffer;__cl_copy_image_3d_to_buffer_align4;__cl_copy_image_3d_to_buffer_align16;__cl_copy_buffer_to_image_2d;__cl_copy_buffer_to_image_2d_align4;__cl_copy_buffer_to_image_2d_align16;__cl_copy_buffer_to_image_3d;__cl_copy_buffer_to_image_3d_align4;__cl_copy_buffer_to_image_3d_align16;__cl_copy_image_1d_array_to_1d_array;__cl_copy_image_2d_array_to_2d_array;__cl_copy_image_2d_array_to_2d;__cl_copy_image_2d_array_to_3d;__cl_copy_image_2d_to_2d_array;__cl_copy_image_3d_to_2d_array;__cl_fill_region_unalign;__cl_fill_region_align2;__cl_fill_region_align4;__cl_fill_region_align8_2;__cl_fill_region_align8_4;__cl_fill_region_align8_8;__cl_fill_region_align8_16;__cl_fill_region_align128;__cl_fill_image_1d;__cl_fill_image_1d_array;__cl_fill_image_2d;__cl_fill_image_2d_array;__cl_fill_image_3d;
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_intel_required_subgroup_size cl_intel_media_block_io cl_intel_planar_yuv cl_khr_gl_sharing

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [Intel]
  clCreateContext(NULL, ...) [default]            Success [Intel]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
```

**Comment by dgkutnic** [comment]
Thanks for reporting! We've seen several OpenCL issues within the past few weeks, and we'll have someone look into this.

**Comment by RihardsT** [comment]
Just wanted to note, that I got the similar CL_INVALID_OPERATION error. But after installing `intel-opencl-icd` package, a new Intel GPU device showed up, which works.
I think these are all of the necessary packages:
`sudo apt install ocl-icd-opencl-dev beignet-dev clinfo intel-opencl-icd`

Below is the log of `plaidml-setup` for the failing GPU - the one that showed up having only `ocl-icd-opencl-dev beignet-dev clinfo` installed.
After that, benchmark between CPU and the GPU (with `intel-opencl-icd`):
```
$ plaidml-setup 

PlaidML Setup (0.7.0)

Thanks for using PlaidML!

The feedback we have received from our users indicates an ever-increasing need
for performance, programmability, and portability. During the past few months,
we have been restructuring PlaidML to address those needs.  To make all the
changes we need to make while supporting our current user base, all development
of PlaidML has moved to a branch — plaidml-v1. We will continue to maintain and
support the master branch of PlaidML and the stable 0.7.0 release.

Read more here: https://github.com/plaidml/plaidml 

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml/issues
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0
 

Default Config Devices:
   llvm_cpu.0 : CPU (via LLVM)

Experimental Config Devices:
   llvm_cpu.0 : CPU (via LLVM)
   opencl_intel_hd_graphics_skylake_ult_gt2.0 : Intel Intel(R) HD Graphics Skylake ULT GT2 (OpenCL)
   opencl_intel_gen9_hd_graphics_neo.0 : Intel(R) Corporation Intel(R) Gen9 HD Graphics NEO (OpenCL)

Using experimental devices can cause poor performance, crashes, and other nastiness.

Enable experimental device support? (y,n)[n]:y

Multiple devices detected (You can override by setting PLAIDML_DEVICE_IDS).
Please choose a default device:

   1 : llvm_cpu.0
   2 : opencl_intel_hd_graphics_skylake_ult_gt2.0
   3 : opencl_intel_gen9_hd_graphics_neo.0

Default device? (1,2,3)[1]:2

Selected device:
    opencl_intel_hd_graphics_skylake_ult_gt2.0

Almost done. Multiplying some matrices...
Tile code:
  function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
WARNING:plaidml:Failed to build program kernel_1: CL_INVALID_OPERATION
WARNING:plaidml:Failed to build program kernel_1
WARNING:plaidml:Failed build log: 
WARNING:plaidml:Code was: 
    1: #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    2: 
    3: 
    4: #pragma OPENCL EXTENSION cl_intel_subgroups : enable
    5: 
    6: #define vector_load(x) as_float(intel_sub_group_block_read((const global int*) (&(x))))
    7: #define vector_store(x, v) intel_sub_group_block_write((const global int*) (&(x)), as_uint(v))
    8: 
    9: // gid: 3 3 1
   10: // lid: 0 0 0
   11: //kernel_0(X_I_0,X_I_1)
   12: //X_T1[x, y : _T0, _T1] = +(X_I_0[x, z] * X_I_1[z, y])
   13: __kernel void kernel_1(__global float* restrict  rb_d1_X_T1, __global const float* restrict  rb_d1_X_I_0, __global const float* restrict  rb_d1_X_I_1)
   14: {
   15:   int d3_y = (get_global_id(1) % 3);
   16:   int d3_x = (get_global_id(0) % 3);
   17:   int ri_3_X_T1_raw = ((3 * d3_x) + (1 * d3_y));
   18:   int ri_3_X_T1 = 0;
   19:   int ri_3_X_I_1 = (1 * d3_y);
   20:   int ri_3_X_I_0 = (3 * d3_x);
   21:   float rb_d3_X_T1[1] = {0, };
   22:   {
   23:     int ri_4_X_I_0 = (0 + ri_3_X_I_0);
   24:     int ri_4_X_I_1 = (0 + ri_3_X_I_1);
   25:     int ri_4_X_T1 = (0 + ri_3_X_T1);
   26:     for (int d4_z = 0; d4_z < 3; d4_z += 1)
   27:     {
   28:       {
   29:         float s_4_X_I_0 = rb_d1_X_I_0[ri_4_X_I_0];
   30:         float s_4_X_I_1 = rb_d1_X_I_1[ri_4_X_I_1];
   31:         float s_4_X_T1 = (s_4_X_I_0 * s_4_X_I_1);
   32:         rb_d3_X_T1[ri_4_X_T1] = (rb_d3_X_T1[ri_4_X_T1] + s_4_X_T1);
   33:       }
   34:       ri_4_X_I_0 = (ri_4_X_I_0 + 1);
   35:       ri_4_X_I_1 = (ri_4_X_I_1 + 3);
   36:     }
   37:   }
   38:   {
   39:     int ri_4_dst = (0 + ri_3_X_T1_raw);
   40:     int ri_4_src = (0 + ri_3_X_T1);
   41:     {
   42:       float s_4_X = rb_d3_X_T1[ri_4_src];
   43:       rb_d1_X_T1[ri_4_dst] = s_4_X;
   44:     }
   45:   }
   46: }

Traceback (most recent call last):
  File "/media/data/Code/Other_repos/plaidml/plaidml/bin/plaidml-setup", line 8, in <module>
    sys.exit(main())
  File "/media/data/Code/Other_repos/plaidml/plaidml/lib/python3.8/site-packages/plaidml/plaidml_setup.py", line 145, in main
    plaidml.run(ctx, matmul, inputs={"B": b, "C": c}, outputs={"A": a})
  File "/media/data/Code/Other_repos/plaidml/plaidml/lib/python3.8/site-packages/plaidml/__init__.py", line 1501, in run
    Invoker(ctx, f, inputs, outputs).invoke()
  File "/media/data/Code/Other_repos/plaidml/plaidml/lib/python3.8/site-packages/plaidml/__init__.py", line 1475, in invoke
    return Invocation(self._ctx, self)
  File "/media/data/Code/Other_repos/plaidml/plaidml/lib/python3.8/site-packages/plaidml/__init__.py", line 1484, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/media/data/Code/Other_repos/plaidml/plaidml/lib/python3.8/site-packages/plaidml/__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "/media/data/Code/Other_repos/plaidml/plaidml/lib/python3.8/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: The state of the promise has already been set.


$ plaidbench keras mobilenet
Running 1024 examples with mobilenet, batch size 1, on backend plaid
INFO:plaidml:Opening device "llvm_cpu.0"
Compiling network... Warming up... Running...
Example finished, elapsed: 4.638s (compile), 187.369s (execution)

-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS          
-----------------------------------------------------------------------------------------
mobilenet            182.98 ms                 181.28 ms / 5.52 fps
Correctness: PASS, max_error: 1.7640328223933466e-05, max_abs_error: 7.040798664093018e-07, fail_ratio: 0.0

$ plaidbench keras mobilenet
Running 1024 examples with mobilenet, batch size 1, on backend plaid
INFO:plaidml:Opening device "opencl_intel_gen9_hd_graphics_neo.0"
Compiling network... Warming up... Running...
Example finished, elapsed: 33.803s (compile), 20.943s (execution)

-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS          
-----------------------------------------------------------------------------------------
mobilenet            20.45 ms                  10.68 ms / 93.62 fps
Correctness: PASS, max_error: 1.0642305824148934e-05, max_abs_error: 7.450580596923828e-07, fail_ratio: 0.0
```

**Comment by tech0x** [comment]
I have same problem, how they fix ?
opencl_intel_hd_graphics_ivybridge_m_gt2.0
Tile code:
```
  function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
WARNING:plaidml:Failed to build program kernel_1: CL_INVALID_OPERATION
WARNING:plaidml:Failed to build program kernel_1
WARNING:plaidml:Failed build log: 
WARNING:plaidml:Code was: 
    1: 
    2: 
    3: #pragma OPENCL EXTENSION cl_intel_subgroups : enable
    4: 
    5: #define vector_load(x) as_float(intel_sub_group_block_read((const global int*) (&(x))))
    6: #define vector_store(x, v) intel_sub_group_block_write((const global int*) (&(x)), as_uint(v))
    7: 
    8: // gid: 3 3 1
    9: // lid: 0 0 0
   10: //kernel_0(X_I_0,X_I_1)
   11: //X_T1[x, y : _T0, _T1] = +(X_I_0[x, z] * X_I_1[z, y])
   12: __kernel void kernel_1(__global float* restrict  rb_d1_X_T1, __global const float* restrict  rb_d1_X_I_0, __global const float* restrict  rb_d1_X_I_1)
   13: {
   14:   int d3_y = (get_global_id(1) % 3);
   15:   int d3_x = (get_global_id(0) % 3);
   16:   int ri_3_X_T1_raw = ((3 * d3_x) + (1 * d3_y));
   17:   int ri_3_X_T1 = 0;
   18:   int ri_3_X_I_1 = (1 * d3_y);
   19:   int ri_3_X_I_0 = (3 * d3_x);
   20:   float rb_d3_X_T1[1] = {0, };
   21:   {
   22:     int ri_4_X_I_0 = (0 + ri_3_X_I_0);
   23:     int ri_4_X_I_1 = (0 + ri_3_X_I_1);
   24:     int ri_4_X_T1 = (0 + ri_3_X_T1);
   25:     for (int d4_z = 0; d4_z < 3; d4_z += 1)
   26:     {
   27:       {
   28:         float s_4_X_I_0 = rb_d1_X_I_0[ri_4_X_I_0];
   29:         float s_4_X_I_1 = rb_d1_X_I_1[ri_4_X_I_1];
   30:         float s_4_X_T1 = (s_4_X_I_0 * s_4_X_I_1);
   31:         rb_d3_X_T1[ri_4_X_T1] = (rb_d3_X_T1[ri_4_X_T1] + s_4_X_T1);
   32:       }
   33:       ri_4_X_I_0 = (ri_4_X_I_0 + 1);
   34:       ri_4_X_I_1 = (ri_4_X_I_1 + 3);
   35:     }
   36:   }
   37:   {
   38:     int ri_4_dst = (0 + ri_3_X_T1_raw);
   39:     int ri_4_src = (0 + ri_3_X_T1);
   40:     {
   41:       float s_4_X = rb_d3_X_T1[ri_4_src];
   42:       rb_d1_X_T1[ri_4_dst] = s_4_X;
   43:     }
   44:   }
   45: }

Traceback (most recent call last):
  File "/.plaidml/bin/plaidml-setup", line 8, in <module>
    sys.exit(main())
  File "/.plaidml/lib/python3.6/site-packages/plaidml/plaidml_setup.py", line 145, in main
    plaidml.run(ctx, matmul, inputs={"B": b, "C": c}, outputs={"A": a})
  File "/.plaidml/lib/python3.6/site-packages/plaidml/__init__.py", line 1501, in run
    Invoker(ctx, f, inputs, outputs).invoke()
  File "/.plaidml/lib/python3.6/site-packages/plaidml/__init__.py", line 1475, in invoke
    return Invocation(self._ctx, self)
  File "/.plaidml/lib/python3.6/site-packages/plaidml/__init__.py", line 1484, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
  File "/.plaidml/lib/python3.6/site-packages/plaidml/__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "/.plaidml/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: The state of the promise has already been set.

(.plaidml) root@x230i:~# clinfo 
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing
  Platform Extensions function suffix             Intel

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 1
  Device Name                                     Intel(R) HD Graphics IvyBridge M GT2
  Device Vendor                                   Intel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 beignet 1.3
  Driver Version                                  1.3
  Device OpenCL C Version                         OpenCL C 1.2 beignet 1.3
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               16
  Max clock frequency                             1000MHz
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None, None, None
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
  Preferred work group size multiple              16
  Preferred / native vector sizes                 
    char                                                16 / 8       
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 8        (n/a)
    float                                                4 / 4       
    double                                               0 / 2        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           1610612736 (1.5GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        8192 (8KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4096 bytes
    Pitch alignment for 2D image buffers          1 pixels
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             8192x8192x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max number of constant args                     8
  Max constant buffer size                        134217728 (128MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      80ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                __cl_copy_region_align4;__cl_copy_region_align16;__cl_cpy_region_unalign_same_offset;__cl_copy_region_unalign_dst_offset;__cl_copy_region_unalign_src_offset;__cl_copy_buffer_rect;__cl_copy_image_1d_to_1d;__cl_copy_image_2d_to_2d;__cl_copy_image_3d_to_2d;__cl_copy_image_2d_to_3d;__cl_copy_image_3d_to_3d;__cl_copy_image_2d_to_buffer;__cl_copy_image_3d_to_buffer;__cl_copy_buffer_to_image_2d;__cl_copy_buffer_to_image_3d;__cl_fill_region_unalign;__cl_fill_region_align2;__cl_fill_region_align4;__cl_fill_region_align8_2;__cl_fill_region_align8_4;__cl_fill_region_align8_8;__cl_fill_region_align8_16;__cl_fill_region_align128;__cl_fill_image_1d;__cl_fill_image_1d_array;__cl_fill_image_2d;__cl_fill_image_2d_array;__cl_fill_image_3d;block_motion_estimate_intel;
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing cl_intel_motion_estimation

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [Intel]
  clCreateContext(NULL, ...) [default]            Success [Intel]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics IvyBridge M GT2
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics IvyBridge M GT2
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel Gen OCL Driver
    Device Name                                   Intel(R) HD Graphics IvyBridge M GT2

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
```
