### ISSUE TITLE
Build failure with bazel 0.8.0

### ISSUE THREAD

**Issue by jwatte** [plaidml/plaidml#66]
I tried to build it on my Ubuntu x86_64 machine, after downloading/installing bazel 0.8.0, and it failed:

```
[09:04] jwatte@ripper:/usr/local/src/plaidml$ bazel build plaidml:wheel plaidml/keras:wheel
........
ERROR: /usr/local/src/plaidml/plaidml/BUILD:21:1: Traceback (most recent call last):
        File "/usr/local/src/plaidml/plaidml/BUILD", line 21
                plaidml_proto_library(name = "proto", srcs = ["plaidml.p..."], ..."])
        File "/usr/local/src/plaidml/bzl/plaidml.bzl", line 81, in plaidml_proto_library
                plaidml_cc_proto_library(name = name, srcs = srcs, deps = dep..., <5 more arguments>)
        File "/usr/local/src/plaidml/bzl/plaidml.bzl", line 116, in plaidml_cc_proto_library
                cc_proto_library(name = (name + "_cc"), srcs = srcs, <7 more arguments>)
        File "/usr/local/src/plaidml/bzl/protobuf.bzl", line 193, in cc_proto_library
                cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: error loading package 'plaidml': Package 'plaidml' contains errors
INFO: Elapsed time: 0.491s
FAILED: Build did NOT complete successfully (2 packages loaded)

```
Using a git checkout from today.

Note that I'm running Ubuntu 17.04, so not one of the "officially supported" versions, but 16.04 doesn't support some of my hardware.

**Comment by earhart** [comment]
Thanks for the report!  We'll definitely be updating our code to work with Bazel 0.8.0 soon; in the meantime, we recommend sticking with 0.7.0.

**Comment by znmeb** [comment]
I just ran into this - BTW, I think Bazel's up to 0.9.0

**Comment by brianretford** [comment]
We now require 0.9.0
