### ISSUE TITLE
Problem with aggregation calculation

### ISSUE THREAD

**Issue by shijianjian** [plaidml/plaidml#672]
I was testing plaidml with keras-rl package with https://github.com/keras-rl/keras-rl/blob/master/examples/sarsa_cartpole.py

It gives the error message like below:
```
Traceback (most recent call last):
  File "sarsa_test.py", line 39, in <module>
    sarsa.compile(Adam(lr=1e-3), metrics=['mae'])
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/rl/agents/sarsa.py", line 99, in compile
    trainable_model.compile(optimizer=optimizer, loss=losses, metrics=combined_metrics)
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training.py", line 342, in compile
    sample_weight, mask)
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training_utils.py", line 420, in weighted
    axis=list(range(weight_ndim, ndim)))
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/plaidml/keras/backend.py", line 905, in mean
    return op.mean(x, axes=axis, keepdims=keepdims, floatx=ptile.convert_np_dtype_to_pml(floatx()))
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/plaidml/op.py", line 2082, in mean
    return Mean.function(x, axes=axes, keepdims=keepdims, floatx=floatx)
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/plaidml/tile.py", line 256, in function
    operation = cls(*args, **kwargs)
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/plaidml/op.py", line 2059, in __init__
    shape, axes, subs = tile.compute_aggregation_axes(x.shape.dims, axes, keepdims)
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/plaidml/tile.py", line 1357, in compute_aggregation_axes
    reduce_indices = [dest_indices[i] for i in axes]
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/plaidml/tile.py", line 1357, in <listcomp>
    reduce_indices = [dest_indices[i] for i in axes]
IndexError: list index out of range
```

It looks like a problem with **dest_indices** and **axes** in the function but I cannot tell where goes wrong while debuggin.

**Comment by dgkutnic** [comment]
Thanks for reporting this bug @shijianjian. We have reproduced it on our end and can confirm that there was an internal function trying to get aggregation axes and passing an invalid value of `axes` (an axis that did not exist in the shape) to `compute_aggregation_axes`. This caused the `out of range` error. We'll dig into this further; however, we're not confident that it is an easy fix.

**Comment by shijianjian** [comment]
HI @dgkutnic,

Thanks for looking into this. I have run some experiments that found the error comes from the difference between how Tensorflow and PlaidML deal with `ndim` property, especially when one-dimension array encountered.

The error comes from
```
  File "/Users/jians/anaconda3/envs/dl/lib/python3.6/site-packages/keras/engine/training_utils.py", line 421, in weighted
```
in which it computes
```
            ndim = K.ndim(score_array)
            weight_ndim = K.ndim(weights)
            score_array = K.mean(score_array,
                                 axis=list(range(weight_ndim, ndim)))
```
Here, I would assume that we prefer not to modify the keras code.

In Tensorflow, we got the tensor below
```
Tensor("loss/Sum:0", shape=(?,), dtype=float32), ndim=1
```
While in PlaidML:
```
Summation FLOAT32(<tile.Value Operation UINT64()>,), ndim=2
```

Hence, while computing `list(range(weight_ndim, ndim)))`, Tensorflow get `[]` back while PlaidML got `[1]`, which is exactly where the "invalid axes" comes from.

I suspect we shall either update the cpp code or to refine the logic of `compute_aggregation_axes ` for handling the one-dimension array.

JS

**Comment by maxekman** [comment]
I'm a complete ML beginner, but googled myself here. Got the same error when trying out Keras from this tutorial (with PlaidML backend): https://medium.com/@abhishek.bn93/using-keras-reinforcement-learning-api-with-openai-gym-6c2a35036c83

Related code:

```python
def agent(states, actions):
    model = Sequential()
    model.add(Flatten(input_shape=(1, states)))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(actions, activation='linear'))
    return model

model = agent(env.observation_space.shape[0], env.action_space.n)
policy = EpsGreedyQPolicy()
sarsa = SARSAAgent(model=model, policy=policy, nb_actions=env.action_space.n)
sarsa.compile('adam', metrics=['mse'])
sarsa.fit(env, nb_steps=50000, visualize=False, verbose=1)
```

**Comment by dmckinno** [comment]
@shijianjian, @dgkutnic do either of you two have a suggestion for working around this issue? I'm using keras-rl for a short-term fun project and can totally modify that keras code if need be, but I would prefer a more permanent fix.

**Comment by shijianjian** [comment]
@dmckinno Sorry, I do not think there is an easy fix here.

@dgkutnic Can PlaidML2 work this around?
