### ISSUE TITLE
Word Embeddings support

### ISSUE THREAD

**Issue by edmondja** [plaidml/plaidml#70]
Hi, is it scheduled to support word embeddings ?

import numpy as np
import pandas as pd
import plaidml.keras
plaidml.keras.install_backend()
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.advanced_activations import ELU
from keras.layers.recurrent import LSTM, GRU
from keras.layers.core import Flatten
from keras.layers.embeddings import Embedding
from sklearn.metrics import mean_squared_error
import random, time
# Read in data
from keras.regularizers import l2
from keras.layers import Input, merge
from keras.models import Model

def saveModel(model):
    modelCopy = {}
    modelCopy['layers'] = []
    for i in range(len(model.layers)+1):
        modelCopy['layers'].append(model.get_layer(index=i))
    modelCopy['weights'] = (model.get_weights())
    return modelCopy

ratings = pd.read_csv('u.data', sep='\t')
ratings.columns=['userId', 'movieId', 'rating', 'ts']
nusers, nmovies = ratings.userId.nunique(), ratings.movieId.nunique()
movies = np.unique(np.array(ratings.movieId))
dictMovies = {movies[i]:i+1 for i in range(nmovies)}
ratings.movieId = ratings.movieId.replace(dictMovies)

np.random.seed(42)
msk = np.random.rand(len(ratings))<0.8

trn = ratings[msk]
val = ratings[~msk]
k= 70

user_in = Input(shape=(1,), dtype='int64', name='user_in')
u = Embedding(nusers+1, int(k*3/2), input_length=1)(user_in)
movie_in = Input(shape=(1,), dtype='int64', name='movie_in')
m = Embedding(nmovies+1, int(k*1/2), input_length=1)(movie_in)

x= merge([u, m], mode='concat')
x= Flatten()(x)
x = Dropout(0.5)(x)

x = Dense(int(k/2), activation='elu')(x)
x = Dropout(0.5)(x)
x = Dense(1)(x)
model = Model([user_in, movie_in], x)
model.compile(loss='mean_squared_error', optimizer="nadam")

patience, nbEpoch, bestError, begin = 0, 0, 999999.9, time.time()

# Manual Earlystopping: Patience < nb allowed fails
while((time.time()-begin<240)&(patience<10)): 
    X_train, Y_train = [trn.userId, trn.movieId], trn.rating
    patience += 1
    nbEpoch += 1
    model.fit(X_train, Y_train, batch_size=512, nb_epoch=1, verbose=1)
    yhat= model.predict( [val.userId, val.movieId]) 
    error = mean_squared_error(val.rating, yhat)
    if(error<bestError):
        duration, patience = time.time()-begin, 0
        bestEpoch, bestError = nbEpoch, error
        print(bestError)
INFO:plaidml:b'Opening device "intel(r)_iris(tm)_graphics_6100.0"'
__main__:47: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/legacy/layers.py:458: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
Traceback (most recent call last):

  File "<ipython-input-1-93c9edd2d80e>", line 49, in <module>
    x = Dropout(0.5)(x)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/layers/core.py", line 111, in call
    training=training)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 1855, in in_train_phase
    cx = x()

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/layers/core.py", line 109, in dropped_inputs
    seed=self.seed)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 1691, in dropout
    side_effects = {_plaidml_val(rng_state): _plaidml_val(n)}

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 181, in _plaidml_val
    return x._plaidml_val(indent)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 852, in _plaidml_val
    a.add_input(k, _plaidml_val(v, indent + 1))

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 181, in _plaidml_val
    return x._plaidml_val(indent)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 852, in _plaidml_val
    a.add_input(k, _plaidml_val(v, indent + 1))

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 181, in _plaidml_val
    return x._plaidml_val(indent)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 852, in _plaidml_val
    a.add_input(k, _plaidml_val(v, indent + 1))

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 181, in _plaidml_val
    return x._plaidml_val(indent)

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/plaidml/keras/backend.py", line 856, in _plaidml_val
    str(e), self, self.traceback()))

PlaidMLKerasException: b'Applying function, tensor with mismatching dimensionality: I0, expected=3, got=2'
Traceback:
_Op(concatenate)
outputs: O
inputs:
  I0: _Op(gather)
  outputs: OUT
  inputs:
    V: embedding_1/embeddings[944, 105]
    embedding_1/embeddings[944, 105]
    I: _Op(cast_as_int32)
    outputs: O
    inputs:
      I: user_in[None, 1]
      user_in[None, 1]
  I1: _Op(gather)
  outputs: OUT
  inputs:
    V: embedding_2/embeddings[1683, 35]
    embedding_2/embeddings[1683, 35]
    I: _Op(cast_as_int32)
    outputs: O
    inputs:
      I: movie_in[None, 1]
      movie_in[None, 1]

(Same error with the sequential API and with other use cases)

**Comment by jbruestle** [comment]
We are currently working on support for Embedding layers, since it's also blocking the network example from #78, and I expect a fix soon on that.  However once that's fixed, you are still going to have issues with the LSTM part (see #24).  We are also working on that, but LSTM support is a bit more complex and will take a bit longer.

**Comment by brianretford** [comment]
We support embedding layers and simple RNNs now, but they can be slow. Duplicate of #171
