### ISSUE TITLE
plaidml support for keras version

### ISSUE THREAD

**Issue by shahidbc** [plaidml/plaidml#727]
Can anybody share the working plaidml version with keras version and tensorflow version. I am using keras 2.2.4 with plaidml 0.6.4 using tensorflow 1.14 but I am getting the following error:
File "C:\Users\shahid\Anaconda3\envs\tfv\lib\site-packages\plaidml\tile.py", line 836, in from_python_value
NotImplementedError: Unable to build a Value from a 'tuple' instance

**Comment by dgkutnic** [comment]
Hi @shahidbc,

We support keras 2.24 in plaidml 0.6.4. How are you connecting TensorFlow in to PlaidML (are you using `ngraph-bridge`)? Can you tell us a little bit about what you were trying to do that caused this error?

**Comment by shahidbc** [comment]
Hi dgkutnic

Thanks for the reply. Actually, I read about configuring nvidia GPU for Keras using Plaidml. I installed following packages: 
keras 2.2.4 
keras-applications-1.0.8
keras-preprocessing-1.1.0
plaidml-keras-0.6.4
plaidml 0.6.4
plaidbench 0.6.4
tensorflow 1.8.0
Then I only added following line to keras code:
 os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
and leave all the rest as it. As I only installed tensorflow at the backend so for keras only the code is working fine and training without error. But when I use the plaidml.keras.backend it throws the said error. I do not know about ngraph-bridge and have not used it.
I am new to the field so please guide me to resolve this issue.

**Comment by dgkutnic** [comment]
Thanks for your response. 

Is there any way that you can provide us with a code snippet showing us the training that you are trying to run when this error occurs? The description of the error alone does not tell us much about why the error has occurred.

**Comment by shahidbc** [comment]
Thanks for the further query on the issue:

Here is the code I used to train model with pre-trained YOLO v3 weights.

###########################################################
"""
Retrain the YOLO model for your own dataset.
"""
import os
#os.environ['CUDA_VISIBLE_DEVICES'] = '0'
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

import numpy as np
import keras.backend as K
from keras.layers import Input, Lambda
from keras.models import Model
from keras.optimizers import Adam
from keras.callbacks import TensorBoard, ModelCheckpoint, ReduceLROnPlateau, EarlyStopping

from yolo3.model import preprocess_true_boxes, yolo_body, tiny_yolo_body, yolo_loss
from yolo3.utils import get_random_data


def _main():
    annotation_path = '4_CLASS_test.txt'
    log_dir = 'logs/000/'
    classes_path = '4_CLASS_test_classes.txt'
    anchors_path = 'model_data/yolo_anchors.txt'
    class_names = get_classes(classes_path)
    num_classes = len(class_names)
    anchors = get_anchors(anchors_path)

    input_shape = (416,416) # multiple of 32, hw

    is_tiny_version = len(anchors)==6 # default setting
    if is_tiny_version:
        model = create_tiny_model(input_shape, anchors, num_classes,
            freeze_body=2, weights_path='model_data/yolo_weights.h5')
    else:
        model = create_model(input_shape, anchors, num_classes, freeze_body=2, weights_path='model_data/yolo_weights.h5') # make sure you know what you freeze


    logging = TensorBoard(log_dir=log_dir)
    checkpoint = ModelCheckpoint(log_dir + 'ep{epoch:03d}-loss{loss:.3f}-val_loss{val_loss:.3f}.h5',
        monitor='val_loss', save_weights_only=True, save_best_only=True, period=3)
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=3, verbose=1)
    early_stopping = EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1)

    val_split = 0.1
    with open(annotation_path) as f:
        lines = f.readlines()
    np.random.shuffle(lines)
    num_val = int(len(lines)*val_split)
    num_train = len(lines) - num_val

    # Train with frozen layers first, to get a stable loss.
    # Adjust num epochs to your dataset. This step is enough to obtain a not bad model.
    if True:
        model.compile(optimizer=Adam(lr=1e-3), loss={
            # use custom yolo_loss Lambda layer.
            'yolo_loss': lambda y_true, y_pred: y_pred})

        batch_size = 32
        print('Train on {} samples, val on {} samples, with batch size {}.'.format(num_train, num_val, batch_size))
        model.fit_generator(data_generator_wrapper(lines[:num_train], batch_size, input_shape, anchors, num_classes),
                steps_per_epoch=max(1, num_train//batch_size),
                validation_data=data_generator_wrapper(lines[num_train:], batch_size, input_shape, anchors, num_classes),
                validation_steps=max(1, num_val//batch_size),
                epochs=50,
                initial_epoch=0,
                callbacks=[logging, checkpoint])
        model.save_weights(log_dir + 'trained_weights_stage_1.h5')

    # Unfreeze and continue training, to fine-tune.
    # Train longer if the result is not good.
    if True:
        for i in range(len(model.layers)):
            model.layers[i].trainable = True
        model.compile(optimizer=Adam(lr=1e-4), loss={'yolo_loss': lambda y_true, y_pred: y_pred}) # recompile to apply the change
        print('Unfreeze all of the layers.')

        batch_size = 8 # note that more GPU memory is required after unfreezing the body
        print('Train on {} samples, val on {} samples, with batch size {}.'.format(num_train, num_val, batch_size))
        model.fit_generator(data_generator_wrapper(lines[:num_train], batch_size, input_shape, anchors, num_classes),
            steps_per_epoch=max(1, num_train//batch_size),
            validation_data=data_generator_wrapper(lines[num_train:], batch_size, input_shape, anchors, num_classes),
            validation_steps=max(1, num_val//batch_size),
            epochs=100,
            initial_epoch=50,
            callbacks=[logging, checkpoint, reduce_lr, early_stopping])
        model.save_weights(log_dir + 'trained_weights_final.h5')

    # Further training if needed.


def get_classes(classes_path):
    '''loads the classes'''
    with open(classes_path) as f:
        class_names = f.readlines()
    class_names = [c.strip() for c in class_names]
    return class_names

def get_anchors(anchors_path):
    '''loads the anchors from a file'''
    with open(anchors_path) as f:
        anchors = f.readline()
    anchors = [float(x) for x in anchors.split(',')]
    return np.array(anchors).reshape(-1, 2)


def create_model(input_shape, anchors, num_classes, load_pretrained=True, freeze_body=2,
            weights_path='model_data/yolo_weights.h5'):
    '''create the training model'''
    K.clear_session() # get a new session
    image_input = Input(shape=(None, None, 3))
    h, w = input_shape
    num_anchors = len(anchors)

    y_true = [Input(shape=(h//{0:32, 1:16, 2:8}[l], w//{0:32, 1:16, 2:8}[l], \
        num_anchors//3, num_classes+5)) for l in range(3)]

    model_body = yolo_body(image_input, num_anchors//3, num_classes)
    print('Create YOLOv3 model with {} anchors and {} classes.'.format(num_anchors, num_classes))

    if load_pretrained:
        model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
        print('Load weights {}.'.format(weights_path))
        if freeze_body in [1, 2]:
            # Freeze darknet53 body or freeze all but 3 output layers.
            num = (185, len(model_body.layers)-3)[freeze_body-1]
            for i in range(num): model_body.layers[i].trainable = False
            print('Freeze the first {} layers of total {} layers.'.format(num, len(model_body.layers)))

    model_loss = Lambda(yolo_loss, output_shape=(1,), name='yolo_loss',
        arguments={'anchors': anchors, 'num_classes': num_classes, 'ignore_thresh': 0.5})(
        [*model_body.output, *y_true])
    model = Model([model_body.input, *y_true], model_loss)

    return model

def create_tiny_model(input_shape, anchors, num_classes, load_pretrained=True, freeze_body=2,
            weights_path='model_data/tiny_yolo_weights.h5'):
    '''create the training model, for Tiny YOLOv3'''
    K.clear_session() # get a new session
    image_input = Input(shape=(None, None, 3))
    h, w = input_shape
    num_anchors = len(anchors)

    y_true = [Input(shape=(h//{0:32, 1:16}[l], w//{0:32, 1:16}[l], \
        num_anchors//2, num_classes+5)) for l in range(2)]

    model_body = tiny_yolo_body(image_input, num_anchors//2, num_classes)
    print('Create Tiny YOLOv3 model with {} anchors and {} classes.'.format(num_anchors, num_classes))

    if load_pretrained:
        model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
        print('Load weights {}.'.format(weights_path))
        if freeze_body in [1, 2]:
            # Freeze the darknet body or freeze all but 2 output layers.
            num = (20, len(model_body.layers)-2)[freeze_body-1]
            for i in range(num): model_body.layers[i].trainable = False
            print('Freeze the first {} layers of total {} layers.'.format(num, len(model_body.layers)))

    model_loss = Lambda(yolo_loss, output_shape=(1,), name='yolo_loss',
        arguments={'anchors': anchors, 'num_classes': num_classes, 'ignore_thresh': 0.7})(
        [*model_body.output, *y_true])
    model = Model([model_body.input, *y_true], model_loss)

    return model

def data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes):
    '''data generator for fit_generator'''
    n = len(annotation_lines)
    i = 0
    while True:
        image_data = []
        box_data = []
        for b in range(batch_size):
            if i==0:
                np.random.shuffle(annotation_lines)
            image, box = get_random_data(annotation_lines[i], input_shape, random=True)
            image_data.append(image)
            box_data.append(box)
            i = (i+1) % n
        image_data = np.array(image_data)
        box_data = np.array(box_data)
        y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes)
        yield [image_data, *y_true], np.zeros(batch_size)

def data_generator_wrapper(annotation_lines, batch_size, input_shape, anchors, num_classes):
    n = len(annotation_lines)
    if n==0 or batch_size<=0: return None
    return data_generator(annotation_lines, batch_size, input_shape, anchors, num_classes)

if __name__ == '__main__':
    _main()
######################################################################

And here is the error I am getting:

##############################################################
Using plaidml.keras.backend backend.
INFO:plaidml:Opening device "llvm_cpu.0"
Create YOLOv3 model with 9 anchors and 4 classes.
Load weights model_data/yolo_weights.h5.
Freeze the first 249 layers of total 252 layers.
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    _main()
  File "train.py", line 35, in _main
    model = create_model(input_shape, anchors, num_classes, freeze_body=2, weights_path='model_data/yolo_weights.h5') # make sure you know what you freeze
  File "train.py", line 131, in create_model
    [*model_body.output, *y_true])
  File "C:\Users\shahid\Anaconda3\envs\tfv\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\shahid\Anaconda3\envs\tfv\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "F:\YOLOv3-object-detection-tutorial-master\YOLOv3-custom-training\yolo3\model.py", line 365, in yolo_loss
    input_shape = K.cast(K.shape(yolo_outputs[0])[1:3] * 32, K.dtype(y_true[0]))
  File "C:\Users\shahid\Anaconda3\envs\tfv\lib\site-packages\plaidml\keras\backend.py", line 406, in cast
    x = ptile.Value.from_python_value(x)
  File "C:\Users\shahid\Anaconda3\envs\tfv\lib\site-packages\plaidml\tile.py", line 836, in from_python_value
    py_val.__class__.__name__))
NotImplementedError: Unable to build a Value from a 'tuple' instance

#####################################################################

When I remove the plaidml.keras.backend and run code on keras.backend it runs fine. Please guide me to resolve it I am much concerned to use Plaidml-keras to utilize the computatioins of AMD GPU for deep learning.

**Comment by dgkutnic** [comment]
Hi @shahidbc,

Thanks for providing us with a code sample.

Your example seems to be failing on the following line:
```
input_shape = K.cast(K.shape(yolo_outputs[0])[1:3] * 32, K.dtype(y_true[0]))
```

According to the [keras definition of cast](https://keras.io/backend/#cast), the function is built to cast a tensor to a different dtype. However, the code that seems to be failing is casting a tuple, not a tensor. PlaidML does not support this type of casting because our implementation of cast expects a tensor. 

You may be able to fix this by using `numpy.ndarray.astype` instead of `K.cast`, however, I’d encourage you to figure out what the `cast` is doing and whether it is even needed at all.

**Comment by masc-it** [comment]
same problem here, @dgkutnic if I try to use your solution, I get a numpy error that says: max dimension for ndarray is 32, found 64.
