### ISSUE TITLE
Error when trying to implement Minibatch standard deviation layer (from PGGAN paper)

### ISSUE THREAD

**Issue by erikrause** [plaidml/plaidml#961]
I have a custom MinibatchStdev layer is after the Input layer with input shape (None, 16, 16, 16, 1):

```
class MinibatchStdev(Layer):
    def __init__(self, **kwargs):
        super(MinibatchStdev, self).__init__(**kwargs)

    def call(self, inputs):
        mean = backend.mean(inputs, axis=0, keepdims=True)
        squ_diffs = backend.square(inputs - mean)
        mean_sq_diff = backend.mean(squ_diffs, axis=0, keepdims=True)
        mean_sq_diff += 1e-8
        stdev = backend.sqrt(mean_sq_diff)
        mean_pix = backend.mean(stdev, keepdims=True)
        shape = backend.shape(inputs)
        output = backend.tile(mean_pix, (shape[0], shape[1], shape[2],shape[3], 1))  
        combined = backend.concatenate([inputs, output], axis=-1)
        return combined

    def compute_output_shape(self, input_shape):
        input_shape = list(input_shape)
        input_shape[-1] += 1
        return tuple(input_shape)
```
When calling train_on_batch method the program gives an error:
```
ERROR:plaidml:syntax` error, unexpected ID, expecting "," or ] :
        function (I[S0, S1, S2, S3, S4]) -> (O) {
            O[t0 * S0 + i0, t1 * S1 + i1, t2 * S2 + i2, t3 * S3 + i3, t4 * S4 + i4 : S0 * SymbolicDim UINT64(), S1 * 16, S2 * 16, S3 * 16, S4 * 1] = =(I[i0, i1, i2, i3, i4]), t0 < SymbolicDim UINT64(), t1 < 16, t2 < 16, t3 < 16, t4 < 1 no_defract;
        }
Traceback (most recent call last):
  File "G:\8 semestr\МСПИС\Neural\GAN-porous-structures\main.py", line 65, in <module>
    model_handler.train(n_straight, n_fadein, batch_size, sample_interval)
  File "G:\8 semestr\МСПИС\Neural\GAN-porous-structures\modules\ModelHandler.py", line 389, in train
    self.train_block(iterations, batch_size, sample_interval, n_resolution)
  File "G:\8 semestr\МСПИС\Neural\GAN-porous-structures\modules\ModelHandler.py", line 519, in train_block
    self.d_loss_real = d_model.train_on_batch(imgs, real[:batch_size//2])
  File "D:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "D:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 519, in _make_train_function
    **self._function_kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\keras\backend.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\keras\backend.py", line 823, in function
    return _Function(inputs, outputs, updates, name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\keras\backend.py", line 161, in __init__
    name=name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\tile.py", line 1058, in compose
    bindings.insert(op, op.bind(bindings))
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\tile.py", line 280, in bind
    func = plaidml.Function(self.code, backtrace=self.backtrace, fid=safe_name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\__init__.py", line 925, in __init__
    self).__init__(_lib().plaidml_build_coded_function(code.encode(), fid.encode()))
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "D:\ProgramData\Anaconda3\lib\site-packages\plaidml\library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.ResourceExhausted: Out of memory
```
But the same code works good with tensorflow backend.
Why is this happening? PlaidML cant work with variable batch size? Do i need to explicitly define batch_size in my model?

**Comment by erikrause** [comment]
UPD: I just tried to build model with static batch size which is defined explicitly in input layer:

```
input_img = Input(batch_shape=(16,8,8,8,1))    # was Input(shape=(8,8,8,1))
d = MinibatchStdev()(input_img)
d = Conv3D...
...
```
and this works.

Is it possible to use PlaidML without explicit batch size definition?
